@extends('layouts.master')
@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.in/blog_management_service" hreflang="en-in" />
    <link rel="alternate" href="https://www.seoeaze.com/blog_management_service" hreflang="en-us" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/blog_management_service" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/blog_management_service" hreflang="x-default" />
@endsection
@section('title', 'Blog Management Service - Website Maintenance Packages -SeoEaze ')
@section('meta' , "Let professionals take care of blog while do the business, our blog management service provides complete website maintainance solution to site owners.")
<!-- Start Breadcrumbs Schema -->
	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			 "itemListElement": [{
			   "@type": "ListItem",
			   "position": 1,
			   "name": "Home",
			   "item": "https://www.seoeaze.in/"
			 },
			{
			   "@type": "ListItem",
			   "position": 2,
			   "name": "Blog Management Service",
			   "item": "https://www.seoeaze.in/blog_management_service"
			 }]
		}
	</script>
	<!-- End Breadcrumbs Schema -->
	<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What if I don’t have a blog?","acceptedAnswer":[{"@type":"Answer","text":"No worries, we can help you to set up and optimize your blog. "}]},{"@type":"Question","name":"Can I also publish to my blog?","acceptedAnswer":[{"@type":"Answer","text":"Yes, of course. You can write, publish, and edit your posts. Our blog management services will not interfere in any way."}]},{"@type":"Question","name":" What's the basic pricing for your blog management packages?","acceptedAnswer":[{"@type":"Answer","text":"Our complete blog managemement packages starts from ₹9900/Month, depending on your requirements, we can always make custom packages."}]},{"@type":"Question","name":"Can I check content before it is published?","acceptedAnswer":[{"@type":"Answer","text":"Yes. You can ask us to review the content and we will send you the edited copies. Upon approval, we will go ahead with the publishing work. "}]}]}</script><!-- Generated by https://www.seoeaze.in/ -->
@section('header')
@show
@section('content')
    <!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-6 col-md-6 col-sm-12 header-video-sec-inner-leftsec">

									<h1> BLOG MANAGEMENT SERVICE </h1>
									<p> MANAGE YOUR BLOGS THE EFFORTLESS WAY  </p>
										
									<ul>
										<li> Team of expert writers and blog marketing professionals</li>
										<li> Guaranteed post indexing </li>
										<li> SEO optimized, high quality content </li>
										<li>Fully managed blog management and maintenance  </li>
									</ul>
										
										
									<span>  
										<a href="#consultation">
											<button class="button1"> Request Consultation </button>
										</a> 
										<a href="#learn">
											<button class="button2"> Learn More </button>
										</a>
									</span>
				  			</div>

				  			<div class="col-lg-6 col-md-6 col-sm-12 header-video-sec-inner-rightsec">
				  				<img src="assets/img/blog-management/blogmanagement-headerimg.png">
				  			</div>
					</div>
			  	</div>
				
			
			</div>
			<!-- Vedio Content Section End -->
							

	</main>
			  
<!-- slider area bar end-->

<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Blog Management Service </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->

<!-- Start Content Creation Simple sec -->

	<div class="container-fluid blogmanagementservice-sec">
		<div class="container">
			<h2>Want Professionals <br>BLOG MANAGEMENT SERVICE? </h2>
			<h3>YOU ARE AT THE RIGHT PLACE</h3>
			<span class="bottomLineImgStyle"></span>
				

			
			<div class="row pt-5 mt-5">
				<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
					
						<img src="assets/img/blog-management/blog-management-service-topleftimg.jpg">
					
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
					<p>
						Blog management is the perfect marketing investment you do if you are all set to scale your content marketing but need the experts to help you. Believe it or not, blog management service helps a lot of people to read what you are actually selling. 
					</p><br>
					<p>
						The biggest benefit of blogging is to give out necessary information and to update this whenever you want. SEOEaze is the right platform to hire the best blog management services at affordable price. Blog management is the process to create, maintain and share blogs to increase the popularity of your site. 
					</p><br>
					<p>At SEOEaze, we have successfully built profitable blogs for our clients. Our team of professionals have also helped our clients build blogs that drive sales, traffic and leads.</p>
				</div>

			</div>
			<div class="row pt-5 mt-5">
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="blogmanagementservice-secondsec">
							<div class="card">
							  <img class="card-img-top" src="assets/img/blog-management/content_management_img.png" alt="Card image cap">
							  <div class="card-body">
								<h4 class="card-title">Content Management</h4>
								<span class="bottom-line-stylesmallimg"></span>
                                <p class="card-text">
									This is not about writing 500 words posts and just praying for the best. Our careful blog researching, content writing, management and editing ensure top end quality for the content we publish on your blog. We ensure of adding unique, SEO optimized and well researched content. 
								</p>
								
								
							  </div>
							</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block" id="learn">
					<div class="blogmanagementservice-secondsec">
							<div class="card">
							  <img class="card-img-top" src="assets/img/blog-management/social_media_management_img.png" alt="Card image cap">
							  <div class="card-body">
								<h4 class="card-title">Social Media Accounts Management</h4>
								<span class="bottom-line-stylesmallimg"></span>
                                <p class="card-text">Under our social media profile management solution, we offer updating latest content on social media channels like FB, Instgram, Twitter and more maintaining your secrutiy & privacy. We also ensure that your social profiles are protected and kept up to date. </p>
								
							  </div>
							</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="blogmanagementservice-secondsec">
							<div class="card">
							  <img class="card-img-top" src="assets/img/blog-management/search_engine_management_img.png" alt="Card image cap">
							  <div class="card-body">
								<h4 class="card-title">Search Engine Optimization</h4>
								<span class="bottom-line-stylesmallimg"></span>
                                <p class="card-text">When we are managing any blog, we make sure everything that goes to blog is SEO Friendly. We also help blogs by making quality backlinks for the website to boost your organic traffic & grow your business. </p>
								
							  </div>
							</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="blogmanagementservice-secondsec">
							<div class="card">
							  <img class="card-img-top" src="assets/img/blog-management/website_maintain_img.png" alt="Card image cap">
							  <div class="card-body">
								<h4 class="card-title">Website Maintenance</h4>
								<span class="bottom-line-stylesmallimg"></span>
                                <p class="card-text">Our website management service includes updating your site, fixing the bugs, managing your hosting, managing and maintaining your website security and more. It even includes preventing hack attempts, keeping the site updated and more, we ensure that your site is well maintained . </p>
								
							  </div>
							</div>
					</div>
				</div>


			</div>
			
			
			
			
			
		</div>
</div>


<!-- End Content Creation Simple sec -->





<!-- Start bannerFirst Section -->


	<div class="container-fluid bannerFirst-sec">
		<div class="container">
		<h2> Proud To Manage</h2>
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 200+ </h2>
					<p> Blogs </p>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 900+ </h2>
					<p> Social Media Channels  </p>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 500+</h2>
					<p> Websites  </p>
				</div>
			</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->





<!-- Start FEATURES AND BENEFITS Section -->


	<div class="container-fluid blogMgtfeaturesandbenefits-sec">
		<div class="container">
			<h2> BLOG MANAGEMENT FEATURES & BENEFITS </h2>
			<span class="bottomLineImgStyle"></span>
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/blog-management/blog_management_features_and_benefits_icon1.png" alt="Cinque Terre"> 
						  <h3> Top in Class Management </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> Offering top end management is the core value we follow at SEOEaze. We limit the workload of our managers so that they deliver better outcomes. </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/blog-management/blog_management_features_and_benefits_icon2.png" alt="Cinque Terre"> 
						  <h3>More Traffic </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> With the right kind of content created by our writers, we are sure that it will perform well on search engines, social media and more. All this when combined with effective promotion will double or triple your monthly traffic volume for sure. </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/blog-management/blog_management_features_and_benefits_icon3.png" alt="Cinque Terre"> 
						  <h3> Customer support </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> With our friendly customer support, you can check the progress of your project with a single click. Our team is there for you for all your blog management hassles.   </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/blog-management/blog_management_features_and_benefits_icon4.png" alt="Cinque Terre"> 
						  <h3> Cost Saving </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> By hiring our blog management service, you can be sure of saving big. We even offer customized plans as per your budget and needs. </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/blog-management/blog_management_features_and_benefits_icon5.png" alt="Cinque Terre"> 
						  <h3> Quality blog posts </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> The right plan makes all the difference and our experts figure out what to publish and when. Our blog posts attract traffic, grab the potential leads and put you as an authority. </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/blog-management/blog_management_features_and_benefits_icon6.png" alt="Cinque Terre"> 
						  <h3> Quality Content</h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> Our expert writers are pro at creating quality content for your blogs, site or social media profiles. They ensure that the content published is SEO optimized, rich and high in quality. </p>
					</div>
				</div>
			</div>
			
				
		</div>
	</div>

<!-- END FEATURES AND BENEFITS Section -->

<!-- Start customers think about us Section -->


	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>Words From Our Clients </h2>
			<h3>Our Valued Customers Believe In Us & This Is What Keeps Us Going </h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
																				<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		
		</div>
	</div>


<!-- End customers thinka bout us Section  -->

<!-- Faq start -->

<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			<h2>FAQS</h2>
			<span class="bottomLineImgStyle"></span>
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> What if I don’t have a blog? </a>
									</div>
									<div id="collapseOne" class="card-body collapse" data-parent="#accordion">
										<p>No worries, we can help you to set up and optimize your blog. </p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> Can I also publish to my blog along with you guys?</a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<p>Yes, of course. You can write, publish, and edit your posts. Our blog management services will not interfere in any way. </p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> Can I check content before it is published? </a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">
										    <p>
										        Yes. You can ask us to review the content and we will send you the edited copies. Upon approval, we will go ahead with the publishing work.  
										    </p> 
										</div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFourth">
										<a class="card-title"> What's the basic pricing for your blog management packages?</a>
									</div>
									<div id="collapseFourth" class="collapse" data-parent="#accordion">
										<div class="card-body"><p>
											Our complete blog managemement packages starts from ₹9900/Month, depending on your requirements, we can always make custom packages.

										</p> </div>
									</div>
									
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
</div>
<!-- Faq End-->

<!-- Start bannerFirst Section -->


	<div class="container-fluid ourpriandachiv-sec">
		<div class="container">
			<h2> Over 2500 Companies Trusted Us </h2>
			<span class="bottomLineImgStyle"></span>
		
			<div class="row text-center carsec-clients">
			
                           
                        <div class="parent-box8 topSlider8 owl-carousel owl-loaded owl-drag">

								
							<div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-3528px, 0px, 0px); transition: all 0.25s ease 0s; width: 9880px;"><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div></div></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button></div></div>

					</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->



<!-- Start GET YOUR FREE AUDIT REPORT Section -->

<div class="container-fluid getfreeaudit-sec">
	<div class="container">
		
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12">
					<div class="getfreeaudit-leftinnersec">
						<img src="assets/img/blog-management/getfreeaudit-sec-leftimg.jpg" alt="">
					</div>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
					<div class="getfreeaudit-rightinnersec max-auto">
						<button class="button3"> GET YOUR FREE AUDIT REPORT </button>
					</div>
				</div>
			</div>
	</div>
</div>
<!-- End GET YOUR FREE AUDIT REPORT Section -->



<!-- Start SOME HAPPY CLIENTS  Section --> 
<div class="container-fluid featureandclient-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="featureandclient-innersec">
							<h3 class="whitecolor"> OUR ACHIEVEMENTS: OUR PRIDE </h3>
						    <span class="bottomLineImgStyle"></span>
						    <p> 
								</p><ul>
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon1.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon2.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon3.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon4.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon5.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon6.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon7.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon8.png"></a></li>
									
								</ul>	
							<p></p>
					</div>
				</div>
			</div>
	</div>
</div>



<!-- End SOME HAPPY CLIENTS  Section --> 









<!-- Start ask a quote Section -->

	<div class="container-fluid askaquote-sec" id="consultation">
		<div class="container">
			<h2>Request Consultation </h2>
			<span class="bottomLineImgStyle"></span>
			
			<div class="askaquote-innersec">
				<form action="/home_page_form" method="post">
				{{ csrf_field() }}
				<div class="row">
						<div class="col-sm-3">
							<div class="inner-cuote-sec">
								<div class="form-group">
									<input name="website" type="text" class="form-control" placeholder="http://" required="">
								</div>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="inner-cuote-sec">
								<div class="form-group">
									<input type="text" name="phone" class="form-control" placeholder="Keywords" required="">
								</div>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="inner-cuote-sec">
								<div class="form-group">
									<input type="email" name="email" class="form-control" placeholder="Email" required="">
								</div>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="inner-cuote-sec m-auto">
								<div class="form-group">
									<button type="submit" class="sub-buttonclass"> Share Details</button>
								</div>
							</div>
						</div>
					</div>
				</form></div>
				

		</div>
	</div>


<!-- End ask a quote Section -->
@endsection