@extends('layouts.master')
@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.in/dedicated_seo_team" hreflang="en-in" />
    <link rel="alternate" href="https://www.seoeaze.com/dedicated_seo_team" hreflang="en-us" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/dedicated_seo_team" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/dedicated_seo_team" hreflang="x-default" />
@endsection




@section('title', 'Dedicated SEO Team -SEO Services for Large Enterprises')

@section('meta' , "IF you are a established brand, looking to hire dedicated SEO Professionals to work as dedicated SEO team, Check SEO Services for Large Enterprises -SeoEaze")
<!-- Start Breadcrumbs Schema -->
	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			 "itemListElement": [{
			   "@type": "ListItem",
			   "position": 1,
			   "name": "Home",
			   "item": "https://www.seoeaze.in/"
			 },
			{
			   "@type": "ListItem",
			   "position": 2,
			   "name": "Reputation Management Service",
			   "item": "https://www.seoeaze.in/dedicated_seo_team"
			 }]
		}
	</script>

	<!-- End Breadcrumbs Schema -->
	
<!-- Faq schema start -->
<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What kind of tools do you use for enterprise SEO?","acceptedAnswer":[{"@type":"Answer","text":"We use the most popular SEO tools for keyword research, analysis, link building and more. Other tools that we use are VWO, Google Analyics, Google Search Console etc. \n"}]},{"@type":"Question","name":"Why should I invest in your company for corporate SEO services? ","acceptedAnswer":[{"@type":"Answer","text":"SEOEaze has been rated as the best SEO Company India. We have worked very hard to be on the top position and to sustain the competition. We invest a lot of time and efforts to keep abreast with the latest search engine industry and we offer the best SEO strategies for your enterprise level business. \n"}]},{"@type":"Question","name":"Why do I need enterprise SEO?","acceptedAnswer":[{"@type":"Answer","text":"Marketers require enterprise SEO to handle the complexities of big organizations. Enterprise SEO looks at the larger picture. Also the volume of content needed and precision required for successful SEO is immense- and this is impossible to achieve without experienced and specialized team. \n"}]},{"@type":"Question","name":"What makes enterprise SEO different from other types of SEO?","acceptedAnswer":[{"@type":"Answer","text":"The needs of an enterprise are more than smaller organizations. The budget is also bigger. Enterprise SEO is different in a way that it has to manage a lot of things like conversions, traffic, online reputation, visibility etc. Services from SEOEaze will balance all these concerns for you and offer you amazing SEO results. \n"}]}]}</script><!-- Generated by https://www.seoeaze.in/ -->
<!-- Faq schema End -->

@section('header')





@show



@section('content')

   <!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-6 col-md-6 col-sm-12 header-video-sec-inner-leftsec">

									<h1> ENTERPRISE SEO SERVICES</h1>
									
									<p> Our services will help your business dominate the SERPs. At SEOEaze, we have helped a lot of enterprise level businesses to enhance their brand awareness. </p>
									
									<ul>
										<li> Grow your traffic</li>
										<li> Improve rankings </li>
										<li> Get more sales </li>
									</ul>
										
									<span class="mt-5">  
										<a href="#">
											<button class="button1"> Get started now  </button>
										</a> 
									</span>
									<p class="pt-5"><img src="assets/img/seopackages/seoPackages-sertificate.png" alt=""></p>
				  			</div>

				  			<div class="col-lg-6 col-md-6 col-sm-12 header-video-sec-inner-rightsec">
								<div class="imgblockright">	  				
									 <img src="assets/img/enterpriseseo/enterprise_seo_header-rightimg.png" alt="">
								</div>
				  			</div>
					</div>
			  	</div>
				
			
			</div>
			<!-- Vedio Content Section End -->
							

	</main>
			  
<!-- slider area bar end-->


<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Dedicated SEO Team </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->


<!-- Start DEDICATED SEO SOLUTIONS section -->


<div class="container-fluid dedicatedseosolutions-sec">
		<div class="container">
		    <h2> DEDICATED SEO PLANS </h2>
			<span class="bottomLineImgStyle"></span>
		    
		    <div class="row pt-5">
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="dedicatedseosolutions-innersec">
						<div class="headersec"> DEDICATED SEO PLANS </div>
						<div class="mainsec">$999/month</div>
						<div class="footersec"><button type="button" class="button1"> INQUIRE NOW</button></div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="dedicatedseosolutions-innersec">
						<div class="headersec"> FULL TIME SEO CONSULTANTS </div>
						<div class="mainsec"> $1499/month </div>
						<div class="footersec"><button type="button" class="button1"> INQUIRE NOW</button></div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="dedicatedseosolutions-innersec">
						<div class="headersec"> DEDICATED CONTENT DEVELOPER </div>
						<div class="mainsec">$999/month</div>
						<div class="footersec"><button type="button" class="button1">INQUIRE NOW</button></div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="dedicatedseosolutions-innersec">
						<div class="headersec"> WEB DEVELOPING TEAM </div>
						<div class="mainsec">$1599/month</div>
						<div class="footersec"><a href="https://www.seoeaze.in/request_consultation"><button type="button" class="button1">INQUIRE NOW</button></a></div>
					</div>
				</div>
								


			</div>
		


				
		</div>
	</div>


<!-- End DEDICATED SEO SOLUTIONS section -->

<!-- 30 days money back guarantee sec -->

<div class="container-fluid moneyback-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 ">
					<figure class="pt-3"><img src="assets/img/seopackages/30daystampimg.png"> </figure>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 p-5">
					<h3 class="pt-5"> 30 DAY MONEY BACK OFFER </h3>
					<p>
						At SEOEaze, we offer risk free, 30 days money back guarantee to all our clients. So if you are not happy with the results, we will return your money! 
					</p>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure><img src="assets/img/seopackages/30daysthumsupimg.png"> </figure>
				</div>
			</div>
		</div>
	</div>


<!-- End 30 days money back guarantee sec  -->

<!-- Start OUR PPC MANAGEMENT APPROACH section -->


<div class="container-fluid dedicatedseosolutions-secondsec">
		<div class="container">
						
					<div class="row devider2 mt-5">
			
						<div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
							<div class="box-sec">
																	
								<h3>OUR ENTERPRISE SEO APPROACH </h3>
									<p>
									Enterprise SEO is the field of digital marketing which requires high level techniques to boost sales and to cut out the tough competition from other businesses. Corporate SEO services we offer are fool proof, ensuring that you get high end solutions for your enterprise level company. <br><br>
                                    ur enterprise SEO plans are special for a reason- because an enterprise level website comes with a lot of pages and coding. Running an SEO campaign like that using low quality insignificant SEO techniques will give you more hassle. And even on the enterprise level, you need to be sure of quality over quantity. <br><br>
                                    At SEOEaze, we work with your team to identify the right techniques for your enterprise level website and work tirelessly to improve its visibility and rankings.  Our experts analyze search trends and data for you to provide actionable insights when needed. With our highly focused enterprise SEO services, we assist your enterprise to be on the top. 

									</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
							<div class="box-sec">
								 <img src="assets/img/enterpriseseo/ourapproachimg1.jpg" alt="OUR APPROACH"> 
							</div>
						</div>
						<hr>
					</div>
																
																
					<div class="row pt-5 devider2">
			
						<div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
							<div class="box-sec">
								<h3>HOW SEOEAZE HELPS YOU STAY AHEAD IN THE SEARCH WORLD? </h3>
									<p>
										At SEOEaze, we drive long term and organic results for our clients. Enterprise SEO is basically an investment with high ROI. It gets targeted traffic, attracts quality leads and improves visibility. Our SEO experts know the right way to do enterprise level SEO to create awareness, engagement and long term success. <br><br>
                                        So if despite being a big company, you are outranked by small or midsized businesses, it is now time that you get ready and hire us for top class enterprise SEO solutions. We are sure of getting you the deserved position in organic search results. Further, you will be glad to know that we have helped enterprise organizations dominate your particular niche in the digital world. 

									</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
							<div class="box-sec">
								<img src="assets/img/enterpriseseo/ourapproachimg2.jpg" alt="HIRE US FOR BETTER WEBSITE PERFORMANCE">
							</div>
						</div>
						<hr>
					</div>
																
										
																

			</div>
		</div>



<!-- End OUR PPC MANAGEMENT APPROACH section -->















<!-- Start FEATURES & BENEFITS OF OUR SEO PACKAGES sec-->


<div class="container-fluid blogMgtfeaturesandbenefits-sec">
		<div class="container">
			<h2> WHY HIRE OUR ENTERPRISE SEO?  </h2>
			<h3>FEATURES & BENEFITS </h3>
			<span class="bottomLineImgStyle"></span>
			
			
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/enterpriseseo/icons/enterprise_seo_icon1.png" alt="" class="img-s"> 
						  <h3 class="h3class"> Detailed Monthly Reports </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> We provide interactive and detailed reports to our clients. Every month, we summarize what changes we have made to your site, review the campaign KPI and generate future strategies.<br><br><br> </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/enterpriseseo/icons/enterprise_seo_icon2.png" alt="" class="img-s"> 
						  <h3 class="h3class"> Technical Capabilities </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> We are a technically focused enterprise SEO solution provider. A lot of SEO companies have ideas that fail when it’s time for execution. But our SEO team has the experts who have all technical knowledge to execute strategies to full potential, without changing your existing design. </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/enterpriseseo/icons/enterprise_seo_icon3.png" alt="" class="img-s"> 
						  <h3 class="h3class"> Content Development  </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p>It has been seen that quality, focused and SEO friendly content is the backbone of your enterprise level SEO success. At SEOEaze, we have content developers who do comprehensive content research and create the perfect content for your website. <br></p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/enterpriseseo/icons/enterprise_seo_icon4.png" alt="" class="img-s"> 
						  <h3 class="h3class"> More ROI </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p>With our enterprise level strategies, from site audits and competitor analysis to content marketing and more, we leverage your budget for maximum ROI. Our team also ensures that your site remains abreast of latest technology and so we create foolproof enterprise SEO strategies that will surely deliver high returns. </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/enterpriseseo/icons/enterprise_seo_icon5.png" alt="" class="img-s"> 
						  <h3 class="h3class"> Proven Enterprise SEO Tactics </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p>We track the latest SEO updates and trends so that your site doesn’t have to miss out on anything. We have worked with so many enterprise-level organizations. We further have a proven track record of success and our experts know what will work and what will not.<br><br> </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/enterpriseseo/icons/enterprise_seo_icon6.png" alt="" class="img-s"> 
						  <h3 class="h3class">In House Experts </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p>With a team of SEO specialists and experts, we are proud of having the professionals who work tirelessly to make your business outshine in the digital space. <br><br><br><br></p>
					</div>
				</div>

			</div>

				
		</div>
	</div>


<!-- End FEATURES & BENEFITS OF OUR SEO PACKAGES sec -->


<!-- Start FAQs -->

<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			<h2>FAQS</h2>
			<span class="bottomLineImgStyle"></span>
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> 1. What kind of tools do you use for enterprise SEO? </a>
									</div>
									<div id="collapseOne" class="card-body collapse" data-parent="#accordion">
										<p>We use the most popular SEO tools for keyword research, analysis, link building and more. Other tools that we use are VWO, Google Analyics, Google Search Console etc. </p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> 2. Why should I invest in your company for corporate SEO services? </a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<p>SEOEaze has been rated as the best SEO Company India. We have worked very hard to be on the top position and to sustain the competition. We invest a lot of time and efforts to keep abreast with the latest search engine industry and we offer the best SEO strategies for your enterprise level business. </p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> 3. Why do I need enterprise SEO? </a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">Marketers require enterprise SEO to handle the complexities of big organizations. Enterprise SEO looks at the larger picture. Also the volume of content needed and precision required for successful SEO is immense- and this is impossible to achieve without experienced and specialized team. </div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFourth">
										<a class="card-title"> 4. What makes enterprise SEO different from other types of SEO?</a>
									</div>
									<div id="collapseFourth" class="collapse" data-parent="#accordion">
										<div class="card-body">The needs of an enterprise are more than smaller organizations. The budget is also bigger. Enterprise SEO is different in a way that it has to manage a lot of things like conversions, traffic, online reputation, visibility etc. Services from SEOEaze will balance all these concerns for you and offer you amazing SEO results. </div>
									</div>
									
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
</div>




<!-- End FAQS -->





<!-- Start Call/WhatsApp Us -->
<div class="container-fluid callus-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure class="callusleftsec"><img src="assets/img/linkbulding/callus-iconimg.png"> </figure>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
					<p class="callusmiddlesec">
						CONFUSED ABOUT WHICH PLAN TO CHOOSE?<br>
						CALL/WHATSAPP ON <span> 8375011200 </span> <br> 
						& WE WILL BE MORE THAN HAPPY TO HELP YOU 
					</p>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure class="callusrightsec"><img src="assets/img/linkbulding/callus-girlimg.png"> </figure>
				</div>
			</div>
		</div>
	</div>

<!-- End Call/WhatsApp Us -->


<!-- Start customers think about us Section -->


	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>WHAT OUR CLIENTS SAY ABOUT US  </h2>
			<h3>IT IS OUR VALUED CUSTOMERS WHO KEEP US GOING </h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														<a href="http://b4uindia.com">www.b4uindia.com</a>
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
																				<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														<a href="http://b4uindia.com">www.b4uindia.com</a>
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		
		</div>
	</div>


<!-- End customers thinka bout us Section  -->



<!-- Start bannerFirst Section -->


	<div class="container-fluid ourpriandachiv-sec">
		<div class="container">
			<h2> OVER 25000+ COMPANIES TRUST US  </h2>
			<span class="bottomLineImgStyle"></span>
		
			<div class="row text-center carsec-clients">
			
                           
                        <div class="parent-box8 topSlider8 owl-carousel owl-loaded owl-drag">

								
							<div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-3528px, 0px, 0px); transition: all 0.25s ease 0s; width: 9880px;"><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div></div></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button></div></div>

					</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->



<!-- Start SOME HAPPY CLIENTS  Section --> 
<div class="container-fluid featureandclient-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="featureandclient-innersec">
							<h3 class="whitecolor"> OUR ACHIEVEMENTS: OUR PRIDE </h3>
						    <span class="bottomLineImgStyle"></span>
						   
								<ul>
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon1.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon2.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon3.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon4.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon5.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon6.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon7.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon8.png"></a></li>
									
								</ul>	
							
					</div>
				</div>
			</div>
	</div>
</div>



<!-- End SOME HAPPY CLIENTS  Section --> 

@endsection