<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfba9944195fe513e6792829a66ec8f78
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'AddCountToCardsTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_27_170753_add_count_to_cards_table.php',
        'AddGroupNameToServicesTable' => __DIR__ . '/../..' . '/database/migrations/2016_11_09_210522_add_group_name_to_services_table.php',
        'AddHeaderCodesToServicesTable' => __DIR__ . '/../..' . '/database/migrations/2020_06_07_114556_add_header_codes_to_services_table.php',
        'AddPlanNameToPlansTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_27_151704_add_plan_name_to_plans_table.php',
        'AddProductIdCardsTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_27_172510_add_product_id_cards_table.php',
        'AddRoleIdToUsersTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_25_135154_add_role_id_to_users_table.php',
        'AddServiceLinkToServicesTable' => __DIR__ . '/../..' . '/database/migrations/2016_11_09_205117_add_service_link_to_services_table.php',
        'AddUsernameToUsersTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_29_121236_add_username_to_users_table.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'CreateAllPlansTable' => __DIR__ . '/../..' . '/database/migrations/2016_11_12_230910_create_all_plans_table.php',
        'CreateCardsTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_27_164315_create_cards_table.php',
        'CreateCouponsTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_31_191451_create_coupons_table.php',
        'CreateGroupsTable' => __DIR__ . '/../..' . '/database/migrations/2016_11_09_211155_create_groups_table.php',
        'CreatePasswordResetsTable' => __DIR__ . '/../..' . '/database/migrations/2014_10_12_100000_create_password_resets_table.php',
        'CreatePaypalDatasTable' => __DIR__ . '/../..' . '/database/migrations/2016_11_05_200809_create_paypal_datas_table.php',
        'CreatePlansTable' => __DIR__ . '/../..' . '/database/migrations/2016_10_27_145100_create_plans_table.php',
        'CreateServicesTable' => __DIR__ . '/../..' . '/database/migrations/2016_11_09_204345_create_services_table.php',
        'CreateUsersTable' => __DIR__ . '/../..' . '/database/migrations/2014_10_12_000000_create_users_table.php',
        'DatabaseSeeder' => __DIR__ . '/../..' . '/database/seeds/DatabaseSeeder.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfba9944195fe513e6792829a66ec8f78::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfba9944195fe513e6792829a66ec8f78::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitfba9944195fe513e6792829a66ec8f78::$classMap;

        }, null, ClassLoader::class);
    }
}
