@extends('layouts.master')
@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.in/content_writing_service" hreflang="en-in" />
    <link rel="alternate" href="https://www.seoeaze.com/content_writing_service" hreflang="en-us" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/content_writing_service" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/content_writing_service" hreflang="x-default" />
@endsection

@section('title', 'Content Writing Services -Hire Article Writer | Buy Articles ')
@section('meta' , "SeoEaze offering all Web Content Writing Services, You can buy article writing service, Blog posts writing, Press Releases, eBooks, Product Reviews & more..")
<!-- Start Breadcrumbs Schema -->
	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			 "itemListElement": [{
			   "@type": "ListItem",
			   "position": 1,
			   "name": "Home",
			   "item": "https://www.seoeaze.in/"
			 },
			{
			   "@type": "ListItem",
			   "position": 2,
			   "name": "Content Writing Service",
			   "item": "https://www.seoeaze.in/content_writing_service"
			 }]
		}
	</script>
	
	<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Who will write my content? ","acceptedAnswer":[{"@type":"Answer","text":"Professional writers create content at SEOEaze. Our experienced writers and editors have complete knowledge and skills about how to write an article and other types of content. "}]},{"@type":"Question","name":"What type of content can you write? ","acceptedAnswer":[{"@type":"Answer","text":"We can write any type of content including web content, articles, press release, product reviews, product descriptions, news, blog posts, technical writing, user manuals, academic content, ebooks and any other type of content as per your requirements."}]},{"@type":"Question","name":"Are the articles keyword-rich?","acceptedAnswer":[{"@type":"Answer","text":"Yes. The articles or say any type of content we write is SEO optimized and keyword rich. This makes our content SEO friendly and easy to read. "}]},{"@type":"Question","name":"How can I check the quality? ","acceptedAnswer":[{"@type":"Answer","text":"You can ask to check your content in between the project to see the quality and give more instructions if required. "}]}]}</script><!-- Generated by https://www.seoeaze.in/ -->

@section('header')


@show

@section('content')

<!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-7 col-md-7 col-sm-12 header-video-sec-inner-leftsec">

				  				<h1> QUALITY CONTENT WRITING SERVICES  </h1>
									<h2> USER  ENGAGING, SEO OPTIMIZED CONTENT AT YOUR DISPOSAL  </h2>
										
										
									<div class="header-bulletsec">
										<div class="header-bulletsec-colleft">
											<ul>
												<li> Original and SEO friendly Content</li>
												<li> Plagiarism Free Content </li>
												<li> Short Rurnaround Time </li>
											</ul>
										</div>
										<div class="header-bulletsec-right">
											<ul>
												
												<li> Free Revisions and Editing </li>
												<li> Content that Convers Well </li>
												<li> Experienced and Well Trained Writers,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Copywriters, Editors </li>
											</ul>
										</div>
									</div>
										
										
									<span>  
										<a href="#pricing">
											<button class="button1"> Get Started </button>
										</a> 
									    <a href="#samples">
											<button class="button2"> Writing Samples </button>
										</a>
										<a  href="#benefits">
											<button class="button1"> Key Benefits </button>
										</a> 
									</span><br><br><br>
				  			</div>

				  			<div class="col-lg-5 col-md-5 col-sm-12 header-video-sec-inner-rightsec">
								<div class="imgblockright">	  				
									<img src="assets/img/content-writing-services/header-rightside-img.png" alt="">
								</div>
				  			</div>
					</div>
			  	</div>
				
			
			</div>
			<!-- Vedio Content Section End -->
							

	</main>
			  
<!-- slider area bar end-->

<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Content Writing Service </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->

<!-- Start Key services sec -->

	<div class="container-fluid" style="border-bottom: 5px solid #eaeaea;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
				    
						    <div class="parent-box8 topSlider8 owl-carousel">

                                <div class="box8 mx-auto d-block">
									<div class="tophoriscrollsec-box text-center">
										<a href="#tab2" id="ui-id-#tab2">
										 <img src="./assets/img/content-writing-services/icons/blog-icon.png">
										 <h2>Blog Posts </h2>
										 </a>
									 </div>
                                </div>
								<div class="box8 mx-auto d-block">
                                     <div class="tophoriscrollsec-box text-center">
										<a href="#tab3" id="ui-id-3">
										 <img src="./assets/img/content-writing-services/icons/web-content.png">
										 <h2> Web Content </h2>
										</a>
									 </div>
                                </div>
                                <div class="box8 mx-auto d-block">
                                     <div class="tophoriscrollsec-box text-center">
                                         <a href="#tab4" id="ui-id-4">
										 <img src="./assets/img/content-writing-services/icons/product-review.png">
										 <h2>Product Reviews </h2>
										 </a>
									 </div>
                                </div>
								<div class="box8 mx-auto d-block">
                                     <div class="tophoriscrollsec-box text-center">
                                         <a href="#tab5" id="ui-id-5">
										 <img src="./assets/img/content-writing-services/icons/e-books-icon.png">
										 <h2>eBooks</h2>
										 </a>
									 </div>
                                </div>
								<div class="box8 mx-auto d-block  text-center">
                                     <div class="tophoriscrollsec-box">
                                         <a href="#tab6" id="ui-id-6">
										 <img src="./assets/img/content-writing-services/icons/press-release.png">
										 <h2> Press Releases </h2>
										 </a>
									 </div>
                                </div>
                                
							</div>
				</div>
			</div>
		</div>
	</div>


<!-- End Key services sec -->


<!-- Start Content Creation Simple sec -->

	<div class="container-fluid contentcreationsimple-sec">
		<div class="container">
			<h2>TOP CONTENT WRITING COMPANY IN DELHI/NCR</h2>
			<h3>Professional content writing services to meet your needs.</h3>
			<span class="bottomLineImgStyle"></span>
			<div class="row">
    			<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block"> 
        			<figure>
        				<img src="assets/img/content-writing-services/content-creation-sample.jpg">
        			</figure>
    			</div>
    			<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block"> 
    			<p><br>
    			    
Whether you need copywriting, web content, articles, blog posts or e- book content, our team of professional content writers offer you high quality content for all your needs. With SEOEaze content writing services, you can be sure of getting SEO optimized, original, unique, keyword rich and high quality content only.

    			</p>
    			</div>
			</div
			
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					
						<!------ Include the above in your HEAD tag ---------->

							<section id="tabs" class="project-tab">
										<div class="container" style="background: white;">
											<div class="row">
												<div class="col-md-12">
													<nav>
														<div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
															<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">SEO Content Services </a>
															<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Enterprise Content Services</a>
															
														</div>
													</nav>
													<div class="tab-content" id="nav-tabContent">
														<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">

																<div class="row pt-5">
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-1.png"></figure>
																			<h3>High quality </h3>
																			<p>
																				We offer high quality, keyword rich SEO content for your site/blog etc. Use our content to convert. 
																			</p>
																		</div>
																	</div>
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-2.png"></figure>
																			<h3>SEO Optimized </h3>
																			<p>
																				We ensure that the content we deliver is SEO optimized to get you on top. Our professionals take extra efforts to deliver the BEST. 
																			</p>
																		</div>
																	</div>
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-3.png"></figure>
																			<h3>Original and targeted </h3>
																			<p>
																				At SEOEaze, you can be sure of getting original content writing services at affordable rates. Our writers create fresh, targeted content for your needs. 
																			</p>
																		</div>
																	</div>
																</div>
																<div class="row mx-auto d-block mb-5 mt-2">
																	<a href="/how_it_works"><button type="button" class="btn btn-danger but-style"> SEE HOW IT WORKS </button></a>
																</div>

														</div>
														<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
															
																<div class="row pt-5">
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-4.png"></figure>
																			<h3>Complex projects  </h3>
																			<p>
																				Our professionals add their expertise to your complex projects, delivering high quality content writing. They can handle any sort of complicated content with ease. 
																			</p>
																		</div>
																	</div>
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-5.png"></figure>
																			<h3>Fully managed  </h3>
																			<p>Our writing team are well aware of how to tackle your content programs. When you choose our enterprise content services, you get industry veterans writing your content. </p>
																		</div>
																	</div>
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-6.png"></figure>
																			<h3>Fast turnaround</h3>
																			<p>
																				We deliver most orders within 24-48 hours. Our team takes turnaround time very seriously and deliver fast yet professional results. 
																			</p>
																		</div>
																	</div>
																</div>
																<div class="row mx-auto d-block mb-5 mt-2">
																	<a href="/explore_enterprise_services"><button type="button" class="btn btn-danger but-style"> Explore Enterprise Services </button></a>
																</div>
															
														</div>

													</div>
												</div>
											</div>
										</div>
									</section>
					
					
					
				</div>
			</div>
		</div>
</div>


<!-- End Content Creation Simple sec -->





<!-- Start bannerFirst Section -->



	<div class="container-fluid bannerFirst-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 30+ </h2>
					<p> Professional Writers </p>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 4500+ </h2>
					<p> Businesses Served </p>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 90M+</h2>
					<p> Words Written  </p>
				</div>
			</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->

<!-- Start customers think about us Section -->


	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>WHAT OUR CLIENTS SAY ABOUT US  </h2>
			<h3>IT IS OUR VALUED CUSTOMERS WHO KEEP US GOING </h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. 
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
																				<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		
		</div>
	</div>


<!-- End customers thinka bout us Section  -->

<!-- Start Find Your Perfect Writer Today Section -->
		<div class="container-fluid perfectwritertoday-sec">
			<div class="container">
				<h2>GET THE BEST CONTENT TODAY </h2>
				<span class="bottomLineImgStyle"></span>
				<a href="#pricing"><button type="button" class="btn btn-danger but-style"> Start Now </button></a>
			</div>
		</div>
<!-- End Find Your Perfect Writer Today Section -->

<!-- Pricing Table Start -->
<div class="container-fluid pt-5 pb-5">
    
    <section class=" b-benefits-container f-benefits-container" style="padding:0;">
        <div class="container">
            <div class="col-sm-12"><h1 id="pricing" class="se_title_serv f-primary-b text-center pr_pl_scroll pt-5">Plans & Pricing</h1>
                <center style="height: 50px;"><span class="bottomLineImgStyle"></span></center>
                <div class="b-shortcode-example">
                    <div class="b-tabs f-tabs j-tabs b-tabs-reset b-tabs--secondary f-tabs--secondary ui-tabs ui-widget ui-widget-content ui-corner-all">
                        <div class="row" style="overflow: hidden">
                            <div class="container-fluid"><br>
                                <div class="panel-body">
                                    <div>
                                        <ul class="seo_navi nav-tabs">
                                            <div style="display: none;">                                                {{ $count = 0 }}                                            </div> @if($plan_name['0'] != '')                                                @foreach($plan_name as $plan)
                                                <div style="display: none;">                                                        {{ $count ++ }}                                                    </div>
                                                <li id="plans" class="for_tabs_un_line_li seo_service_accord_menu">
                                                    <span style="background-color: #42af9a; " class="for_tabs_un_line"></span>
                                                    <a data-toggle="tab" style="font-size: 18px;" href="#tab{{$count}}">
                                                        {{ $plan['plan_name'] }}
                                                    </a>
                                                </li>                                                @endforeach                                            @endif
                                        </ul>
                                        <div class="tab-content" style="background: #eaeaea; overflow: hidden; padding: 50px;">                                            @if($plan_name['0'] != '')                                                @include('parts.pricing_table')                                            @endif                                        </div>
                                    </div>
                                </div>
                                <div class="A4KZv8 visible_hide_class" data-reactid="2">
                                    <div class="AFyd3c" data-reactid="3">
                                        <div class="_1EA4La" data-reactid="4">
                                            <div class="_1-baVo" data-reactid="5">
                                                <img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0nMjAnIGhlaWdodD0nMjAnIHZpZXdCb3g9JzAgMCAyMCAyMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz4KCTxnPgoJCTxwYXRoIGQ9J00tMi0yaDI0djI0SC0yeicgZmlsbD0nbm9uZScvPgoJCTxwYXRoIGQ9J00xMCAwQzQuNDggMCAwIDQuNDggMCAxMHM0LjQ4IDEwIDEwIDEwIDEwLTQuNDggMTAtMTBTMTUuNTIgMCAxMCAwek04IDE1bC01LTUgMS40MS0xLjQxTDggMTIuMTdsNy41OS03LjU5TDE3IDZsLTkgOXonIGZpbGw9JyMyNkJDNEUnLz4KCTwvZz4KPC9zdmc+Cg==" class="_2P4x_N" data-reactid="6">
                                            </div>
                                            <div class="JAUzCh" data-reactid="7">Product Added to Cart Successfully.
                                            </div>
                                            <a href="/cart" class="checkout_link">
                                                <button name="checkout" type="submit" class="cta-full-width pull-right" id="checkout-link" style="width: 100%;margin-right: 10px; font-size: 1.6rem;margin-top: 10px;">
                                                    Go to cart
                                                </button>
                                            </a></div>
                                    </div>
                                </div>
                                <br></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
  </div>  
    
    
    
    
    
<script type="text/javascript" language="javascript"
        src="https://maps.google.com/maps/api/js?sensor=false&key=AIzaSyCfVS1-Dv9bQNOIXsQhTSvj7jaDX7Oocvs"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.13/d3.min.js"></script>
<!-- end Progress -->

<!-- Cart Functionality services -->
<script type="text/javascript"
        src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}"></script>
<script src="/assets/js/main.min.js"></script>
<!-- Pricing Table End -->
<!-- Start OUR WRITING SAMPLES Section -->
	<div class="container-fluid ourwritingsamples-sec" id="samples">
		<div class="container">
			<h2>OUR WRITING SAMPLES </h2>
			<span class="bottomLineImgStyle"></span>
			
			
			<div class="row">
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon1.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Blogs  Writing Samples</p>
						  <a href="https://www.seoeaze.in/assets/cws_files/blog_posts.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon2.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Web Content Samples</p>
						  <a href="https://www.seoeaze.in/assets/cws_files/web_content.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon3.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Product Review Samples</p>
						  <a href="https://www.seoeaze.in/assets/cws_files/product_reviews.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon4.png" alt="Cinque Terre" > 
						  <h3>Download</h3>
						  <p>Ebooks Samples</p>
						  <a href="https://www.seoeaze.in/assets/cws_files/e_book.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon5.png" alt="Cinque Terre" > 
						  <h3>Download</h3>
						  <p>Press Release Samples</p>
						  <a href="https://www.seoeaze.in/assets/cws_files/press_eleases.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
			</div>
			
			

		</div>
	</div>
			
<!-- End OUR WRITING SAMPLES Section -->



<!-- Start card Section -->
	<div class="container-fluid card-sec">
		<div class="container">
	
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">Be #1 on Google</h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/Be1onGoogle-img.jpg" alt="Card image cap">
								<p class="card-text">With our top content writing services, you can be sure of getting the top positions on popular search engines like Google. Our content writers create high quality, keyword rich, SEO friendly and optimized content that gets noticed. Use our content writing to create rich website that Google will love. </p>
								
						  </div>
						</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">GET MORE TRAFFIC </h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/igniteyourcommunity-img.jpg" alt="Card image cap">
								<p class="card-text">With high quality content that is targeted and optimized, you definitely get more traffic and visitors. This makes your site/blog more popular and you start earning more
						  </div>
						</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">Convert More </h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/achieve-content-marketing-success-img.jpg" alt="Card image cap">
								<p class="card-text"> With our engaging content and high traffic, you will definitely convert more and fast. Not just this, you can also achieve successful content marketing with our amazing content. </p>
								
						  </div>
						</div>
				</div>
				
			</div>


		</div>
	</div>
<!-- End card Section -->



<!-- Start FEATURES AND BENEFITS Section -->


	<div class="container-fluid featuresandbenefits-sec" id="benefits">
		<div class="container">
			<h2> FEATURES AND BENEFITS </h2>
			<span class="bottomLineImgStyle"></span>
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/expert-writing-icon.png" alt="Cinque Terre"> 
						  <h3> EXPERT WRITING </h3>
						  <p> Professional writers with many years of experience handle all types of content as per your requirements. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/revisionandediting-icon.png" alt="Cinque Terre"> 
						  <h3> REVISIONS AND EDITING </h3>
						  <p> Unlimited revisions are provided and content is submitted after editing from trained editors. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/originalcontent-icon.png" alt="Cinque Terre"> 
						  <h3> ORIGINAL CONTENT </h3>
						  <p> 100% original and SEO friendly content is what we offer. You can be sure of originality and high quality.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/keywordoptimazation-icon.png" alt="Cinque Terre"> 
						  <h3> KEYWORD OPTIMIZED </h3>
						  <p> Our content is keyword rich and optimized to make it SEO friendly. </p>
					</div>
				</div>
			</div>
			
				
		</div>
	</div>

<!-- END FEATURES AND BENEFITS Section -->



<!-- Start Get Custom Quote Section -->


	<div class="container-fluid getcustomquote-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
					<h3> NOT SURE HOW MUCH TO PAY? </h3>
					<p> CONFUSED ABOUT THE WORD COUNT?  </p>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
					<a href="" data-toggle="modal" data-target="#myModal"><img src="assets/img/ourwritingsamples-sec/getcustomquote-bannerimg.png"></a>
				</div>
			</div>
		</div>
	</div>

<!-- End Get Custom Quote Section -->




<!-- Start FAQS RELATED TO CONTENT WRITING SERVICE Section -->
<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			<h2>FAQS RELATED TO CONTENT WRITING SERVICE </h2>
			<span class="bottomLineImgStyle"></span>
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> 1. Who will write my content?  </a>
									</div>
									<div id="collapseOne" class="card-body collapse" data-parent="#accordion">
										<p>Professional writers create content at SEOEaze. Our experienced writers and editors have complete knowledge and skills about how to write an article and other types of content.  </p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> 2.What type of content can you write?  </a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<p>We can write any type of content including web content, articles, press release, product reviews, product descriptions, news, blog posts, technical writing, user manuals, academic content, ebooks and any other type of content as per your requirements. </p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> 3. Are the articles keyword-rich? </a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">Yes. The articles or say any type of content we write is SEO optimized and keyword rich. This makes our content SEO friendly and easy to read.  </div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFourth">
										<a class="card-title"> 4. How can I check the quality?  </a>
									</div>
									<div id="collapseFourth" class="collapse" data-parent="#accordion">
										<div class="card-body">You can ask to check your content in between the project to see the quality and give more instructions if required.  </div>
									</div>
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
</div>
<!-- End FAQS RELATED TO CONTENT WRITING SERVICE Section -->


<!-- START  Hire the Perfect Content Writer SECTION -->

<div class="container-fluid hirethepercerctcontentwriter-sec">
		<div class="container">
			
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="hirethepercerctcontentwriter-innersec">
						<h2>Hire the <span> Perfect Content Writer </span> for Your Website </h2>
						
						
								<section class="py-4">
									<div class="row">
										<div class="col-md-12">
											<div class="d-flex">
												<ul id="tabsJustified" class="nav nav-pills flex-column">
													<li class="nav-item"><a href="" data-target="#home1" data-toggle="tab" class="nav-link text-uppercase active mb-1">Hire The Best </a></li>
													<li class="nav-item"><a href="" data-target="#profile1" data-toggle="tab" class="nav-link text-uppercase mb-1">Skilled professionals  </a></li>
													<li class="nav-item"><a href="" data-target="#messages1" data-toggle="tab" class="nav-link text-uppercase mb-1">Writers for all </a></li>
												</ul>
												<div class="tab-content pt-1 pl-5 w-100 text-left">
													<div id="home1" class="tab-pane fade active show">
														We have a team of the best writers for you. This ensures that you get top quality content writing services only. 
													</div>
													<div id="profile1" class="tab-pane fade">
														We rate our writers every now and then to check their abilities and creativity. This makes certain that our professionals are highly skilled and experienced. 
													</div>
													<div id="messages1" class="tab-pane fade">
														Our team of writers are from across the globe, offering you the opportunity to get best content writing solutions. 
													</div>
												</div>
											</div>
										</div>
									</div>
								</section>
						
						
						
						
						

					</div>
				</div>
			</div>
		</div>
</div>








<!-- End  Hire the Perfect Content Writer SECTION -->




@endsection