@extends('layouts.master')
@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.in/local_seo_service" hreflang="en-in" />
    <link rel="alternate" href="https://www.seoeaze.com/local_seo_service" hreflang="en-us" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/local_seo_service" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/local_seo_service" hreflang="x-default" />
@endsection




@section('title', 'Local SEO Service -Local Business Listing & SEO Solution by SeoEaze')

@section('meta' , "Every Local Business has different SEO needs, with SeoEaze's Local SEO Service, we insure your local business listing & provide Special Local SEO Solution.")
<!-- Start Breadcrumbs Schema -->
	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			 "itemListElement": [{
			   "@type": "ListItem",
			   "position": 1,
			   "name": "Home",
			   "item": "https://www.seoeaze.in/"
			 },
			{
			   "@type": "ListItem",
			   "position": 2,
			   "name": "Local SEO Service",
			   "item": "https://www.seoeaze.in/local_seo_service"
			 }]
		}
	</script>

	<!-- End Breadcrumbs Schema -->
	
<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What is local SEO and why should we go for it?","acceptedAnswer":[{"@type":"Answer","text":"Local SEO is an effective way to market your business to people closest to you online. Local SEO helps businesses promote their products and services to local prospects and audience. So if your locals are your main audience or potential customers, you should invest in local SEO for sure."}]},{"@type":"Question","name":"What is Google Local listing? ","acceptedAnswer":[{"@type":"Answer","text":"Google local listings are the business listings that show up on the map on the first page of a Google search result. You can do this by managing your Google My Business page. To optimise your Google My Business listing - set up your page with a relevant category and populate it with great images, your phone number and local information. Encouraging reviews and optimising your own web site for local SEO will help optimise your listings."}]},{"@type":"Question","name":"Who should take local SEO packages? ","acceptedAnswer":[{"@type":"Answer","text":"Any business that operates locally and when their target audience is local residing in that area, they should do it. Local listing is one of the main tricks used to promote your brand in local search results. "}]},{"@type":"Question","name":"What is the cost of your local SEO packages? ","acceptedAnswer":[{"@type":"Answer","text":"Our proposal for any Local SEO campaign depends on our effort estimates which are calculated based on your location, number and quality of keywords we are targeting, the age of your website and competitiveness of the major industry players for those local keywords. However, the basic plan of our Local SEO starts from INR 9000."}]},{"@type":"Question","name":"As a dentist, how can I optimize my business locally in search engines? ","acceptedAnswer":[{"@type":"Answer","text":"Local SEO is all about helping a company to be seen locally. An effective strategy will work effectively to bring you the desired results. All you have to do is to hire us and let us work for your local SEO results. "}]}]}</script><!-- Generated by https://www.seoeaze.in/ -->

@section('header')



@show



@section('content')

    <!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-6 col-md-6 col-sm-12 header-video-sec-inner-leftsec">

									<h1> LOCAL SEO SERVICE</h1>
									
									<ul>
										<li> Increase local rankings</li>
										<li> Improve local online presence</li>
										<li> More clients, more business </li>
										<li> More targeted geographic campaigns  </li>
									</ul>
										
									<span class="mt-5">  
										<a href="#whylocal">
											<button class="button1"> Why Local SEO?  </button>
										</a> 
										<a href="/request_consultation">
											<button class="button2">  Request Consultation</button>
										</a>
									</span>
									
									
				  			</div>

				  			<div class="col-lg-6 col-md-6 col-sm-12 header-video-sec-inner-rightsec">
								<div class="imgblockright">	  				
									<img src="assets/img/localseoservices/localseoservices_headerimg.png" alt="">
								</div>
				  			</div>
					</div>
			  	</div>
				
			
			</div>
			<!-- Vedio Content Section End -->
							

	</main>
			  
<!-- slider area bar end-->

<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Local SEO Service </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->

<!-- LOCAL SEO FOR REGION SPECIFIC NEEDS-->
<div class="container-fluid localseopackage-sec">
		<div class="container">
			<h2> WHAT IS LOCAL SEO? </h2>
			<span class="bottomLineImgStyle"></span>
			<p> Local SEO is the process to make your business visible for geographically related searches or map listings. It helps your business to increase its online visibility, outrank the local competitors and increase organic traffic. Every Business Has different Needs, If you are opearating in a city & providing Local Services, Local SEO is your thing, If you are a dentist, You don't want to Rank in Boston when you are providing services in Delhi, Mumbai or Bangaluru. So You will need Local SEO for that.</p>
			
		</div>
	</div>
<div class="container-fluid localseopackage-sec"id="whylocal">
		<div class="container">
			<h2> LOCAL SEO COMPANY INDIA FOR YOUR LOCAL NEEDS  </h2>
			<span class="bottomLineImgStyle"></span>
			<p> Offering quality local SEO services India, SEOEaze emphasis on local search engine optimization, thus optimizing your site for a specific region, city or location. Our local SEO strategy helps increase your search engine rankings for your products and services. Search engines such as Google have realized that users are looking for specific products and services near them. In fact, over half of total search queries have local intent. With better local search rankings, you will get more visitors and leads for your business. </p>
			
		</div>
	</div>
<!--LOCAL SEO FOR REGION SPECIFIC NEEDS -->

<!-- Start section -->
<div class="container-fluid localseopackage-sec2">
		<div class="container">
							
					<div class="row mt-5">
						<div class="col-lg-8 col-md-8 col-sm-12 offset-lg-2 offset-md-2 devider2 mx-auto d-block">
						<h2> How We Work?  </h2>
							
								 <figure><img src="assets/img/localseoservices/localauditimg.png" alt="OUR APPROACH"></figure> 
								 	<h3>LOCAL Market Analysis</h3>
									<p>
										We check your local market and competitors. Your local surroundings are checked to see where you belong to, your local target customers and how you can get better results in local searches. 
									</p>
						</div>
						<hr>
					</div>
					<div class="row mt-5">
						<div class="col-lg-8 col-md-8 col-sm-12 offset-lg-2 offset-md-2 devider2 mx-auto d-block">
							
								 <figure><img src="assets/img/localseoservices/localoptimization-img.png" alt="OUR APPROACH"></figure> 
								 	<h3>LOCAL OPTIMIZATION</h3>
									<p>
										After competitor analysis and local keyword research, we do proper on page and content optimization. Your website is optimized as per local SEO standards so that your local search needs are properly met. This then brings you more business when you have proper directions, schema markup and navigation. 
									</p>
						</div>
						<hr>
					</div>
					<div class="row mt-5">
						<div class="col-lg-8 col-md-8 col-sm-12 offset-lg-2 offset-md-2 devider2 mx-auto d-block">
							
								 <figure><img src="assets/img/localseoservices/locallinkbuilding-img.png" alt="OUR APPROACH"></figure> 
								 	<h3>Strong LOCAL LINKs </h3>
									<p>
										Strong local link building can get you organic rankings. Effective strategies are used for link building and to improve your search engine rankings. 
									</p>
						</div>
						<hr>
					</div>
					<div class="row mt-5">
						<div class="col-lg-8 col-md-8 col-sm-12 offset-lg-2 offset-md-2 devider2 mx-auto d-block">
							
								 <figure><img src="assets/img/localseoservices/onlinereviewmonitoring-img.png" alt="OUR APPROACH"></figure> 
								 	<h3>Local Business Listing</h3>
									<p>
										We list your business on Google maps so that when someone searches for some product or service near them, your company should appear on the top.  
									</p>
						</div>
						<hr>
					</div>

			</div>
		</div>



<!-- End section -->



<!-- Start Not convinced sec -->

<div class="container-fluid notconvinced-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 ">
					<figure>
						<img src="assets/img/localseoservices/not-convinceimg1.png"> 
					</figure>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12">
					<figure>
						<img src="assets/img/localseoservices/not-convinceimg2.png"> 
					</figure>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 middle">
					<a href="https://www.seoeaze.in/request_consultation">
						<button class="button4"> GET A FREE CONSULTATION </button>
					</a>
				</div>
			</div>
		</div>
	</div>


<!-- End Not convinced sec  -->



<!-- Start FEATURES & BENEFITS OF OUR SEO PACKAGES sec-->


<div class="container-fluid blogMgtfeaturesandbenefits-sec">
		<div class="container">
			<h2> WHY CHOOSE SEOEAZE FOR LOCAL SEO STRATEGY? </h2>
			<h3> Local SEO consulting is provided to the clients who ask for the same. </h3>
			<span class="bottomLineImgStyle"></span>
			<p>We help you expand your business in the local market. Our professionals set necessary keywords for the customers searching for local companies like yours. At SEOEaze, we use local SEO strategies to attract customers by positioning and promoting your company. With our local SEO services India, we not just list your website in local directories but also help you to boost your business and gain better visibility. We further extend our services like Google My Business Page Management for your benefit. </p>
<hr>
<h3>HIRE US TODAY TO ENJOY BETTER AND BENEFICIAL LOCAL SEO OF YOUR BUSINESS</h3>
			
		</div>
	</div>


<!-- End FEATURES & BENEFITS OF OUR SEO PACKAGES sec -->


<!-- Start FAQs -->

<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			<h2>FAQS</h2>
			<span class="bottomLineImgStyle"></span>
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> What is local SEO and why should we go for it? </a>
									</div>
									<div id="collapseOne" class="card-body collapse" data-parent="#accordion">
										<p>Local SEO is an effective way to market your business to people closest to you online. Local SEO helps businesses promote their products and services to local prospects and audience. So if your locals are your main audience or potential customers, you should invest in local SEO for sure.</p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> What is Google Local listing?  </a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<p>Google local listings are the business listings that show up on the map on the first page of a Google search result. You can do this by managing your Google My Business page. To optimise your Google My Business listing - set up your page with a relevant category and populate it with great images, your phone number and local information. Encouraging reviews and optimising your own web site for local SEO will help optimise your listings.</p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> Who should take local SEO packages?  </a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">Any business that operates locally and when their target audience is local residing in that area, they should do it. Local listing is one of the main tricks used to promote your brand in local search results.  </div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFourth">
										<a class="card-title">What is the cost of your local SEO packages? </a>
									</div>
									<div id="collapseFourth" class="collapse" data-parent="#accordion">
										<div class="card-body">Our proposal for any Local SEO campaign depends on our effort estimates which are calculated based on your location, number and quality of keywords we are targeting, the age of your website and competitiveness of the major industry players for those local keywords. However, the basic plan of our Local SEO starts from INR 9000 and goes up to INR 20000. </div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFifth">
										<a class="card-title"> As a dentist, how can I optimize my business locally in search engines? </a>
									</div>
									<div id="collapseFifth" class="collapse" data-parent="#accordion">
										<div class="card-body">Local SEO is all about helping a company to be seen locally. An effective strategy will work effectively to bring you the desired results. All you have to do is to hire us and let us work for your local SEO results.  </div>
									</div>
									
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
</div>




<!-- End FAQS -->





<!-- Start Call/WhatsApp Us -->

<div class="container-fluid callus-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure class="callusleftsec"><img src="assets/img/linkbulding/callus-iconimg.png"> </figure>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
					<p class="callusmiddlesec">
						NOT SURE OF WHICH LOCAL SEO PACKAGE TO CHOOSE? <br>
						Call Us At <span> 8375011200</span> To Learn More
					</p>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure class="callusrightsec"><img src="assets/img/linkbulding/callus-girlimg.png"> </figure>
				</div>
			</div>
		</div>
	</div>

<!-- End Call/WhatsApp Us -->



<!-- Start customers think about us Section -->


	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>Words From Our Clients </h2>
			<h3>Our Valued Customers Believe In Us & This Is What Keeps Us Going </h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
																				<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		
		</div>
	</div>


<!-- End customers thinka bout us Section  -->





<!-- Start bannerFirst Section -->


	<div class="container-fluid ourpriandachiv-sec">
		<div class="container">
			<h2> MORE THAN 2500 BUSINESSES TRUSTED US </h2>
			<span class="bottomLineImgStyle"></span>
		
			<div class="row text-center carsec-clients">
			
                           
                        <div class="parent-box8 topSlider8 owl-carousel owl-loaded owl-drag">

								
							<div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-3528px, 0px, 0px); transition: all 0.25s ease 0s; width: 9880px;"><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div></div></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button></div></div>

					</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->



<!-- Start SOME HAPPY CLIENTS  Section --> 
<div class="container-fluid featureandclient-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="featureandclient-innersec">
							<h3 class="whitecolor"> OUR ACHIEVEMENTS: OUR PRIDE </h3>
						    <span class="bottomLineImgStyle"></span>
						   
								<ul>
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon1.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon2.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon3.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon4.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon5.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon6.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon7.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon8.png"></a></li>
									
								</ul>	
							
					</div>
				</div>
			</div>
	</div>
</div>



<!-- End SOME HAPPY CLIENTS  Section --> 
@endsection