@extends('layouts.master')
@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.in/panda_penguin_recovery_service" hreflang="en-in" />
    <link rel="alternate" href="https://www.seoeaze.com/panda_penguin_recovery_service" hreflang="en-us" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/panda_penguin_recovery_service" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/panda_penguin_recovery_service" hreflang="x-default" />
@endsection
@section('title', 'Manual SEO Penalty Recovery- Google Panda Penguin Recovery Service')
@section('meta' , "Is your site penalized for bad links or suffered from google panda-penguin, Check SeoEaze's Panda Penguin Recovery Service & Manual Penalty Recovery Service")
<!-- Start Breadcrumbs Schema -->
	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			 "itemListElement": [{
			   "@type": "ListItem",
			   "position": 1,
			   "name": "Home",
			   "item": "https://www.seoeaze.in/"
			 },
			{
			   "@type": "ListItem",
			   "position": 2,
			   "name": "Panda Penguin Recovery Service",
			   "item": "https://www.seoeaze.in/panda_penguin_recovery_service"
			 }]
		}
	</script>

<!-- End Breadcrumbs Schema -->
<!-- START FAQS SCHEMA -->
    <script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How to check that your site is penalized?","acceptedAnswer":[{"@type":"Answer","text":"There are various ways you can check that like if there is some major ranking drop, decrease in organic traffic or leads, if you get messages in Google WBT for unnatural links warning etc. \n"}]},{"@type":"Question","name":"What caused me Google panda and penguin penalty?","acceptedAnswer":[{"@type":"Answer","text":"The first thing that we will help you identify is whether you have a manual action penalty, or if you have triggered something in Google's algorithm that has caused sudden harm to your keyword rankings. Regardless, penalties given out by Google can be caused by a few different factors.\n"}]},{"@type":"Question","name":"How do you fix Google penalty?","acceptedAnswer":[{"@type":"Answer","text":"When dealing with sites that have been hit by a Google penalty - Penguin, Panda or otherwise, we take a no-nonsense approach to identifying the issues, taking action to fix those issues, and developing a strategy for the future that avoids Google penalties. \n"}]},{"@type":"Question","name":"How much do Google penalty recovery services cost?","acceptedAnswer":[{"@type":"Answer","text":"SEOEaze team estimates the cost of Google penalty removal based on the severity of the case. Depending on the specific issue causing the penalty, our team will assess the size and scope of the project and estimate a price based on our hourly rate. In some instances this can be as low as INR 10,000 while more complex issues can cost significantly more.\n"}]}]}</script><!-- Generated by https://www.seoeaze.in/ -->
<!-- END FAQS SCHEMA -->
@section('header')
@show
@section('content') 

<!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-7 col-md-7 col-sm-12 header-video-sec-inner-leftsec">

									<h1> GOOGLE PENALTY RECOVERY SERVICE  </h1>
									<h2> Have your site dived in search results? Hire us now!  </h2>
									
									<ul>
										<li> Bad links removal  </li>
										<li> Updating poor quality content  </li>
										<li> Analysing traffic fall  </li>
										<li> Baseline rank check  </li>
									</ul>
										
									<span class="mt-5">  
										<a href="#auditmywebsite">
											<button class="button1"> Audit My Website </button>
										</a> 
										<a href="#requsetconsultationpanda">
											<button class="button2"> Request Consultation </button>
										</a>
									</span>
				  			</div>

				  			<div class="col-lg-5 col-md-5 col-sm-12 header-video-sec-inner-rightsec">
				  				<div class="imgblockright">
				  					<img src="assets/img/seopenalty/seopanelty-toprightimg.png" alt="">
				  				</div>
				  			</div>
					</div>
			  	</div>
				
			
			</div>
			<!-- Vedio Content Section End -->
							

	</main>
			  
<!-- slider area bar end-->

<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Panda Penguin Recovery Service </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->

<!-- Start reputationmngtser sec -->

<div class="container-fluid seopanelty-sec">
	<div class="container">
			<h2> GOOGLE PENALTY RECOVERY SERVICES </h2>
			<span class="bottomLineImgStyle"></span>
			<img src="assets/img/seopenalty/googlepanelty-img.png" alt="">
			
			<p class="pb-2">
			Hire our Google Penalty recovery service and get a clean chit. With Google changing its algorithm every now and then, a lot of sites have seen a drop in their rankings. Google Panda and penguin updates have impacted the rankings of so many high ranking sites. This year alone, we have helped 150+ sites recover from Google penalties. 

                <br>
			</p>
			<p class="pb-2">
				Our team of professionals are experienced in recovering sites from all sorts of penalties. We offer you well researched solution, great service execution at affordable cost. Further, we provide you fast Google penalty recovery so that you don’t miss a lot. 

                <br>
			</p>
			<p class="pb-2">
				When Google believes that some of your site links are harmful, they send you the unnatural links warning. Our experts will help you identify those manipulative links and remove them from your site.

			</p>

	</div>
</div>
<div class="container-fluid seopanelty-sec2">
	<div class="container">
		<h2>GOOGLE PANDA RECOVERY SERVICE  </h2>
			<span class="bottomLineImgStyle"></span>

			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 offset-lg-4 offset-md-4 mx-auto d-block">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
								<img src="assets/img/seopenalty/googlepadarecovery-img.png" alt="" class="p-3">
						</div>
						<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
							 
							<p class="p-3">
								Google Panda hits the websites that have poor quality, duplicate or spun content and the ones that are packed with images and advertisements. Panda penalty leaves you with no option than to seek the help of our experts to get the lost or dropped rankings back. This is where our Google Panda recovery service comes to your rescue. Our Panda recovery experts help you with checking your site rankings, checking Analytics and Webmasters tools, finding duplicate content and recommending you to remove some content or pages. 

                                <h3>We further offer you:</h3>
                                <ol type="1">
                                    <li> Rank check </li>
                                    <li> Resubmit XML sitemap in webmaster tools </li>
                                    <li> Analyze low quality content issues </li>
                                    <li> Copyscape web pages to find duplicate content </li>
                                </ol>
                               
                                
                                
                                
							</p><br>
							
						</div>
					</div>
				</div>
			</div>
	</div>
</div>
<div class="container-fluid seopanelty-sec3">
	<div class="container">
		<h2> GOOGLE PENGUIN RECOVERY SERVICE </h2>
			<span class="bottomLineImgStyle"></span>

			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12  mx-auto d-block">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
								<img src="assets/img/seopenalty/googlepadarecovery-img2.png" alt="" class="p-3">
						</div>
						<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
							 
							<p class="p-3">
								The penguin penalty targets the sites that have poor links and where there is over optimization of anchor texts. Our experts run a series of checks that involve looking at the major link factors and more. All unnatural or harmful links are checked using Google penalty checker tool, poor links are identified and removed and more. 

							</p><br>
							<p>
							    <h3>What we do: </h3>
							    <ol type="1">
                                    <li>Evaluate unnatural links</li>
                                    <li>Monitor Google Webmaster Tools for changes in inbound links </li>
                                    <li>Finding links to be removed</li>
                                    <li>Contact webmasters to remove the bad links</li>
                                    <li>Analyze links from Google Webmaster Tool Latest Link Report, ahrefs, Majestic SEO etc </li>
                                </ol>
							</p>
						</div>
					</div>
				</div>
			</div>
	</div>
</div>
<hr>
	<div class="container-fluid reputationmngtser-sec">
		<div class="container">	
			<h2> GOOGLE PENALTY REMOVAL SERVICE FOR YOUR SAFETY  </h2>
			<span class="bottomLineImgStyle"></span>
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="reputationmngtser-innersec">
						  <img src="assets/img/reputationmanagementservice/icons/icon1.png" alt="" class="img-s"> 
						  <h3> CLEAN WEBSITE  </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> Deleting low quality bad links and content from your site is what our experts are specialized in. this helps you to have a clean and proper website to recover after the penalty. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="reputationmngtser-innersec">
						  <img src="assets/img/reputationmanagementservice/icons/icon2.png" alt="" class="img-s"> 
						  <h3> FASTER RECOVERY </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> When you are hit by Panda or Penguin penalty, we make it easier for you to recover from such tough penalties and make sure that we do it in the shortest time possible. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="reputationmngtser-innersec">
						  <img src="assets/img/reputationmanagementservice/icons/icon3.png" alt="" class="img-s"> 
						  <h3> BAD LINKS REMOVAL  </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p>If you have poor links on your site, we can help you get rid of them. We analyze which links are dragging your site down and remove them carefully. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="reputationmngtser-innersec">
						  <img src="assets/img/reputationmanagementservice/icons/icon4.png" alt="" class="img-s"> 
						  <h3> EASY EXECUTION  </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> Experts at SEOEaze evaluate your website for poor content, bad inks and closely scrutinize the problem areas. We provide recovery solutions that are easy to execute and doesn’t make your site miss a lot. </p>
					</div>
				</div>

			</div>
				<h3 class="text-center mt-2" style="font-size: 17px;">LOSING OUT RANKINGS? DROP IN TRAFFIC? TRUST US AND LET US TAKE YOU OUT FROM GOOGLE PENALTIES </h3>
				
		</div>
	</div>


<!-- End reputationmngtser sec -->

<!-- -->

<div class="container-fluid reputationmngtser2" id="requsetconsultationpanda">
		<div class="container">

			<div class="row m-5">
			
				<div class="col-lg-5 col-md-5 col-sm-12 mt-5">
				<h3 class="pb-5 text-center">Request Consultation</h3>
						<div class="reputationmngtser-inrsecbox">
							
                            	<form action="/panda_penguin_post" method="post">   
                            	{{ csrf_field() }}
                                	<div class="row">
                                	    <label class="b-form-horizontal__label d-none" for="create_account_email"> Full Name</label> 
                                    	<div class="col-lg-12"><input type="text" id="create_account_email" name="first_name" placeholder="Full Name: "></div>
                                    	<label class="b-form-horizontal__label d-none" for="create_account_password">Email</label>             
                                        <div class="col-lg-12"><input type="text" id="create_account_password" name="email" placeholder=" Email: "></div>
                                        <label class="b-form-horizontal__label d-none" for="create_account_confirm">Phone</label>   
                                    	<div class="col-lg-12"><input type="text" id="create_account_confirm" name="phone" placeholder=" Phone: "></div>
                                    	<label class="b-form-horizontal__label d-none" for="create_account_phone">Website</label>   
                                        <div class="col-lg-12"><input type="text" id="create_account_phone" name="website" placeholder=" Website: "></div>
                                        <label class="b-form-horizontal__label d-none" for="create_account_location">Website Suffering From?</label>
                                    	<div class="col-lg-12"><input type="text" id="create_account_location" name="number_of_clients" placeholder=" Company Name: "></div>
                                    	<label class="b-form-horizontal__label d-none" for="create_account_name">Brief Details</label>   
                                        <div class="col-lg-12"><input type="text" id="create_account_name" name="total_monthly_spending" placeholder=" Brief Case Details: "></div>
                                    
                                    	<div class="col-lg-12"><button type="submit" class="button4"> Submit Request </button></div>
                                    </div>
                                </form>
                            </div>

				</div>
				<div class="col-lg-7 col-md-7 col-sm-12">
					<div class="row m-5">
					<h3 class="pb-5 text-center">WHY CHOOSE SEOEAZE? </h3>
						<div class="col-lg-12 col-md-12 col-sm-12 reputationmngtser-inrsec">
							<h3 class="">Pocket friendly packages</h3>
							<p>We offer affordable Google Penalty Recovery service packages to help you get your site back from the severe hit. You can choose our penalty recovery services for all your content or link related woes. </p>
						</div>
					</div>
					<div class="row m-5">
						<div class="col-lg-12 col-md-12 col-sm-12 reputationmngtser-inrsec">
							<h3>Dedicated recovery experts </h3>
							<p>We have a team of dedicated recovery experts who are well adept at handling such sites. They know about the recent updates and penalties and work on your site accordingly. </p>
						</div>
					</div>
					<div class="row m-5">
						<div class="col-lg-12 col-md-12 col-sm-12 reputationmngtser-inrsec">
							<h3>Detailed analysis </h3>
							<p>Our dedicated team of professionals will monitor all Google algorithms t o prepare the right strategy for your site. They carry out detailed analysis of your site for errors, penalties and poor quality work and try to rectify accordingly. </p>
						</div>
					</div>
					<div class="row m-5">
						<div class="col-lg-12 col-md-12 col-sm-12 reputationmngtser-inrsec">
							<h3>24*7 customer support </h3>
							<p>Our customer support staff is available through live chat, phone, email and Skype 24*7 to solve your problems. </p>
						</div>
					</div>

				</div>
			</div>
			
			
	</div>
</div>



<!-- -->
<!-- Start FAQs -->

<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			<h2>FAQS</h2>
			<span class="bottomLineImgStyle"></span>
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> 1. How to check that your site is penalized? </a>
									</div>
									<div id="collapseOne" class="card-body collapse" data-parent="#accordion">
										<p>There are various ways you can check that like if there is some major ranking drop, decrease in organic traffic or leads, if you get messages in Google WBT for unnatural links warning etc. </p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> 2. What caused me Google panda and penguin penalty? </a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<p>The first thing that we will help you identify is whether you have a manual action penalty, or if you have triggered something in Google's algorithm that has caused sudden harm to your keyword rankings. Regardless, penalties given out by Google can be caused by a few different factors.</p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> 3. How do you fix Google penalty? </a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">When dealing with sites that have been hit by a Google penalty - Penguin, Panda or otherwise, we take a no-nonsense approach to identifying the issues, taking action to fix those issues, and developing a strategy for the future that avoids Google penalties. </div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFourth">
										<a class="card-title"> 4. How much do Google penalty recovery services cost?</a>
									</div>
									<div id="collapseFourth" class="collapse" data-parent="#accordion">
										<div class="card-body">SEOEaze team estimates the cost of Google penalty removal based on the severity of the case. Depending on the specific issue causing the penalty, our team will assess the size and scope of the project and estimate a price based on our hourly rate. In some instances this can be as low as INR 10,000 while more complex issues can cost significantly more.</div>
									</div>
								
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
</div>




<!-- End FAQS -->
<!-- Start customers think about us Section -->


	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>WHAT OUR CLIENTS SAY ABOUT US</h2>
			<h3>IT IS OUR VALUED CUSTOMERS WHO KEEP US GOING</h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														<a href="http://b4uindia.com">www.b4uindia.com</a>
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
																				<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														<a href="http://b4uindia.com">www.b4uindia.com</a>
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		
		</div>
	</div>


<!-- End customers thinka bout us Section  -->




<!-- Start bannerFirst Section -->


	<div class="container-fluid ourpriandachiv-sec">
		<div class="container">
			<h2> OVER 2500+ BUSINESSES TRUST US  </h2>
			<span class="bottomLineImgStyle"></span>
		
			<div class="row text-center carsec-clients">
			
                           
                        <div class="parent-box8 topSlider8 owl-carousel owl-loaded owl-drag">

								
							<div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-3528px, 0px, 0px); transition: all 0.25s ease 0s; width: 9880px;"><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div></div></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button></div></div>

					</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->



<!-- Start SOME HAPPY CLIENTS  Section --> 
<div class="container-fluid featureandclient-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="featureandclient-innersec">
							<h3 class="whitecolor"> OUR ACHIEVEMENTS: OUR PRIDE </h3>
						    <span class="bottomLineImgStyle"></span>
						   
								<ul>
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon1.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon2.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon3.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon4.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon5.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon6.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon7.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon8.png"></a></li>
									
								</ul>	
							
					</div>
				</div>
			</div>
	</div>
</div>



<!-- End SOME HAPPY CLIENTS  Section -->
@endsection