@extends('layouts.master')
@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.in/reputation_management_service" hreflang="en-in" />
    <link rel="alternate" href="https://www.seoeaze.com/reputation_management_service" hreflang="en-us" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/reputation_management_service" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/reputation_management_service" hreflang="x-default" />
@endsection

@section('title', 'Reputation Management Service -Online Presence Improvement-SeoEaze')
@section('meta' , "Remove & Counter Negative Reviews & Comments harming your business by Reputation Management Service by SeoEaze & make positive brand  presence online.")
<!-- Start Breadcrumbs Schema -->
	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			 "itemListElement": [{
			   "@type": "ListItem",
			   "position": 1,
			   "name": "Home",
			   "item": "https://www.seoeaze.in/"
			 },
			{
			   "@type": "ListItem",
			   "position": 2,
			   "name": "Reputation Management Service",
			   "item": "https://www.seoeaze.in/reputation_management_service"
			 }]
		}
	</script>

	<!-- End Breadcrumbs Schema -->
	<!-- Start FAQ Schema -->
	    <script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What is reputation management?","acceptedAnswer":[{"@type":"Answer","text":"An online reputation is the rapport of a company, person, product, or service on the Internet and on digital platforms. Online reputation management (ORM) is the practice of crafting strategies that shape or influence public perception of an organization, individual or other entity on the Internet. \n"}]},{"@type":"Question","name":"Why are reputation management services important for a business? ","acceptedAnswer":[{"@type":"Answer","text":"Having a good reputation is important for your business growth. People search brands, services and products online before they make the final purchase. Healthy reputation management can help you increase your sales, build trust and credibility, and provide insights into customer preferences, and market trends.\n"}]},{"@type":"Question","name":"How much time does online reputation management take to work?","acceptedAnswer":[{"@type":"Answer","text":"Online reputation management is an ongoing process and will involve time and commitment. While Google normally recognises changes in indexed sites and profiles every 2-6 weeks, it can take 3-6 months to promote positive content, new content and social media creation, and responding to negative reviews or suppressing them.\n"}]},{"@type":"Question","name":"How does your reputation management work?","acceptedAnswer":[{"@type":"Answer","text":"SeoEaze’s ORM strategy begins with monitoring all existing web material about your brand and products through our online reputation monitoring software. We help you proactively respond to negative reviews and promote existing positive content. For long term, we help you devise ways of being a customer-friendly and more accessible brand.\n"}]},{"@type":"Question","name":"How much does ORM services cost?","acceptedAnswer":[{"@type":"Answer","text":"ORM services cost start from INR 30,000 a month and can go up to INR 80,000 a month. This cost is surely nothing when we talk about business branding. This fee covers content writing, profile creations, content syndications and link syndication activities which eventually help you to get rid of negative posts & establish positive branding.\n"}]},{"@type":"Question","name":"How long does it take to change the search results?","acceptedAnswer":[{"@type":"Answer","text":"While some changes like removing a page can take just a few days, others may involve a few weeks or even months. The time taken to change search results varies a lot on different factors. Like for a typical project to improve its online reviews may start to show results in a week or two and can continue to have better ratings and reviews over a period of a year maybe. \n"}]}]}</script><!-- Generated by https://www.seoeaze.in/ -->
	<!-- start faq schema -->
@section('header')


@show

@section('content')
    <!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-6 col-md-6 col-sm-12 header-video-sec-inner-leftsec">

									<h1> ONLINE REPUTATION MANAGEMENT </h1>
									<h2>YOUR BRAND DESERVES A BETTER ONLINE REPUTATION: REMOVE ALL NEGATIVITY </h2>
									
									<ul>
										<li> Get positive online reviews </li>
										<li> Build your reputation </li>
										<li> Fix negative comments  </li>
										<li> Protect your business </li>
									</ul>
										
									<span class="mt-5">  
										<a href="#whyus">
											<button class="button1"> Why Us?  </button>
										</a> 
										<a href="#quote">
											<button class="button2"> Get Staretd Now </button>
										</a>
									</span>
									
				  			</div>

				  			<div class="col-lg-6 col-md-6 col-sm-12 header-video-sec-inner-rightsec">
								<div class="imgblockright">	  				
									 <img src="assets/img/reputationmanagementservice/reutationmanagementservices3.png" alt="">
								</div>
				  			</div>
					</div>
			  	</div>
				
			
			</div>
			<!-- Vedio Content Section End -->
				
	</main>
			  
<!-- slider area bar end-->

<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Reputation Management Service </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->

<!-- Start reputationmngtser sec -->

<div class="container-fluid reputationmngtser-sec">
		<div class="container">
			<h2> ONLINE REPUTATION MANAGEMENT SERVICES-<br> IMPROVE YOUR RECOGNITION   </h2>
			<span class="bottomLineImgStyle"></span>
			<h3>Protect your brand from negative feedback and have a good rapport </h3>
			<p class="pb-5">As one of the best online reputation management agency India, we are proud of our legal methods, strategies and ethics. SEOEaze, being the top reputation management company, understands that the amount of prestige any brand can carry directly affect their productivity and brand recognition. We have the required knowledge of how to deal with negative publicity and how to reverse it effectively. </p>
			
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="reputationmngtser-innersec">
						  <img src="assets/img/reputationmanagementservice/icons/icon1.png" alt="" class="img-s"> 
						  <h3> Remove negativity  </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> We can help you with suppressing or removing the negative remarks or feedback you get. Further, we promote your positive side by updating your social profiles, adding press releases etc. <br><br></p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="reputationmngtser-innersec">
						  <img src="assets/img/reputationmanagementservice/icons/icon2.png" alt="" class="img-s"> 
						  <h3> Repair your reputation </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p>We help you fix the existing problems and issues. This involves removing or suppressing negative content and improving your online brand recognition. <br><br><br></p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="reputationmngtser-innersec">
						  <img src="assets/img/reputationmanagementservice/icons/icon3.png" alt="" class="img-s"> 
						  <h3> Improve your reviews </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p>Our professionals can help you improve your ratings and reviews. This will further attract more customers towards your business and let you enjoy the positive environment. <br><br></p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="reputationmngtser-innersec">
						  <img src="assets/img/reputationmanagementservice/icons/icon4.png" alt="" class="img-s"> 
						  <h3> Comprehensive tracking system  </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> We offer complete tracking to provide you with instant alerts about what is being said about your brand on various channels. Strengthen your brand by knowing what happens when. <br></p>
					</div>
				</div>

			</div>
						<p class="text-center mt-3">PROTECT YOUR BRAND, STAY SAFE & REPAIR YOUR REPUTATION NOW! </p>
				
		</div>
	</div>


<!-- End reputationmngtser sec -->

<!-- -->

<div class="container-fluid reputationmngtser2">
		<div class="container">

			<div class="row m-5">
			
				<div class="col-lg-5 col-md-5 col-sm-12 mt-5"id="quote">
				<h3 class="pb-5 text-center">Request Consultation</h3>
						<div class="reputationmngtser-inrsecbox">
							
                            	<form action="/reputation_managment_post" method="post">
                            	    {{ csrf_field()}}
                                	<div class="row">
                                	    <label class="b-form-horizontal__label d-none" for="create_account_email">Name</label>
                                    	<div class="col-lg-12"><input type="text" name="first_name" placeholder=" Name: "></div>
                                    	<label class="b-form-horizontal__label d-none" for="create_account_password">Email</label>
                                        <div class="col-lg-12"><input type="text" name="email" placeholder=" Email: "></div>
                                        <label class="b-form-horizontal__label d-none" for="create_account_confirm">Phone</label>
                                    	<div class="col-lg-12"><input type="text" name="phone" placeholder=" Phone: "></div>
                                    	<label class="b-form-horizontal__label d-none" for="create_account_phone">Website</label>
                                        <div class="col-lg-12"><input type="text" name="website" placeholder=" Website: "></div>
                                        <label class="b-form-horizontal__label d-none" for="create_account_location">Company Name</label>
                                    	<div class="col-lg-12"><input type="text" name="number_of_clients" placeholder=" Company Name: "></div>
                                    	<label class="b-form-horizontal__label d-none" for="create_account_name">Brief Case Details</label>
                                        <div class="col-lg-12"><input type="text" name="total_montly_spending" placeholder=" Brief Case Details: "></div>
                                    
                                    	<div class="col-lg-12"><button type="submit" class="button4"> Send Message </button></div>
                                    </div>
                                </form>
                            </div>

				</div>
				<div class="col-lg-7 col-md-7 col-sm-12"id="whyus">
					<div class="row m-5">
					<h3 class="pb-5 text-center">WHY CHOOSE SEOEAZE? </h3>
						<div class="col-lg-12 col-md-12 col-sm-12 reputationmngtser-inrsec">
							<h3 class="">Industry experts since a decade </h3>
							<p>We have been serving our clients protect their brand since a decade now. You can trust us for all your reputation management requirements. </p>
						</div>
					</div>
					<div class="row m-5">
						<div class="col-lg-12 col-md-12 col-sm-12 reputationmngtser-inrsec">
							<h3>Ethical approach </h3>
							<p>At SEOEaze, we follow ethical approach towards safeguarding your reputation and rapport in the market. You can be sure of being in trusted hands for best online reputation management. </p>
						</div>
					</div>
					<div class="row m-5">
						<div class="col-lg-12 col-md-12 col-sm-12 reputationmngtser-inrsec">
							<h3>Tracking and improving feedback </h3>
							<p>With instant tracking updates, we ensure to improve your rating and reviews in the online world. Negative remarks are removed and we work towards creating a positive atmosphere for you. </p>
						</div>
					</div>
					<div class="row m-5">
						<div class="col-lg-12 col-md-12 col-sm-12 reputationmngtser-inrsec">
							<h3>Effective methods used </h3>
							<p>We use tried and tested, effective ways to have good online reputation for your business. You can trust us for using the up-to-date techniques to protect your name.  </p>
						</div>
					</div>

				</div>
			</div>
			
			
	</div>
</div>












<!-- -->
<!-- Start FAQs -->

<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			<h2>FAQS</h2>
			<span class="bottomLineImgStyle"></span>
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> 1. What is reputation management?</a>
									</div>
									<div id="collapseOne" class="card-body collapse" data-parent="#accordion">
										<p>An online reputation is the rapport of a company, person, product, or service on the Internet and on digital platforms. Online reputation management (ORM) is the practice of crafting strategies that shape or influence public perception of an organization, individual or other entity on the Internet. </p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> 2. Why are reputation management services important for a business?  </a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<p>Having a good reputation is important for your business growth. People search brands, services and products online before they make the final purchase. Healthy reputation management can help you increase your sales, build trust and credibility, and provide insights into customer preferences, and market trends.</p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> 3. How much time does online reputation management take to work? </a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">Online reputation management is an ongoing process and will involve time and commitment. While Google normally recognises changes in indexed sites and profiles every 2-6 weeks, it can take 3-6 months to promote positive content, new content and social media creation, and responding to negative reviews or suppressing them.</div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFourth">
										<a class="card-title"> 4. How does your reputation management work?</a>
									</div>
									<div id="collapseFourth" class="collapse" data-parent="#accordion">
										<div class="card-body">SeoEaze’s ORM strategy begins with monitoring all existing web material about your brand and products through our online reputation monitoring software. We help you proactively respond to negative reviews and promote existing positive content. For long term, we help you devise ways of being a customer-friendly and more accessible brand.</div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFifth">
										<a class="card-title"> 5. How much does ORM services cost?</a>
									</div>
									<div id="collapseFifth" class="collapse" data-parent="#accordion">
										<div class="card-body">ORM services cost start from INR 30,000 a month and can go up to INR 80,000 a month. This cost is surely nothing when we talk about business branding. This fee covers content writing, profile creations, content syndications and link syndication activities which eventually help you to get rid of negative posts & establish positive branding. </div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSixth">
										<a class="card-title"> 6. How long does it take to change the search results?</a>
									</div>
									<div id="collapseSixth" class="collapse" data-parent="#accordion">
										<div class="card-body">While some changes like removing a page can take just a few days, others may involve a few weeks or even months. The time taken to change search results varies a lot on different factors. Like for a typical project to improve its online reviews may start to show results in a week or two and can continue to have better ratings and reviews over a period of a year maybe. </div>
									</div>
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
</div>




<!-- End FAQS -->





<!-- Start Call/WhatsApp Us -->
<div class="container-fluid callus-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure class="callusleftsec"><img src="assets/img/linkbulding/callus-iconimg.png"> </figure>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
					<p class="callusmiddlesec">
						WE ARE THIS CLOSE TO MANAGING YOUR REPUTATION<br>
						CALL Us On  <span>8375011200</span> To Discuss

					</p>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure class="callusrightsec"><img src="assets/img/linkbulding/callus-girlimg.png"> </figure>
				</div>
			</div>
		</div>
	</div>

<!-- End Call/WhatsApp Us -->



<!-- Start customers think about us Section -->


	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>WHAT OUR CLIENTS SAY ABOUT US</h2>
			<h3>IT IS OUR VALUED CUSTOMERS WHO KEEP US GOING</h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														<a href="http://b4uindia.com">www.b4uindia.com</a>
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
																				<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														<a href="http://b4uindia.com">www.b4uindia.com</a>
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		
		</div>
	</div>


<!-- End customers thinka bout us Section  -->




<!-- Start bannerFirst Section -->


	<div class="container-fluid ourpriandachiv-sec">
		<div class="container">
			<h2> OVER 2500+ BUSINESSES TRUST US  </h2>
			<span class="bottomLineImgStyle"></span>
		
			<div class="row text-center carsec-clients">
			
                           
                        <div class="parent-box8 topSlider8 owl-carousel owl-loaded owl-drag">

								
							<div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-3528px, 0px, 0px); transition: all 0.25s ease 0s; width: 9880px;"><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div></div></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button></div></div>

					</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->



<!-- Start SOME HAPPY CLIENTS  Section --> 
<div class="container-fluid featureandclient-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="featureandclient-innersec">
							<h3 class="whitecolor"> OUR ACHIEVEMENTS: OUR PRIDE </h3>
						    <span class="bottomLineImgStyle"></span>
						   
								<ul>
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon1.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon2.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon3.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon4.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon5.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon6.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon7.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon8.png"></a></li>
									
								</ul>	
							
					</div>
				</div>
			</div>
	</div>
</div>



<!-- End SOME HAPPY CLIENTS  Section -->
@endsection