@extends('layouts.master')
@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.in/social_media_marketing" hreflang="en-in" />
    <link rel="alternate" href="https://www.seoeaze.com/social_media_marketing" hreflang="en-us" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/social_media_marketing" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/social_media_marketing" hreflang="x-default" />
@endsection
@section('title', 'Social Media Marketing Plans -Best Social Media Marketing Company India | SeoEaze')
@section('meta' , "Want To Boost Your Company's Online Presence? Check Our Social Media Marketing Plans. Start with a FREE audit by The Best Social Media Marketing Company India.")
<!-- Start Breadcrumbs Schema -->
	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			 "itemListElement": [{
			   "@type": "ListItem",
			   "position": 1,
			   "name": "Home",
			   "item": "https://www.seoeaze.in/"
			 },
			{
			   "@type": "ListItem",
			   "position": 2,
			   "name": "Social Media Marketing",
			   "item": "https://www.seoeaze.in/social_media_marketing"
			 }]
			}
	</script>


	<!-- End Breadcrumbs Schema -->

	<!-- FAQ Schema start -->
        <script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Are Custom Social Media Packages Available?","acceptedAnswer":[{"@type":"Answer","text":"Yes, we can create custom SMO packages for you. Just email us your requirement at info@seoeaze.in.\n"}]},{"@type":"Question","name":"How SMO is important for my business?","acceptedAnswer":[{"@type":"Answer","text":"Social Media Optimization helps to build brand recognition in the online world. SMO optimizes your content that can be visible on popular social media platforms.\n"}]},{"@type":"Question","name":"Can we increase followers on Facebook and Instagram using SMO techniques?","acceptedAnswer":[{"@type":"Answer","text":"Yes, SMO tends to increase followers on various social media platforms. \n"}]},{"@type":"Question","name":"What are your Social Media packages and pricing?","acceptedAnswer":[{"@type":"Answer","text":"Our social media packages start from INR 9000. However, they may vary according to the client’s requirements.\n"}]}]}</script><!-- Generated by https://www.seoeaze.in/ -->
	<!-- FAQ Schema end -->
@section('header')
@show
@section('content')
    
<!-- Header part end-->

<!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-7 col-md-7 col-sm-12 header-video-sec-inner-leftsec">

									<h1> SOCIAL MEDIA MARKETING  </h1>
									<h2> Enhance your social presence; connect with more people  </h2>
										
									<ul>
										<li> Have your presence on various social media networks  </li>
										<li> Increase your followers </li>
										<li> Create brand awareness </li>
										<li> Increase customer engagement </li>
										<li> Manage brand visibility </li>
									</ul>
										
										
									<span>  
									<a href="#benefits">
										<button class="button1"> See Benefits </button>
									</a> 
									<a href="" data-toggle="modal" data-target="#myModal">
										<button class="button2"> Start Now! </button>
									</a>
									</span>
									<p class="pt-5"><img src="assets/img/seopackages/seoPackages-sertificate.png" alt=""></p>
				  			</div>

				  			<div class="col-lg-5 col-md-5 col-sm-12 header-video-sec-inner-rightform-sec"  id="smmformsec">
				  				
								<div class="header-form-sec">
									<h4> Start With <span> Free</span>  Audit </h4>
									<span class="bottomLineImgStyle2"></span>
									<form role="form" method="post" action="/social_media_form"> 
									{{ csrf_field() }}
									    <label class="sr-only" for="r-form-1-first-name">Name</label>
    									<input type="text" name="first_name" id="r-form-1-first-name" placeholder="Name:" class="textbox-cls">
    									<label class="sr-only" for="r-form-1-last-name">E-mail</label>
    									<input type="text" name="email" id="r-form-1-first-name" placeholder="E-mail:" class="textbox-cls">
    									<label class="sr-only" for="r-form-1-email">Phone</label>
    									<input type="text" name="phone" id="r-form-1-email" placeholder="Phone:" class="textbox-cls">
    									<label class="sr-only" for="r-form-1-email">Website</label>
    									<input type="text" name="website" id="r-form-1-email" placeholder="Website:" class="textbox-cls">
    									<label class="sr-only" for="r-form-1-email">Company Name</label>
    									<input type="text" name="company_name" id="r-form-1-email" placeholder="Company Name:" class="textbox-cls">
    									
    									<!-- Check box start -->
    
    										<div class="checkbox" style="margin-bottom:10px; margin-top: 20px; text-align: center;">
    											<label style="line-height: 18px; padding-left: 12px">
    												<input type="checkbox" value="yes" name="facebook">
    												<span class="cr"><i style="color: white;" class="cr-icon fa fa-facebook"></i></span>
    												<span style="color:white; font-size:12px;">Facebook</span> </label>
    											<label style="line-height: 18px; padding-left: 12px; font-size:12px;">
    												<input type="checkbox" value="yes" name="google">
    												<span class="cr"><i style="color: white; font-size: 11px" class="cr-icon fa fa-instagram"></i></span>
    												<span style="color:white; font-size:12px;">Instagram</span> </label>
    											<label style="line-height: 18px; padding-left: 12px">
    												<input type="checkbox" value="yes" name="twiiter">
    												<span class="cr"><i style="color: white; " class="cr-icon fa fa-twitter"></i></span>
    												<span style="color:white; font-size:12px;">Twitter</span> </label>
    										</div>
    										
    										<hr>
    										
    										<div class="checkbox" style="margin-bottom:0;margin-top: 0;text-align: center;">
    											<label style="line-height: 18px; padding-left: 12px">
    												<input type="checkbox" value="yes" name="subscribe" checked>
    												<span class="cr"><i style="color: white;" class="cr-icon fa fa-check"></i></span>
    												<span style="color:white; font-size:12px;">Send Me Latest Updates </span>
    											</label>
    										</div>
    										
    									<!-- Check box End -->
    									<button type="submit">Submit Request</button>
    									<p class="form-pcls"> We Will Never Spam Your Inbox </p>
									</form>
								</div>

				  			</div>
					</div>
			  	</div>
				
			
			</div>
			<!-- Vedio Content Section End -->
							

	</main>
			  
<!-- slider area bar end-->

<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Social Media Marketing </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->



<!-- Start WHY SEOEAZE FOR SOCIAL MEDIA MARKETING sec -->

<div class="container-fluid blogmanagementservice-sec">

		<div class="container">
		
			<h2>WHAT IS SOCIAL MEDIA MARKETING? <br> WHY CHOOSE SEOEAZE? </h2>
			<span class="bottomLineImgStyle"></span>

			<div class="row pt-5 mt-5">
			<div class="col-lg-4 col-md-4 col-sm-12 offset-lg-1 offset-md-1 mx-auto d-block">
				<figure><img src="assets/img/social_media_marketing_img/social-media-marketing-img1.png" alt=""></figure>
			</div>

				<div class="col-lg-6 col-md-6 col-sm-12 p-5 mx-auto d-block">
					<p>
						As one of the best social media marketing companies in India, we at SEOEaze acknowledge that social media marketing gives 100% positive leads towards real sales. So irrespective of your business, we help you to gain active presence on different social media platforms. <br><br>
					</p>
					<p>
						Creating brand awareness on different social platforms becomes interesting with us. Our social media specialists understand your business and target your audience accordingly.
					</p>
					<p>
						As a social media marketing expert, we manage social networks like Facebook, Twitter, Instagram and more. We use effective SMO techniques to let your business get better visibility on major social platforms. <br><br>
					</p>
				</div>

			</div>
			
			
			<div class="row pt-5 mt-5">
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="blogmanagementservice-secondsec">
							<div class="card">
							  <img class="card-img-top" src="assets/img/social_media_marketing_img/social_media_marketing_facebookimg.png" alt="Card image cap">
							  <div class="card-body">
								<h4 class="card-title">FACEBOOK</h4>
								<span class="bottom-line-stylesmallimg"></span>
                                <p class="card-text">
									With our FB marketing service, you can have more customers coming your way. We help to manage your Facebook account and help promoting your products and services through it. Links to your recent blog posts or quiz or contests can engage the customers and bring in more sales. 
								</p>
								
								
							  </div>
							</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="blogmanagementservice-secondsec">
							<div class="card">
							  <img class="card-img-top" src="assets/img/social_media_marketing_img/social_media_marketing_instagramimg.png" alt="Card image cap">
							  <div class="card-body">
								<h4 class="card-title">INSTAGRAM</h4>
								<span class="bottom-line-stylesmallimg"></span>
                                <p class="card-text">We can help you promote your brand through appealing images on Instagram. You can have pictures of your team, services, products and we can help you to write the perfect hashtags and status for your posts. take your Intagram marketing to another level with our expert services. </p>
							  </div>
							</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="blogmanagementservice-secondsec">
							<div class="card">
							  <img class="card-img-top" src="assets/img/social_media_marketing_img/social_media_marketing_twitterimg.png" alt="Card image cap">
							  <div class="card-body">
								<h4 class="card-title">TWITTER</h4>
								<span class="bottom-line-stylesmallimg"></span>
                                <p class="card-text">Another great platform is Twitter where you can share links and information with the readers. We use the best Twitter marketing strategy to offer the information you want and we can help you with this in the best possible way. Our social media marketing experts will handle your Twitter account, add images, follow similar businesses, update tweets, manage ads and more. </p>
							  </div>
							</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="blogmanagementservice-secondsec">
							<div class="card">
							  <img class="card-img-top" src="assets/img/social_media_marketing_img/social_media_marketing_complitepacageimg.png" alt="Card image cap">
							  <div class="card-body">
								<h4 class="card-title">COMPLETE PACKAGES</h4>
								<span class="bottom-line-stylesmallimg"></span>
                                <p class="card-text">We also offer all-in-one packages to help you with all types of social media marketing services like Facebook, Google+, Twitter, Pinterest, Instagram and more. By this, we help to keep all SMO solutions under one big roof so that you don’t have to skip one or the other service. </p>
								
							  </div>
							</div>
					</div>
				</div>


			</div>
			


		</div>
</div>

<!--End -->








<!-- Start FEATURES & BENEFITS OF OUR SEO PACKAGES sec-->


<div class="container-fluid blogMgtfeaturesandbenefits-sec" id="benefits">
		<div class="container">
			<h2> OUR SMO FEATURES & BENEFITS  </h2>
			<span class="bottomLineImgStyle"></span>
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/social_media_marketing_img/icons/icon1.png" alt="" class="img-s"> 
						  <h3 class="h3class"> BRAND AWARENESS </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> Increase your brand awareness through popular social networks. this not only enhances your social presence but even your business credibility. <br><br><br></p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/social_media_marketing_img/icons/icon2.png" alt="" class="img-s"> 
						  <h3 class="h3class"> GET MORE VISITORS </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> By having a strong social presence, you can automatically attract more visitors to your site. this will further increase the chances of your profits.<br><br></p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/social_media_marketing_img/icons/icon3.png" alt="" class="img-s"> 
						  <h3 class="h3class"> OFFLINE MARKETING </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> Good Social media marketing can contribute in offline marketing as well. It is through social media that people will get to know about your business and may visit your store/company for offline solutions.</p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/social_media_marketing_img/icons/icon4.png" alt="" class="img-s"> 
						  <h3 class="h3class"> Performance tracking and reporting </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> We provide weekly and monthly updates of your projects so to help you track your site’s progress. We also provide what has been planned for the coming months.</p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/social_media_marketing_img/icons/icon5.png" alt="" class="img-s"> 
						  <h3 class="h3class"> SOCIAL MEDIA PRESENCE </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> With our social media marketing services, you can have increased social presence. Enjoy more fans, followers, likes and more when you hire our expert SMO solutions. </p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<div class="blogMgtfeaturesandbenefits-innersec">
						  <img src="assets/img/social_media_marketing_img/icons/icon6.png" alt="" class="img-s"> 
						  <h3 class="h3class"> GO VIRAL </h3>
						  <span class="bottom-line-stylesmallimg"></span>
						  <p> The biggest advantage of SMM is that you can get your things go viral instantly. our experts create engaging content that it gets viral and famous in no time, gaining high popularity for your business. </p>
					</div>
				</div>
			</div>
			
				
		</div>
	</div>


<!-- End FEATURES & BENEFITS OF OUR SEO PACKAGES sec -->


<!-- Start Get free Audit report sec -->
<div class="container-fluid getfreeaudit-sec">
	<div class="container">
		
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12">
					<div class="getfreeaudit-leftinnersec">
						<img src="assets/img/blog-management/getfreeaudit-sec-leftimg.jpg" alt="">
					</div>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
					<div class="getfreeaudit-rightinnersec max-auto">
					    <a href="#smmformsec">
						<button class="button3"> GET YOUR FREE AUDIT REPORT </button>
						</a>
					</div>
				</div>
			</div>
	</div>
</div>
<!-- End Get free Audit report sec -->

<!-- Faq start -->

<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			<h2>FAQS</h2>
			<span class="bottomLineImgStyle"></span>
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> 1. Are Custom Social Media Packages Available? </a>
									</div>
									<div id="collapseOne" class="card-body collapse" data-parent="#accordion">
										<p>Yes, we can create custom SMO packages for you. Just email us your requirement at info@seoeaze.in.</p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> 2. How SMO is important for my business?</a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<p>Social Media Optimization helps to build brand recognition in the online world. SMO optimizes your content that can be visible on popular social media platforms.</p>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> 3. Can we increase followers on Facebook and Instagram using SMO techniques?</a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">
										    <p>
										        Yes, SMO tends to increase followers on various social media platforms. 
										    </p> 
										</div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFourth">
										<a class="card-title"> 4. What are your Social Media packages and pricing?</a>
									</div>
									<div id="collapseFourth" class="collapse" data-parent="#accordion">
										<div class="card-body"><p>
											Our social media packages start from INR 9000. However, they may vary according to the client’s requirements.

										</p> </div>
									</div>
									
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
</div>
<!-- Faq End-->
<!-- Start customers think about us Section -->


	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>Words From Our Clients </h2>
			<h3>Our Valued Customers Believe In Us & This Is What Keeps Us Going </h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
																				<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Anand Maheshwari </h3>
													<h4> B4U India </h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		
		</div>
	</div>


<!-- End customers thinka bout us Section  -->



<!-- Start bannerFirst Section -->


	<div class="container-fluid ourpriandachiv-sec">
		<div class="container">
			<h2> MORE THAN 2500 BUSINESSES TRUSTED US </h2>
			<span class="bottomLineImgStyle"></span>
		
			<div class="row text-center carsec-clients">
			
                           
                        <div class="parent-box8 topSlider8 owl-carousel owl-loaded owl-drag">

								
							<div class="owl-stage-outer"><div class="owl-stage" style="transform: translate3d(-3528px, 0px, 0px); transition: all 0.25s ease 0s; width: 9880px;"><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item active" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-1.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-2.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-3.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-4.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-5.png">
                                </div></div><div class="owl-item cloned" style="width: 166.422px; margin-right: 10px;"><div class="box8">
                                     <img src="./assets/img/partners/client-logo-6.png">
                                </div></div></div></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button></div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><img src="./assets/img/left-arrow-black.png"></button><button type="button" role="presentation" class="owl-next"><img src="./assets/img/right-arrow-black.png"></button></div><div class="owl-dots"><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button></div></div>

					</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->



<!-- Start SOME HAPPY CLIENTS  Section --> 
<div class="container-fluid featureandclient-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="featureandclient-innersec">
							<h3 class="whitecolor"> OUR ACHIEVEMENTS: OUR PRIDE </h3>
						    <span class="bottomLineImgStyle"></span>
						    <p> 
								</p><ul>
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon1.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon2.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon3.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon4.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon5.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon6.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon7.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon8.png"></a></li>
									
								</ul>	
							<p></p>
					</div>
				</div>
			</div>
	</div>
</div>



<!-- End SOME HAPPY CLIENTS  Section --> 


@endsection