@extends('layouts.master')


@section('title', 'Web Content Writing Services -Buy Articles, eBook, Blog Posts, Reviews')
@section('meta' , "SeoEaze offering all Web Content Writing Services, You can buy article writing service, Blog posts writing, Press Releases, eBooks, Product Reviews & more..")


@section('header')

@section('hreflangs')
    <link rel="canonical" href="https://www.seoeaze.com/content_writing_service" />
@endsection
<!-- Start Breadcrumbs Schema -->
<script type="application/ld+json">
{
  "@context": "https://schema.org/", 
  "@type": "BreadcrumbList", 
  "itemListElement": [{
    "@type": "ListItem", 
    "position": 1, 
    "name": "Home",
    "item": "https://www.seoeaze.com"  
  },{
    "@type": "ListItem", 
    "position": 2, 
    "name": "Content Writing Service",
    "item": "https://www.seoeaze.com/content_writing_service"  
  }]
}
</script>
<!-- End Breadcrumbs Schema -->

<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Will the content be original?","acceptedAnswer":[{"@type":"Answer","text":"100% Guaranteed. At SeoEaze, we have a stringent 'no plagiarism policy' which assures our clients that our content writing services are reliable. We make use of premium plagiarism tools like Copyscape, ensuring delivery of only original high-quality content written by native writers.\n"}]},{"@type":"Question","name":"How do I know that I will get top quality content?","acceptedAnswer":[{"@type":"Answer","text":"In over a decade of our existence, SeoEaze content writing services have served over 1500 global clients who speak of our quality services. Our content offers high value and so almost all the clients are our long-time partners.\n"}]},{"@type":"Question","name":"What industries does SeoEaze cater to?","acceptedAnswer":[{"@type":"Answer","text":"We have expert content writers who have experience and knowledge of various topics and subjects. Our native writers have in-depth knowledge of several industries spanning across IT, real estate, education, eCommerce, tourism, hospitality, healthcare and others. When you hire us, we match your project with the best-suited writers who are aware of terminologies and technicalities of your industry.\n"}]},{"@type":"Question","name":"Do you charge extra for revisions?","acceptedAnswer":[{"@type":"Answer","text":"At SeoEaze, we ensure that there are no hidden costs that surprise our clients. Every cost will be detailed upfront when you hire us. For minor revisions and editing, there are no additional costs. Our editors make sure that you receive error-free and accurate copy in the right format. But if you need any revision done, we get at it as soon as we get your feedback.\n"}]}]}</script><!-- Generated by https://www.seoeaze.com/ -->
<style>
	h2 {color:#000;}
	
</style>	
@show

@section('content')

<!-- slider area bar start-->
	
<section class="local_seosec">
					<div class="container">
							<div class="social_media_marketing_solution_left_sec i-can-has-a-colored-thing">
									<h2><span class="highlight">Content Writing Service </span> </h2>
									<h4>Quality Content You Need</h4>
									<p>
									Get content that builds your name and sells, written by humans: 
									</p>
									<ul>        
												<li>Subject matter-expert writers</li>
												<li>Experience writers from all industries </li>
												<li>100% original, plagiarism free content </li>
												<li>Timely delivery, well researched content </li>
									</ul>
										
									<div class="indibuttons">
									<a href="#samples">
										<button class="btn-hover color-2"> Writing Samples 
											<span class="roundshapebutton roundshapearrow"> 
												<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
													<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
												</svg>
											</span>
										</button>
									</a>
									</div>
									<div class="indibuttons">
									<a href="#getintouch">
										<button class="btn-hover color-1"> Get Started 
											<span class="roundshapebutton roundshapearrow"> 
												<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
													<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
												</svg>
											</span>
										</button>
										</a>
									</div>
							</div>
							<div class="social_media_marketing_solution_right_sec">
									<img src="assets/img/content-writing-services/content-writing.webp" alt="content writing by seoeaze" />
							</div>
					</div>

				</section>


				<section class="ourbestcapabilitysec">
					<div class="row">
						<div class="col-lg-6 col-md-12 col-sm-12">
							 <div class="ourbestcapabilityleftsec i-can-has-a-colored-thing">
									<h2>Quality Content That <sapn class="highlight">Grows Your Business</sapn></h2>
									<h4></h4>
									<p><span class="highlight"><b>126% MORE LEADS</b></span> are generated by businesses from a blog compared to other mediums.</p>
									<p><span class="highlight"><b>2nd MOST SUCCESSFUL LEAD GENERATION </b></span> tactic.Content marketing is only below email marketing in lead generation.</p>
									<p><span class="highlight"><b>3x MORE LEADS </b></span> are generated with content marketing compared to any traditional outbound approach.</p>
									<p><span class="highlight"><b>62% LESS COST</b></span>  is incurred when you engage in content marketing.</p>
									<p>You do not need more reasons than these to invest in high-quality content development. SeoEaze’s web content writing services are made to suit your requirements without getting over budget.<br><br>Delegate your content requirements to our industry skilled writers who deliver your content on time. Whatever industry you are in, our writers can easily create content that engages your audience.</p> 
								</div>
						</div>
						<div class="col-lg-6 col-md-12 col-sm-12">
								<div class="ourbestcapabilityrightsec">
										<img src="assets/img/seo_packages_img/ourbestcapabilityrightsecimg.webp" alt="" />
										<div class="thirdrighttsec">
												<p>
														Your Content Strategy
														Is Awaiting
												</p>
												<div class="indibuttons">
												<a href="javascript:;" data-toggle="modal" data-target="#myModal">
													<button class="btn-hover color-1"> Ping Now 
														<span class="roundshapebutton roundshapearrow"> 
															<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
																<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
															</svg>
														</span>
													</button></a>
												</div>
											</div>
								</div>
						</div>
					</div>
				</section>

				<section class="weareatrustedgooglepartner">
						<div class="weareatrustedgooglepartnerleftsec i-can-has-a-colored-thing">
								<h2>WE ARE A TRUSTED <span class="highlight">GOOGLE PARTNER </span></h2>
								<p>We are proud to mention that we are a certified Google Partner. As a Google certified company, we can proactively update content strategies for your clients and their businesses. We have even earned the much-valued Google Partner badge.</p>
						</div>
						<div class="weareatrustedgooglepartnerrightsec">
							<div class="googlepartnersec">
								<img src="assets/img/seo_packages_img/googlepartnerimg.webp" alt="google partner" />
									<div class="googlepartner1"><img src="assets/img/seo_packages_img/googlepartnericon5.webp" alt="" /></div>
									<div class="googlepartner2"><img src="assets/img/seo_packages_img/googlepartnericon4.webp" alt="" /></div>
									<div class="googlepartner3"><img src="assets/img/seo_packages_img/googlepartnericon3.webp" alt="" /></div>
									<div class="googlepartner4"><img src="assets/img/seo_packages_img/googlepartnericon2.webp" alt="" /></div>
									<div class="googlepartner5"><img src="assets/img/seo_packages_img/googlepartnericon1.webp" alt="" /></div>
							</div>

						</div>

				</section>
<!-- Start Key services sec -->
<section class="social_media_marketing_solution_featuresandbenifitsec">
					<h2> SEO & Enterprise Content Development </h2>
					<div class="row m-0">
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecwhitebgimg">
								<h4>High quality</h4>
								<p>We offer high quality, keyword-rich SEO content for your site/blog. Use our content to convert. </p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecgreenbgimg">
								<h4>SEO Optimized </h4>
								<p>We ensure that the content we deliver is SEO optimized to get you on top. Our professionals take extra efforts to deliver the BEST. </p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecwhitebgimg">
								<h4>Original and targeted </h4>
								<p>At SEOEaze, you can be sure of getting original content writing services at affordable rates. Our writers create fresh, targeted content for your needs.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecgreenbgimg">
								<h4> Complex projects  </h4>
								<p> Our professionals add their expertise to your complex projects, delivering high quality content writing. They can handle any sort of complicated content with ease. </p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecwhitebgimg">
								<h4>Fully managed </h4>
								<p>Our writing team is well aware of how to tackle your content programs. When you choose our enterprise content services, you get industry veterans writing your content.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecgreenbgimg">
								<h4>Fast turnaround</h4>
								<p>We deliver most orders within 24-48 hours. Our team takes turnaround time very seriously and deliver fast yet professional results. </p>
							</div>
						</div>
					</div>

				</section>
	
<!-- End  Hire the Perfect Content Writer SECTION -->


<!-- Start OUR WRITING SAMPLES Section -->
	<div class="container-fluid ourwritingsamples-sec" id="samples">
		<div class="container">
			<h2>OUR WRITING SAMPLES </h2>
			<span class="bottomLineImgStyle"></span>
			
			
			<div class="row">
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon1.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Blogs  Writing Samples</p>
						  <a href="/assets/cws_files/blog_posts.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon2.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Web Content Samples</p>
						  <a href="/assets/cws_files/web_content.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon3.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Review <br>Samples</p>
						  <a href="/assets/cws_files/product_reviews.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon4.png" alt="Cinque Terre" > 
						  <h3>Download</h3>
						  <p>Ebooks <br>Samples</p>
						  <a href="/assets/cws_files/e_book.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon5.png" alt="Cinque Terre" > 
						  <h3>Download</h3>
						  <p>Press Release Samples</p>
						  <a href="/assets/cws_files/press_eleases.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
			</div>
			
			

		</div>
	</div>
			
<!-- End OUR WRITING SAMPLES Section -->
<section class="enterpriseseoservicesfourthsec">
						<div class="container i-can-has-a-colored-thing">
							<h4>WHY HIRE US FOR CONTENT DEVELOPMENT? </h4>
							<h2> Features of Our Service</h2>
</section>
<!-- Start card Section -->
	<div class="container-fluid card-sec">
		<div class="container">
	
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">Be #1 on Google</h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/Be1onGoogle-img.webp" alt="Card image cap">
								<p class="card-text">Our top content writing service ensures you get high positions on popular search engines like Google. Our content writers create high quality, keyword-rich, SEO friendly and optimized content that gets noticed. Use our content writing to create website that Google will love. </p>
								
						  </div>
						</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">GET MORE TRAFFIC </h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/igniteyourcommunity-img.webp" alt="Card image cap">
								<p class="card-text">With high quality content that is targeted and optimized, you definitely get more traffic and visitors. This makes your site/blog more popular and you start earning. <br><br><br><br></p>
						  </div>
						</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">Convert More </h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/achieve-content-marketing-success-img.webp" alt="Card image cap">
								<p class="card-text"> With our engaging content and high traffic, you will definitely convert more. Not just this, you can also achieve successful content marketing with our amazing writing. <br><br><br><br></p>
								
						  </div>
						</div>
				</div>
				
			</div>


		</div>
	</div>
<!-- End card Section -->
<section class="enterpriseseoservicesfourthsec">
						<div class="container i-can-has-a-colored-thing">
							<h4>DELIVERING QUALITY EVERY TIME </h4>
							<h2>Benefits of hiring our service</h2>
	<!-- Start FEATURES AND BENEFITS Section -->
	<div class="container-fluid featuresandbenefits-sec" id="benefits">
		<div class="container">
		
			<span class="bottomLineImgStyle"></span>
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/expert-writing-icon.png" alt="Cinque Terre"> 
						  <h3> EXPERT WRITING </h3>
						  <p> Professional writers with many years of experience handle all types of content as per your requirements. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/revisionandediting-icon.png" alt="Cinque Terre"> 
						  <h3> REVISIONS AND EDITING </h3>
						  <p> Unlimited revisions are provided and content is submitted after proofreading from trained editors. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/originalcontent-icon.png" alt="Cinque Terre"> 
						  <h3> ORIGINAL CONTENT </h3>
						  <p> 100% original and SEO friendly content is what we offer. You can be sure of originality and high quality.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/keywordoptimazation-icon.png" alt="Cinque Terre"> 
						  <h3> KEYWORD OPTIMIZED </h3>
						  <p> Our content is keyword-optimized to make it SEO friendly. </p>
					</div>
				</div>
			</div>
			
				
		</div>
	</div>
	</section>
<!-- END FEATURES AND BENEFITS Section -->
	
	<section class="getintuchformsec" id="getintouch">
					<h2> Please Share Your 
						Content Requirements
					</h2>
					<form role="form" method="post" action="/seo_sending_form">
					{{ csrf_field() }}
					<div class="getintuchforminnersec">
						
							<div class="getintuchforminnerleftsec">
								<label for="r-form-1-first-name">Hey, I’m is</label>
								<input type="text" name="first-name" id="r-form-1-first-name" placeholder="name" class="textbox-cls">
							</div>
							<div class="getintuchforminnerrightsec">
									<label for="r-form-1-email">my website is</label>
									<input type="text" name="website" id="r-form-1-email" name="" placeholder="www.example.com">
							</div>
							<div class="getintuchforminnerleftsec">
									<label for="selfie">and, I’m looking for </label>
									<select id="r-form-1-first-name" name="Options" class="selectarrow">
										<span>&#xf107;</span>
											<option selected>&nbsp; Select </option>
<<<<<<< HEAD
											<option value="Blog Content">Blog Content</option>
											<option value="Website Content">Website Content</option>
											<option value="SEO Content">SEO Articles</option>
											<option value="ECommerce Content">eCommerce Site Content</option>
											<option value="Press Release Content">Press Release Content</option>
											<option value="eBook Content">eBook Content</option>
											<option value="Emails/Ads/Other Content	">Emails/Ads/Other Content</option>
									</select>										
=======
											<option value="Blog Content1">Blog Content</option>
											<option value="Website Content">Website Content</option>
											<option value="SEO Articles">SEO Articles</option>
											<option value="eCommerce Site Content">eCommerce Site Content</option>
											<option value="Press Release Content">Press Release Content</option>
											<option value="eBook Content">eBook Content</option>
											<option value="Emails/Ads/Other Content">Emails/Ads/Other Content</option>

									</select>
										
>>>>>>> 89dad1f2d667521bbac192e52e6cc4679d75f888
							</div>
							<div class="getintuchforminnerrightsec">
									<label for="r-form-1-last-name">Get in touch with me at </label>
									<input type="text" name="email" id="r-form-1-first-name" placeholder="email">
							</div>
							<div class="getintuchforminnerleftsec">
										<label for="r-form-1-email">or call  </label>
										<input type="text" name="phone" id="r-form-1-email"  placeholder="phone no.">
							</div>
							<div class="getintuchforminnerrightsec">
									<label>Any additional info </label>
<<<<<<< HEAD
									<input type="text" id="r-form-1-email" name="Add. Info" placeholder="brief about project">
=======
									<input type="text" id="r-form-1-email" name="Add. Info"  placeholder="brief about project">
>>>>>>> 89dad1f2d667521bbac192e52e6cc4679d75f888
							</div>
							<div class="getintuchforminnerbottomsec">
							<p style = "font-size:12px"> <input type="checkbox" id="r-form-1-email" name="" >  Subscribe For Important SEO Updates(We Will Never Spam Your Inbox) </p>
									
							</div>
							<div class="getintuchforminnerbottomsec">
                               {!! NoCaptcha::display(['data-size'=>"invisible"]) !!}
                            </div>
							<div class="getintuchforminnerbottomsec">
									<button type="submit"> Send Enquiry </button>
							</div>

						</div>
					</form>
</section>

				<section class="testimonial">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 d-none d-lg-block">
									<ol class="carousel-indicators tabs">
										<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-01-179x179.webp" class="img-fluid" alt="seoeaze testimonial 1">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="1">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-02-306x306.webp" class="img-fluid" alt="seoeaze testimonial 2">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="2">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-03-179x179.webp" class="img-fluid" alt="seoeaze testimonial 3">
											</figure>
										</li>
									</ol>
								</div>
								<div class="col-lg-6 d-flex justify-content-center align-items-center i-can-has-a-colored-thing">
									<div id="carouselExampleIndicators" data-interval="false" class="carousel slide" data-ride="carousel">
										<h3>Words From</h3>
										<h1><span class="highlight">Our Clients</span></h1>
										<h4>Our Valued Customers Believe In Us & 
												This Is What Keeps Us Going</h4>
										<div class="carousel-inner">
											<div class="carousel-item active">
												<div class="quote-wrapper">
													<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
															It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																												</p>
													<h3> Evrim Oralkan </h3>
													<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
										</div>
										<ol class="carousel-indicators indicators">
											<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
										</ol>
									</div>
								</div>
							</div>
						</div>
				</section>


<!-- New Start bannerFirst Section -->
<section class="frequentlyaskedquestionsec">
						<div class="container i-can-has-a-colored-thing">
								<h2> Frequently <br> <span class="highlight"> Asked Questions</span> </h2>
							<div class="row">

								<div class="col-lg-5 col-md-12 col-sm-12" style="margin-top: -50px;">
									<img src="assets/img/seo_packages_img/faqsleftsec.gif" class="img-fluid" alt=""/>
								</div>
								<div class="col-lg-7 col-md-12 col-sm-12">
									  <!-- start Frequently Asked Questions-->
									  			<button class="accordion"> Will the content be original?  </button>
												<div class="panel">
													<p>100% Guaranteed. At SeoEaze, we have a stringent 'no plagiarism policy' which assures our clients that our content writing services are reliable. We make use of premium plagiarism tools like Copyscape, ensuring delivery of only original high-quality content written by native writers.</p>
												</div>

												<button class="accordion"> How do I know that I will get top quality content? </button>
												<div class="panel">
													<p>In over a decade of our existence, SeoEaze content writing services have served over 1500 global clients who speak of our quality services. Our content offers high value and so almost all the clients are our long-time partners.</p>
												</div>
												
												<button class="accordion">What industries does SeoEaze cater to?</button>
												<div class="panel">
													<p>We have expert content writers who have experience and knowledge of various topics and subjects. Our native writers have in-depth knowledge of several industries spanning across IT, real estate, education, eCommerce, tourism, hospitality, healthcare and others. When you hire us, we match your project with the best-suited writers who are aware of terminologies and technicalities of your industry.</p>
												</div>
												
												<button class="accordion">Do you charge extra for revisions?</button>
												<div class="panel">
													<p>At SeoEaze, we ensure that there are no hidden costs that surprise our clients. Every cost will be detailed upfront when you hire us. For minor revisions and editing, there are no additional costs. Our editors make sure that you receive error-free and accurate copy in the right format. But if you need any revision done, we get at it as soon as we get your feedback.</p>
												</div>												
  										<!-- end Frequently Asked Questions-->

								</div>
							</div>

						</div>
				</section>
				<section class="clientsec">
						<h2> Some of Our Esteemed Clients </h2>
							<div class="clientinnersec">
								<div class="clientinnerleftsec">
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg1.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg2.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg3.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg4.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg5.webp" alt="client icon"/></a></li>
									</ul>
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg6.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg7.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg8.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg9.webp" alt="client icon"/></a></li>
									</ul>
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg10.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg11.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg12.webp" alt="client icon"/></a></li>
									</ul>
								</div>	
							</div>		
				</section>

				<section class="seventhsec">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 col-md-12 col-sm-12">
									<h3>We <i class="fas fa-heart hearticonsty"></i> <br> what we do </h3>
								</div>
								<div class="col-lg-6 col-md-12 col-sm-12">
									<h4>In a world of infinite possibilities, do not limit yourself.</h4>
									<div class="indibuttons">
									<a href="javascript:;" data-toggle="modal" data-target="#myModal">
											<button class="btn-hover color-1"> Let’s Talk  
												<span class="roundshapebutton roundshapearrow"> 
													<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
														<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
													</svg>
												</span>
											</button></a>
										</div>
								</div>
							</div>
						</div>
				</section>      


@endsection