@extends('layouts.master')

@section('title', 'Pay Per Click Management Services -FB, Adwords Campaign Mangement')
@section('meta' , "SeoEaze has Improved ROI on PPC Management upto 268%, with our Adwords Campaign Management & Facebook PPC Service, You get best results for your spending.")


@section('header')
@section('hreflangs')
    <link rel="canonical" href="https://www.seoeaze.com/ppc_management_service" />

@endsection
<!-- Start Breadcrumbs Schema -->
    <script type="application/ld+json">
    {
      "@context": "https://schema.org/", 
      "@type": "BreadcrumbList", 
      "itemListElement": [{
        "@type": "ListItem", 
        "position": 1, 
        "name": "Home",
        "item": "https://www.seoeaze.com"  
      },{
        "@type": "ListItem", 
        "position": 2, 
        "name": "Pay Per Click Management Service",
        "item": "https://www.seoeaze.com/ppc_management_service"  
      }]
    }
    </script>
	<!-- End Breadcrumbs Schema -->
	<!-- FAQ Schema Start -->
	<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What type of result can I expect from PPC Ads campaigns?","acceptedAnswer":[{"@type":"Answer","text":"Website traffic and conversions are the key performance indicators we look at. The answer depends on what your business goals are and how much traffic or conversion is expected."}]},{"@type":"Question","name":"How much traffic can I expect from PPC?","acceptedAnswer":[{"@type":"Answer","text":"The amount through PPC received every month will vary depending on:\n1. How effective your PPC campaigns are\n2. You PPC advertising budget"}]},{"@type":"Question","name":"Is advertising with Google expensive?","acceptedAnswer":[{"@type":"Answer","text":"Pay per click ad model is expensive than other methods of advertising and due to stiff competition to rank in Google search results, it can be expensive to advertise with the search giant. However, the traffic you receive will be high quality leading to more sales and conversion."}]}]}</script><!-- Generated by https://www.seoeaze.com/ -->
	<!-- FAQ Schema End -->
@show
@section('content')

<section class="ppc_management_service_sec">
					<div class="container">
							<div class="ppc_management_service_innersec">
								<h2><span class="highlight">Pay Per Click Advertising Service</span> </h2>
								<div class="ppc_management_service_subinnersec i-can-has-a-colored-thing">
										
										<h4> ATTRACT CUSTOMERS FAST WITH ADWORDS, BING AND FACEBOOK ADVERTISING</h4>
										<p> We, at SEOEaze, are adept at offering effective PPC services in Delhi NCR, managing successful Adwords, Facebook and Bing PPC campaigns. We can help you with creating the right advertisements, placing them and attracting people towards them through searches. With our PPC services, you can be sure of increased profits and more.</p>
										<div class="indibuttons pb-5">
										<a href="javascript:;" data-toggle="modal" data-target="#myModal">
											<button class="btn-hover color-2"> GET A QUOTE  
												<span class="roundshapebutton roundshapearrow"> 
													<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
														<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
													</svg>
												</span>
											</button></a>
										</div>
										<div class="indibuttons pb-5">
										<a href="#benefits">
											<button class="btn-hover color-1">  PPC BENEFITS 
												<span class="roundshapebutton roundshapearrow"> 
													<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
														<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
													</svg>
												</span>
											</button></a>
										</div>


								</div>
							</div>
					</div>

				</section>

				<section class="ppc_management_service_secndsec"> 
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-12">
							<h2>Pay Per Click Services <span> For Small/Medium/Large Enterprises</span></h2>
							<h6>WHAT WORKS FOR US</h6>
							<span class="ppc_management_service_secndsecboright"></span>
						</div>
						<div class="col-lg-8 col-md-8 col-sm-12">
								<p>
									SEOEaze has vast experience in PPC marketing and have run successful campaigns for over 1000 clients from more than 50+ countries. Being the most trusted advertising company, our dedicated PPC management team has run ads worth over $40M.
								</p>
						</div>
					</div>

				</section>

				<section class="ppc_management_service_thrdsec"> 
					<div class="row">
						<div class="col-lg-3 col-md-3 col-sm-12">
							<img src="assets/img/ppc/Pay-Per-Click-thirdsecimg.webp" class="img-fluid" alt="" />
							<span class="ppc_management_service_thrdsecboright"></span>
						</div>
						<div class="col-lg-9 col-md-9 col-sm-12">
								<h5>WHY SEOEAZE?</h5>
								<p>
									PPC advertising is a cost effective way to earn top positions at Google and Bing search results and on other digital platforms. With 97% population turning to online search and 75% people agreeing that paid ads make it easy to find information online, ads are becoming a true hit. So if you have time to invest in PPC management from a reputed PPC company in Delhi, you are at the right place.
									<br><br>After successfully creating your ads, we monitor them, working on all aspects that can affect the advertising campaign and ensure that the cost is kept at a minimum. At SEOEaze, we take your campaign forward with the aim to improve your ROI and gain more customers.
								</p>
						</div>
					</div>

				</section>

				<section class="ppc_management_service_forthsec"> 
					<h5>WHY SEOEAZE?</h5>
					<h2>HAVE A LOOK AT WHAT ALL IS INCLUDED 
						IN OUR PPC ADVERTISING SOLUTIONS:</h2>
						<ul>
							<li>
								<span>01-</span>
							</li>
							<li>
								<h3>SEARCH ADVERTISING</h3>
							</li>
							<li>
								<p>Set up the ads with right keywords and how many clicks you would like to pay for. With success, you can get more visitors and enjoy increase in traffic and sales.</p>
							</li>
						</ul>
						<ul>
							<li>
								<span>02-</span>
							</li>
							<li>
								<h3>DISPLAY ADVERTISING</h3>
							</li>
							<li>
								<p>If you already have an ad that you would like to put up, we are there with our display advertising. You can be sure of having your ad on the top sites and positions. This is good when you want to increase awareness or to retarget the audience.</p>
							</li>
						</ul>
						<ul>
							<li>
								<span>03-</span>
							</li>
							<li>
								<h3>REMARKETING & RETARGETING</h3>
							</li>
							<li>
								<p>If you already have some visitors from your site who haven’t purchased yet, use our display ads to get them back through retargeting. Such an ad will remind the visitor about your company, increasing the odds of converting them into leads.</p>
							</li>
						</ul>
						<ul>
							<li>
								<span>04-</span>
							</li>
							<li>
								<h3>PRODUCT LISTING ADS</h3>
							</li>
							<li>
								<p>When looking for ways to increase your ROI, product listing ads are not the best. But when the user is searching for some specific service, they will look at these ads. Thus you can use display ads to attract the viewers to click and visit your site.</p>
							</li>
						</ul>
				</section>



				<section  class="ppc_management_service_fifthsec">
					<h5>WHY SEOEAZE?</h5>
					<div class="tabs">

						<input type="radio" name="tabs" id="tab1" checked >
						<label for="tab1">
							<i class="fa fa-html5"></i><span>Our Bing & Google Ads PPC Process</span>
						</label>
				
						
				
				
						<div id="tab-content1" class="tab-content">
							<span class="ppcadwordandbingcls"> Adwords & Bing PPC Process </span>
							<div class="row m-0 p-3 bor-bottom bor-left">
			
								<div class="col-lg-8 col-md-8 col-sm-12 pt-4">
									<h3><b>PLANNING</b></h3><br>
									<p>We do complete planning at the first stage and analyze your site carefully. Our professionals then create or structure the PPC campaign as per your needs and structure the keywords and ad groups to have high quality score.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12">
									<figure>
										<img src="assets/img/ppc/ppctabsolutiontabimg1.webp" class="img-fluid" alt="PLANNING image" />
									</figure>
								</div>
							</div>
							<div class="row m-0 p-3 pt-5 bor-right">
								<div class="col-lg-8 col-md-8 col-sm-12">
									<h3><b>EXECUTION</b></h3><br>
									<p>After the planning process is done, we head towards the execution process where we start with creating an ad copy and filter your budget and bidding options. After that, dedicated PPC campaign strategies are used for those perfect ads.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12">
									<figure>
										<img src="assets/img/ppc/ppctabsolutiontabimg2.webp" class="img-fluid" alt="PLANNING image" />
									</figure>
								</div>
							</div>
							<div class="row m-0 p-3 pt-5 bor-top bor-left">
								<div class="col-lg-8 col-md-8 col-sm-12">
									<h3><b>MANAGING</b></h3><br>
									<p>The best thing about our PPC services is that we manage your campaigns on a regular basis. There is daily bid management, filtration of negative keywords, keyword management, removal of low quality keywords, ad creation, and addition of new keywords and preparation of the performance report. Our PPC specialists use tracking tools like Google Analytics to get the best solutions for our clients.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12">
									<figure>
										<img src="assets/img/ppc/ppctabsolutiontabimg3.webp" class="img-fluid" alt="PLANNING image" />
									</figure>
								</div>
							</div>
							<div class="row m-0 p-3 pt-5 bor-top bor-right bor-bottom">
								<div class="col-lg-8 col-md-8 col-sm-12">
									<h3><b>RESULTS</b></h3><br>
									<p>In the end, we offer guaranteed qualified clicks and results from your PPC campaign.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12">
									<figure>
										<img src="assets/img/ppc/ppcresult-img.webp" class="img-fluid" alt="PLANNING image" />
									</figure>
								</div>
							</div>
						</div> <!-- #tab-content1 -->
				
						<div id="tab-content2" class="tab-content">
							<div class="row m-0 p-3 bor-bottom bor-left">
			
								<div class="col-lg-8 col-md-8 col-sm-12 pt-4">
									<h3><b>ACCOUNT SET UP</b></h3><br>
									<p>We create your Facebook account and identify the right PPC campaigns. Accordingly, the campaign is set up and worked upon.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12">
									<figure>
										<img src="assets/img/ppc/ppc_account_setup.webp" class="img-fluid" alt="PLANNING image" />
									</figure>
								</div>
							</div>
							<div class="row m-0 p-3 pt-5 bor-right">
								<div class="col-lg-8 col-md-8 col-sm-12">
									<h3><b>AD CREATION</b></h3><br>
									<p>We ensure that we create the right ad for your business. We further ensure that the most useful audience is targeted.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12">
									<figure>
										<img src="assets/img/ppc/ppc_add_creation.webp" class="img-fluid" alt="PLANNING image" />
									</figure>
								</div>
							</div>
							<div class="row m-0 p-3 pt-5 bor-top bor-left">
								<div class="col-lg-8 col-md-8 col-sm-12">
									<h3><b>MANAGING</b></h3><br>
									<p>After the creation of an ad campaign, our work doesn’t stop there. We ensure that we monitor the progress of your ads and update the campaign as per the requirements.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12">
									<figure>
										<img src="assets/img/ppc/ppctabsolutiontabimg3.webp" class="img-fluid" alt="PLANNING image" />
									</figure>
								</div>
							</div>
							<div class="row m-0 p-3 pt-5 bor-top bor-right bor-bottom">
								<div class="col-lg-8 col-md-8 col-sm-12">
									<h3><b>REPORT AND FEEDBACK</b></h3><br>
									<p>We provide complete, detailed reports that include in depth analysis of your campaign so that you get a clear picture of the results. We also take feedback from our clients and work upon them for better PPC solutions.</p>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-12">
									<figure>
										<img src="assets/img/ppc/ppc_reportandfeedback.webp" class="img-fluid" alt="PLANNING image" />
									</figure>
								</div>
							</div>
									
						</div> <!-- #tab-content2 -->
				
				
					</div> <!-- .tabs -->
				</section>



				

				<section  class="ppc_management_service_sixthsec" id="benefits">
				<h2> Benefits of  <span class="highlight"> Our PPC Management Service</span></h2>
					<div class="row">
						<div class="col-lg-3 col-md-3 col-sm-12 ">
							<div class="ppc_management_service_sixthinnsec bor-bottom">
								<div class="ppc_management_service_sixthsubinnsec bor-right">
									<h3>INCREASED PROFIT</h3>
									<p>Our PPC campaigns are optimized in real-time to offer highest ROI. See instant increase in profits and brand exposure with our campaigns.</p>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-12">
							<div class="ppc_management_service_sixthinnsec bor-bottom">
								<div class="ppc_management_service_sixthsubinnsec bor-right">
									<h3>GREAT EXPERIENCE</h3>
									<p>With over a decade of experience in the industry, we have nurtured thousands of successful ad campaigns for our clients.</p>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-12">
							<div class="ppc_management_service_sixthinnsec bor-bottom">
								<div class="ppc_management_service_sixthsubinnsec bor-right">
									<h3>REDUCED CPC</h3>
									<p>Our PPC experts help in reducing the overall CPC i.e. cost per conversion to improve quality score level.</p>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-12">
							<div class="ppc_management_service_sixthinnsec bor-bottom">
								<div class="ppc_management_service_sixthsubinnsec">
									<h3>TRANSPARENCY</h3>
									<p>We believe in providing clean and clear services, keeping complete transparency of what we offer. You can easily track</p>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-12">
							<div class="ppc_management_service_sixthinnsec">
								<div class="ppc_management_service_sixthsubinnsec bor-right">
									<h3>PROFESSIONAL APPROACH</h3>
									<p>We believe in providing clean and clear services, keeping complete transparency of what we offer. You can easily track</p>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-12">
							<div class="ppc_management_service_sixthinnsec">
								<div class="ppc_management_service_sixthsubinnsec bor-right">
									<h3>IMPROVED TRAFFIC</h3>
									<p>We believe in providing clean and clear services, keeping complete transparency of what we offer. You can easily track</p>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-12">
							<div class="ppc_management_service_sixthinnsec">
								<div class="ppc_management_service_sixthsubinnsec bor-right">
									<h3>REACH RIGHT AUDIENCE</h3>
									<p>We believe in providing clean and clear services, keeping complete transparency of what we offer. You can easily track</p>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-3 col-sm-12">
							<div class="ppc_management_service_sixthinnsec">
								<div class="ppc_management_service_sixthsubinnsec">
									<h3>BRAND RECOGNITION</h3>
									<p>We believe in providing clean and clear services, keeping complete transparency of what we offer. You can easily track</p>
								</div>
							</div>
						</div>
					</div>
				</section>

				<section class="getintuchformsec">
					<h2> 
						Fill Us In About 
						Your PPC Requirement
					</h2>
					<form role="form" method="post" action="/seo_sending_form">
					{{ csrf_field() }}
					<div class="getintuchforminnersec">
						
							<div class="getintuchforminnerleftsec">
								<label for="r-form-1-first-name">Hey, I’m is</label>
								<input type="text" name="first-name" id="r-form-1-first-name" placeholder="name" class="textbox-cls">
							</div>
							<div class="getintuchforminnerrightsec">
									<label for="r-form-1-email">my website is</label>
									<input type="text" name="website" id="r-form-1-email" name="" placeholder="www.example.com">
							</div>
							<div class="getintuchforminnerleftsec">
									<label for="selfie">and, I’m looking for </label>
									<select id="r-form-1-first-name" name="Options" class="selectarrow">
										<span>&#xf107;</span>
											<option selected>&nbsp; Select </option>
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> df52a5487d6e3ee5ffa5291f2eccb608be2e4de6
											<option value="Google Ads">Google Ads</option>
											<option value="FB/Insta Ads">FB/Instagrm Ads</option>
											<option value="LinkedIn Ads">Linkdin Ads</option>
											<option value="Other Ads">Other Ads</option>
<<<<<<< HEAD
=======
											<option value="4-Complete Performance Campaign">Complete Performance Management Campaign</option>
											<option value="1-Google Ads">Google Management</option>
											<option value="2-FB/Insta Ads">FB/Instagrm Ads</option>
											<option value="3-Linkdin Ads">Linkdin Ads</option>
											
>>>>>>> 89dad1f2d667521bbac192e52e6cc4679d75f888
=======
>>>>>>> df52a5487d6e3ee5ffa5291f2eccb608be2e4de6
									</select>
										
							</div>
							<div class="getintuchforminnerrightsec">
									<label for="r-form-1-last-name">Get in touch with me at </label>
									<input type="text" name="email" id="r-form-1-first-name" placeholder="email">
							</div>
							<div class="getintuchforminnerleftsec">
										<label for="r-form-1-email">or call  </label>
										<input type="text" name="phone" id="r-form-1-email"  placeholder="phone no.">
							</div>
							<div class="getintuchforminnerrightsec">
									<label>Any additional info </label>
<<<<<<< HEAD
<<<<<<< HEAD
									<input type="text" id="r-form-1-email" name="Add. Info" placeholder="brief about project">
=======
									<input type="text" id="r-form-1-email" name="Add. Info"  placeholder="brief about project">
>>>>>>> 89dad1f2d667521bbac192e52e6cc4679d75f888
=======
									<input type="text" id="r-form-1-email" name="Add. Info" placeholder="brief about project">
>>>>>>> df52a5487d6e3ee5ffa5291f2eccb608be2e4de6
							</div>
							<div class="getintuchforminnerbottomsec">
							<p style = "font-size:12px"> <input type="checkbox" id="r-form-1-email" name="" >  Subscribe For Important Updates & Offers(We Will Never Spam Your Inbox) </p>
									
							</div>
							<div class="getintuchforminnerbottomsec">
                                {!! NoCaptcha::display(['data-size'=>"invisible"]) !!}
                            </div>
							<div class="getintuchforminnerbottomsec">
									<button type="submit"> Send Enquiry </button>
							</div>

						</div>
					</form>
				</section>
				<section class="testimonial">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 d-none d-lg-block">
									<ol class="carousel-indicators tabs">
										<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-01-179x179.webp" class="img-fluid" alt="seoeaze testimonial 1">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="1">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-02-306x306.webp" class="img-fluid" alt="seoeaze testimonial 2">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="2">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-03-179x179.webp" class="img-fluid" alt="seoeaze testimonial 3">
											</figure>
										</li>
									</ol>
								</div>
								<div class="col-lg-6 d-flex justify-content-center align-items-center i-can-has-a-colored-thing">
									<div id="carouselExampleIndicators" data-interval="false" class="carousel slide" data-ride="carousel">
										<h3>Words From</h3>
										<h1><span class="highlight">Our Clients</span></h1>
										<h4>Our Valued Customers Believe In Us & 
												This Is What Keeps Us Going</h4>
										<div class="carousel-inner">
											<div class="carousel-item active">
												<div class="quote-wrapper">
													<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
															It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																												</p>
													<h3> Evrim Oralkan </h3>
													<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
										</div>
										<ol class="carousel-indicators indicators">
											<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
										</ol>
									</div>
								</div>
							</div>
						</div>
				</section>
				<section class="frequentlyaskedquestionsec">
						<div class="container i-can-has-a-colored-thing">
								<h2> Frequently <br> <span class="highlight"> Asked Questions</span> </h2>
							<div class="row">

								<div class="col-lg-5 col-md-12 col-sm-12" style="margin-top: -50px;">
									<img src="assets/img/seo_packages_img/faqsleftsec.gif" class="img-fluid" alt=""/>
								</div>
								<div class="col-lg-7 col-md-12 col-sm-12">
									 
									  			<button class="accordion">What type of result can I expect from PPC Ads campaigns?</button>
												<div class="panel">
													<p>Website traffic and conversions are the key performance indicators we look at. The answer depends on what your business goals are and how much traffic or conversion is expected.</p>
												</div>

												<button class="accordion">How much traffic can I expect from PPC?</button>
												<div class="panel">
													<p>The amount through PPC received every month will vary depending on:<br>
														How effective your PPC campaigns are<br>
														You PPC advertising budget</p>
												</div>
												
												<button class="accordion">Is advertising with Google expensive?</button>
												<div class="panel">
													<p>Pay per click ad model is expensive than other methods of advertising and due to stiff competition to rank in Google search results, it can be expensive to advertise with the search giant. However, the traffic you receive will be high quality leading to more sales and conversion.</p>
												</div>
												
												
  										

								</div>
							</div>

						</div>
				</section>

				<section class="clientsec">
						<h2> Some of Our Esteemed Clients </h2>
							<div class="clientinnersec">
								<div class="clientinnerleftsec">
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg1.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg2.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg3.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg4.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg5.webp" alt="client icon"/></a></li>
									</ul>
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg6.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg7.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg8.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg9.webp" alt="client icon"/></a></li>
									</ul>
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg10.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg11.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg12.webp" alt="client icon"/></a></li>
									</ul>
								</div>	
							</div>		
				</section>

				

				<section class="seventhsec">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 col-md-12 col-sm-12">
									<h3>We <i class="fas fa-heart hearticonsty"></i> <br> what we do </h3>
								</div>
								<div class="col-lg-6 col-md-12 col-sm-12">
									<h4>In a world of infinite possibilities, do not limit yourself.</h4>
									<div class="indibuttons">
									<a href="javascript:;" data-toggle="modal" data-target="#myModal">
											<button class="btn-hover color-1"> Let’s Talk  
												<span class="roundshapebutton roundshapearrow"> 
													<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
														<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
													</svg>
												</span>
											</button></a>
										</div>
								</div>
							</div>
						</div>
				</section> 
@endsection