@extends('layouts.master')

@section('title', 'Pay Per Click Management Services -FB, Adwords Campaign Mangement')
@section('meta' , "SeoEaze has Improved ROI on PPC Management upto 268%, with our Adwords Campaign Management & Facebook PPC Service, You get best results for your spending.")


@section('header')
@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.com/ppc_management_service" hreflang="en-us" />
    <link rel="alternate" href="https://www.seoeaze.in/ppc_management_service" hreflang="en-in" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/ppc_management_service" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/ppc_management_service" hreflang="x-default" />
@endsection
<!-- Start Breadcrumbs Schema -->
    <script type="application/ld+json">
    {
      "@context": "https://schema.org/", 
      "@type": "BreadcrumbList", 
      "itemListElement": [{
        "@type": "ListItem", 
        "position": 1, 
        "name": "Home",
        "item": "https://www.seoeaze.com"  
      },{
        "@type": "ListItem", 
        "position": 2, 
        "name": "Pay Per Click Management Service",
        "item": "https://www.seoeaze.com/ppc_management_service"  
      }]
    }
    </script>
	<!-- End Breadcrumbs Schema -->
	<!-- FAQ Schema Start -->
	<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What type of result can I expect?","acceptedAnswer":[{"@type":"Answer","text":"Website traffic and conversions are the key performance indicators we look at. The answer depends on what your business goals are and how much traffic or conversion is expected."}]},{"@type":"Question","name":"How much traffic can I expect?","acceptedAnswer":[{"@type":"Answer","text":"The amount through PPC received every month will vary depending on:\n1. How effective your PPC campaigns are\n2. You PPC advertising budget"}]},{"@type":"Question","name":"Is advertising with Google expensive?","acceptedAnswer":[{"@type":"Answer","text":"Pay per click ad model is expensive than other methods of advertising and due to stiff competition to rank in Google search results, it can be expensive to advertise with the search giant. However, the traffic you receive will be high quality leading to more sales and conversion."}]}]}</script><!-- Generated by https://www.seoeaze.com/ -->
	<!-- FAQ Schema End -->
@show
@section('content')
	<script>
        $(function () {
                $('a[href="#tab_name1"]').tab('show');
            }
        )
	</script>
	<!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-7 col-md-7 col-sm-12 header-video-sec-inner-leftsec">

									<h1>PPC Services To Make Your Sales Soar </h1>
									
									<p class="mb-5">
									    SeoEaze is a leading PPC management service that offers complete pay per click marketing solutions for businesses. Whether you want to boost traffic to your website or increase conversions or both, our PPC management services are available to help you achieve your goals.
									</p>
									<h2> 10,000+ Successful PPC Campaigns Delivered to Over 1500+ Clients </h2>

										
									<span class="mt-5">  
									<a href="#" data-toggle="modal" data-target="#">
										<button class="button1">Ready To Grow Your Business? </button>
									</a> 
									<a href="#ppcbenefits">
										<button class="button2"> Request Your Proposal Now</button>
									</a>
									</span>
									<p class="pt-5"><figure><img src="assets/img/ppc/bingandgooglepartnerimg.png" alt=""></figure></p>
				  			</div>

				  			<div class="col-lg-5 col-md-5 col-sm-12 header-video-sec-inner-rightform-sec">
				  				
							 
								<div class="header-form-sec">
									<h4> Start With <span> Free</span> PPC Audit </h4>
									<span class="bottomLineImgStyle2"></span>
									<form role="form" method="post" action="/ppc_sending_form">
									    {{ csrf_field() }}
									    <label class="sr-only" for="r-form-1-first-name">Name</label>
    									<input type="text" name="first-name" id="r-form-1-first-name" placeholder="Name:" class="textbox-cls">
    									<label class="sr-only" for="r-form-1-last-name">E-mail</label>
    									<input type="text" name="email" id="r-form-1-first-name" placeholder="E-mail:" class="textbox-cls">
    									<label class="sr-only" for="r-form-1-email">Phone</label>
    									<input type="text" name="phone" id="r-form-1-email" placeholder="Phone:" class="textbox-cls">
    									<label class="sr-only" for="r-form-1-email">Website</label>
    									<input type="text" name="website" id="r-form-1-email" placeholder="Website:" class="textbox-cls">
    									<label class="sr-only" for="r-form-1-email">Title</label>
    									<input type="text" name="title" id="r-form-1-email" placeholder="Title:" class="textbox-cls">
    									
    									<button type="submit">Submit Request</button>

									</form>
									<p class="form-pcls"> We Will Never Spam Your Inbox </p>
								</div>
				  			</div>
					</div>
			  	</div>
				
			
			</div>
			<!-- Vedio Content Section End -->
	</main>
			  
<!-- slider area bar end-->

<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Pay Per Click Management Service </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->


<!-- Start Pay-Per-Click Management That Works sec -->

<div class="container-fluid blogmanagementservice-sec bgcolor1">
		<div class="container">
			<h2>Grow Business With #1 Ranked PPC Management Agency</h2>
			<span class="bottomLineImgStyle"></span>
            <div class="row mt-5">
						<div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
							<div class="box-sec">								
        	                    <p>
            					Pay per click marketing is one of the best ways for businesses to reach the most qualified audience, beating the competition and gaining an edge. SeoEaze can deliver custom PPC campaigns to help businesses of all sizes increase both revenue as well as conversion.<br><br>
                                PPC services we offer are backed by experts who consistently deliver compelling messages with a combination of right keywords, site experience and ad messaging to produce results. It doesn’t end here; we also test and analyze every aspect of the campaigns we run and rigorously optimize it for maximum ROI.<br><br>
                                The combination of <mark> PPC MANAGEMENT + OPTIMIZATION + ANALYTICS </mark> is what makes us the best in the industry.
            					</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
							<div class="box-sec">
								 <figure class="p-5 mt-5"><img src="assets/img/ppc/Pay-Per-Click-management-that-works-img.png" alt="Pay per click marketing" class="img-flude"></figure>
							</div>
						</div>
						<hr>
					</div>
		</div>
</div>

<!-- End Pay-Per-Click Management That Works sec-->


<!-- Start Award-Winning Services -->

<div class="container-fluid awardwinningservices-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-10 col-md-10 col-sm-12 offset-lg-1 offset-md-1">
					<div class="awardwinningservices-innersec">
							<h3 class="whitecolor"> AWARDS & ACHIEVEMENTS  </h3>
						    <span class="bottomLineImgStyle"></span>
							<figure class="mt-5"><img src="assets/img/ppc/awardwinningimg.png" alt=""></figure>
					</div>
				</div>
			</div>
	</div>
</div>

<!-- End Award-Winning Services -->

<!-- Start PPC campaigns sec -->

<div class="container-fluid ppccampaigns-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-4 col-md-4 col-sm-12 offset-lg-1 offset-md-1">
					<div class="ppccampaigns-innersec">
							<h3> PPC campaigns </h3>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 offset-lg-1 offset-md-1">
					<div class="ppccampaigns-innersec">
							<button class="button3"> Get My Free PPC Proposal </button>
					</div>
				</div>
			</div>
	</div>
</div>


<!-- End PPC campaigns sec -->

<!-- Start WHY SEOEAZE FOR YOUR PPC MANAGEMENT SERVICES sec -->

<div class="container-fluid whyseoeazeppcmgmtser-sec">

		<div class="container">
			<h3> Why Invest in Pay Per Click Advertising? </h3>
			<span class="bottomLineImgStyle"></span>
		
			<div class="row">
			<div class="col-lg-4 col-md-4 col-sm-12 offset-lg-1 offset-md-1 mx-auto d-block">
				<figure><img src="assets/img/ppc/whyseoeazeforyourppcmanagementservices.png" alt=""></figure>
			</div>

				<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
					<div class="whyseoeazeppcmgmtser-innersec">

						<p>PPC services are not just a part of a digital marketing strategy that businesses use to increase sales but it has a lot more to offer. According to SEMrush:</p><br>
                        <p><strong>3,933</strong>&nbsp;out of<strong> Inc. 5000 companies </strong>spend on PPC</p><br>
                        <p><strong>$20,404.61</strong>&nbsp;on an average is spent by each company on PPC</p><br>
                        <p>But figures get a lot more interesting when we look at revenue, its mind boggling.</p><br>
                        <p>GoDaddy spends<strong> $5,262,098</strong> on PPC to earn a revenue of<strong> $ 1,100,000,000</strong></p><br>
                        <p>Appriver spends <strong>$460,800 </strong>on PPC to earn a revenue of <strong>$43,600,000</strong></p><br>
                        <p>Coupons.com spends<strong> $952,965 </strong>on PPC to earn a revenue of<strong> $178,200,000</strong></p><br>
                        <p>The number speaks for themselves, no other medium of marketing can offer such amazing ROI; almost faster than pay per click advertising.&nbsp;&nbsp;</p><br>
						</p>
					</div>
				</div>

			</div>

		</div>
</div>


<!-- End WHY SEOEAZE FOR YOUR PPC MANAGEMENT SERVICES sec -->

<!-- 30 days money back guarantee sec -->

<div class="container-fluid moneyback-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 ">
					<figure class="pt-3"><img src="assets/img/seopackages/30daystampimg.png"> </figure>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 p-5">
					<h3 class="pt-5"> 30 DAYS MONEY BACK GUARANTEE  </h3>
					<p>
						We offer a whooping 30 days money back guarantee. So if you are not happy with our results, we can return our fee! 
					</p>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure><img src="assets/img/seopackages/30daysthumsupimg.png"> </figure>
				</div>
			</div>
		</div>
	</div>


<!-- End 30 days money back guarantee sec  -->

<!-- Start SeoEaze’s Dedicated SEO Solutions sec-->

<div class="container-fluid dedicatedseosolutions-thirdsec bgcolor2">
        <div class="container">
            <h2>Our PPC Management Process</h2>
			<span class="bottomLineImgStyle"></span>
                    <div class="row mt-5">
                        <div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
                            <div class="box-sec">                               
                                <h3>Assign Advertising Specialist </h3>
                                    <p>
                						We start with assigning PPC advertising specialist to manage your ad campaign. Highly trained professionals with years of AdWords experience, first learn about the goals of your business.
                					</p>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
                            <div class="box-sec">
                                 <img src="assets/img/ppc/our_ppc_management_process_img1.png" alt="UNIQUE APPROACH FOR EACH SEO PLAN " class="img-flude"> 
                            </div>
                        </div>
                        <hr>
                    </div>
                    <div class="row mt-5">
                        <div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
                            <div class="box-sec">                               
                                <h3>Identify Keyword Opportunities </h3>
                                    <p>
                						Spending on the most cost-effective keywords is most important and so we invest in thorough research to find the most valuable opportunities for your business.
                					</p>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
                            <div class="box-sec">
                                 <img src="assets/img/ppc/our_ppc_management_process_img2.png" alt="UNIQUE APPROACH FOR EACH SEO PLAN " class="img-flude"> 
                            </div>
                        </div>
                        <hr>
                    </div>
                    <div class="row mt-5">
                        <div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
                            <div class="box-sec">                               
                                <h3>Analyze Competition</h3>
                                    <p>
                						It is important to know what your competitors are up to and what advertising tactics are working for them; so we can develop an even smarter approach for your PPC campaign.
                					</p>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
                            <div class="box-sec">
                                 <img src="assets/img/ppc/our_ppc_management_process_img3.png" alt="UNIQUE APPROACH FOR EACH SEO PLAN " class="img-flude"> 
                            </div>
                        </div>
                        <hr>
                    </div>
                    <div class="row mt-5">
                        <div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
                            <div class="box-sec">                               
                                <h3>Ad Creation</h3>
                                    <p>
                					    At this stage, we develop effective ads with the right headlines, copy and target keywords. We also do A/B split test the ads to identify which are the high-performing ones.
                					</p>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
                            <div class="box-sec">
                                 <img src="assets/img/ppc/our_ppc_management_process_img4.png" alt="UNIQUE APPROACH FOR EACH SEO PLAN " class="img-flude"> 
                            </div>
                        </div>
                        <hr>
                    </div>
                    <div class="row mt-5">
                        <div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
                            <div class="box-sec">                               
                                <h3>Monitor Ads and Optimize</h3>
                                    <p>
                						Identifying the low-performing areas of a PPC ad campaign once it is live is important to act immediately and save your investment from depleting.
                					</p>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
                            <div class="box-sec">
                                 <img src="assets/img/ppc/our_ppc_management_process_img5.png" alt="UNIQUE APPROACH FOR EACH SEO PLAN " class="img-flude"> 
                            </div>
                        </div>
                        <hr>
                    </div>
                    <div class="row mt-5">
                        <div class="col-lg-8 col-md-8 col-sm-12 mx-auto d-block">
                            <div class="box-sec">                               
                                <h3>Reporting and Communication</h3>
                                    <p>
                					    Clients must know how their PPC campaigns are performing and for this we share a detailed monthly report so that they are aware of the ROI.
                					</p>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
                            <div class="box-sec">
                                 <img src="assets/img/ppc/our_ppc_management_process_img6.png" alt="UNIQUE APPROACH FOR EACH SEO PLAN " class="img-flude"> 
                            </div>
                        </div>
                        <hr>
                    </div>
            </div>
        </div>

<!-- End SeoEaze’s Dedicated SEO Solutions sec -->


<!-- Start Call Us section  -->

<div class="container-fluid callus-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure class="callusleftsec"><img src="assets/img/linkbulding/callus-iconimg.png"> </figure>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12">
					<p class="callusmiddlesec">
						LET US SUGGEST YOU THE BEST PPC PROPOSAL FOR YOU<br>
				        Call Us To Discuss Now On <span> 844-736-3293</span>  
					</p>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12">
					<figure class="callusrightsec"><img src="assets/img/linkbulding/callus-girlimg.png"> </figure>
				</div>
			</div>
		</div>
	</div>

<!-- End Call Us section -->

<!-- Start FAQS RELATED TO CONTENT WRITING SERVICE Section -->

<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
                        <h2>Frequently Asked Questions </h2>
            			<span class="bottomLineImgStyle"></span>
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> 1. What type of result can I expect? </a>
									</div>
									<div id="collapseOne" class="card-body collapse show" data-parent="#accordion">
										<div class="card-body">Website traffic and conversions are the key performance indicators we look at. The answer depends on what your business goals are and how much traffic or conversion is expected.</div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> 2. How much traffic can I expect? </a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<div class="card-body">
                                        The amount through PPC received every month will vary depending on:
                                        <ul>
                                            <li>1.	How effective your PPC campaigns are</li>
                                            <li>2.	You PPC advertising budget</li>
                                        </ul>
                                        </div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> 3. Is advertising with Google expensive? </a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">Pay per click ad model is expensive than other methods of advertising and due to stiff competition to rank in Google search results, it can be expensive to advertise with the search giant. However, the traffic you receive will be high quality, leading to more sales and conversion.</div>
									</div>
									
                                    
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
</div>
<!-- End FAQS RELATED TO Section -->
<!-- New Start bannerFirst Section -->
    <section class="happyclientsec">
                      <div class="container text-center">
                    
                        <div class="row">
                           <div class="col-lg-12 col-md-12">
                            <ul>
                              <li><img src="assets/img/clientcomicon/icon1.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon2.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon3.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon4.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon5.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon6.jpg" alt=""></li>
                              <div class="hcheader"><h2> Our Clients | Our Strength </h2><h4> Some of our esteemed customers </h4></div>
                              <li><img src="assets/img/clientcomicon/icon7.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon8.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon9.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon10.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon11.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon12.jpg" alt=""></li>
                            </ul>
                          </div>
                        </div>
                        
                      </div>
    </section>
<!-- New End bannerFirst Section -->
<!-- Start customers think about us Section -->
	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>Words From Our Clients </h2>
			<h3>Our Valued Customers Believe In Us & This Is What Keeps Us Going </h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Angus Walls</h3>
													<h4> Xlife Enterprices</h4>
													
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Angus Walls</h3>
													<h4> Xlife Enterprices</h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		

	</div>

 <!-- End customers think about us Section  -->

<!-- Start SOME HAPPY CLIENTS  Section --> 
<div class="container-fluid featureandclient-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="featureandclient-innersec">
							<h3 class="whitecolor"> OUR ACHIEVEMENTS: OUR PRIDE </h3>
						    <span class="bottomLineImgStyle"></span>
						    <p> 
								</p><ul>
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon1.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon2.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon3.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon4.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon5.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon6.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon7.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon8.png"></a></li>
									
								</ul>	
							<p></p>
					</div>
				</div>
			</div>
	</div>
</div>
<!-- End SOME HAPPY CLIENTS  Section -->            
@endsection