@extends('layouts.master')

@section('title', 'SEO Packages- Monthly SEO Packages at Affordable Pricing')
@section('meta', 'SeoEaze Brings Result Oriented Best SEO Packages. Our affordable SEO Pricing Starts @ $299. Enjoy Monthly SEO Packages with result assurance. ')

<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "LocalBusiness",
  "@id": "https://www.seoeaze.com/seo_packages",
  "name": "SeoEaze",
  "image": "https://www.seoeaze.com/assets/img/logo-small.png",
  "sameAs": "https://www.seoeaze.com/seo_packages",
  
  "priceRange": "$$$",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": " 10685-B Hazelhurst Dr. #19976",
    "addressLocality": "Houston",
    "addressRegion": "TX",
    "postalCode": "77043",
    "addressCountry": "US"
  },
  "telephone": "+1844-736-3293",
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": 29.796706,
    "longitude": -95.5636957
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.7",
    "bestRating": "5",
    "worstRating": "1",
    "ratingCount": "126"
  },
  "review": {
    "@type": "Review",
    "url": "https://www.seoeaze.com/seo_packages",
    "author": {
      "@type": "Person",
      "name": "Anand Maheshawari",
      "sameAs": ""
    },
    "publisher": {
      "@type": "Organization",
      "name": "B4U",
      "sameAs": "https://www.b4uindia.com/"
    },
    "datePublished": "2018-06-14T20:00",
    "description": "SEO Helped us Rank High for our Hosting related keywords in India with their SEO Services & we got 300% traffic boost.",
    "inLanguage": "en",
    "reviewRating": {
      "@type": "Rating",
      "worstRating": 1,
      "bestRating": 5,
      "ratingValue": 4.7
    }
  }
}
</script>
<script type="application/ld+json">
{
"@context": "https://schema.org",
"@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "name": "Home",
    "item": "https://www.seoeaze.com/"
  },
{
    "@type": "ListItem",
    "position": 2,
    "name": "SEO Packages",
    "item": "https://www.seoeaze.com/seo_packages"
  }]
}
</script>

<!-- FAQ schema start -->
<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What are your SEO Strategy & SEO Packages?","acceptedAnswer":[{"@type":"Answer","text":"Our SEO strategy & packages are a complete SEO bundle which include the details of SEO tasks we provide as an SEO agency and the price we charge. The cost of our SEO plans ranges from $250 to $1000. The prices of our packages are completely dependent on the niche of the website and the competition against the business of the client.\n"}]},{"@type":"Question","name":"What all is included in SEO Services?","acceptedAnswer":[{"@type":"Answer","text":"Our Monthly SEO Plans take care of your technical SEO related issues including On-page SEO, Off-Page SEO and content marketing.\n"}]},{"@type":"Question","name":"Are custom monthly SEO packages available?","acceptedAnswer":[{"@type":"Answer","text":"Yes, we can build custom SEO plans for you. Please get in touch with us so that we can understand your requirements.\n"}]},{"@type":"Question","name":"What is the minimum contract period for these SEO Plans?","acceptedAnswer":[{"@type":"Answer","text":"6 months. Based on our experience, in most cases, it takes a good 5-6 months to achieve rankings on competitive keywords and to start driving a significant volume of targeted traffic. If you are serious about SEO, you should be prepared to continue for at least 6 months. If you need quick results, you can go with 1 month plans or check out our PPC plans. \n"}]},{"@type":"Question","name":"Do you use White Hat or Black Hat SEO techniques?","acceptedAnswer":[{"@type":"Answer","text":"We use only white hat SEO techniques to offer the best SEO services. We are not into any type of illegal or black hat working.\n"}]},{"@type":"Question","name":"Who will be working on my SEO campaign?","acceptedAnswer":[{"@type":"Answer","text":"Our trained and experienced team of SEO professionals will work on your campaign, providing the best SEO solutions. There will even be a dedicated manager for your project who will be assisting you with everything you need to know.\n"}]},{"@type":"Question","name":"How long does it take to show SEO results for Google ranking?","acceptedAnswer":[{"@type":"Answer","text":"If you already have an established website, it will not take long to rank high. But if you have a relatively new site, it will take about 5-6 months to see your business in top 100 rankings.\n\n"}]}]}</script><!-- Generated by https://www.ranklogs.com/ -->
<!-- FAQ schema end -->
@section('header')

@show

@section('content')

<section class="seo_packagehsec">
					<div class="container">
							<div class="seo_packageinnerleftsec i-can-has-a-colored-thing">
									<h2><span class="highlight">SEO Strategy</span> That Is Absolute Global Standard </h2>
									<p>
										SeoEaze delivers unparalleled SEO Services that goes 
										beyond ranking your website on page #1. We develop 
										true digital strategy to drive sales, 
										leads and grow your business even for the most 
										competitive keywords.
									</p>
									<img src="assets/img/seo_packages_img/seo_packages_headersecondbgimg.webp" class="disbloc" alt=""/>
							</div>
						</div>

				</section>


				
				<section class="affordableseobillingmodelsec">
					<div class="container">
						<div class="row">
							<div class="col-lg-12 col-md-12 col-sm-12 affordableseobillingmodelheadersec i-can-has-a-colored-thing">
								<h2> <span class="highlight">Affordable SEO Billing</span> Models
									that Work!</h2>
									<p>At SEOEAZE, We have a billing model for every client based 
										on their budget and project size</p>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-6 col-md-12 col-sm-12">
								<div class="affordableseobillingmodelinnersec i-can-has-a-colored-thing">
									<figure><img src="assets/img/seo_packages_img/p_img.png" alt=""/></figure>
										<h4><span class="highlight">PROJECT-BASED SEO</span></h4>
										<p>Project-based SEO packages have a clear 
										beginning and end timeline that’s set 
										before a project begins. This type of SEO is 
										the most common in technical SEO analysis 
										and on-site audits. Project-based 
										SEO package is more affordable because it 
										requires less ongoing maintenance as 
										compared to link building and content.</p>
								</div>
							</div>
							<div class="col-lg-6 col-md-12 col-sm-12">
									<div class="affordableseobillingmodelinnersec i-can-has-a-colored-thing">
											<figure><img src="assets/img/seo_packages_img/h_img.png" alt=""/></figure>
											<h4><span class="highlight">HOURLY SEO</span></h4>
											<p>Hourly SEO consulting is our specialization 
													as our SEO consultants help businesses 
													of all sizes to build a digital marketing and 
													SEO strategy that they can execute 
													internally. Based on the extent of your 
													requirement and kind of consultation you 
													need, hourly SEO can be best suited for 
													people with such requirements.</p>
									</div>
							</div>

								<div class="col-lg-6 col-md-12 col-sm-12 affordableseobillingmodelinnerbottommartsec">
										<div class="affordableseobillingmodelinnerbottomsec i-can-has-a-colored-thing">
												<figure><img src="assets/img/seo_packages_img/r_img.png" alt=""/></figure>
												<h4><span class="highlight"> RETAINER-BASED SEO </span></h4>
												<p>The most common SEO pricing models, 
														retainer-based SEO package is our most 
														affordable offering.  We enter into an 
														agreement with the client to pay us a 
														monthly fee for a set list of SEO 
														deliverables. SeoEaze’s retainer-based 
														affordable SEO packages have helped over 
														50,000 businesses so far to lead in SERPs.</p>
										</div>
								</div>
							</div>
							<p> SEO packages don’t necessarily need to be over the budget when the deliverables can be customized to include strategies and methods that are most viable for your business. What makes SeoEaze’s SEO services package so affordable is the bottom-up approach towards pricing. We first take your budget then indulge into research and finally based on the data we get, tailor a strategy that makes sense to your business.</p>
							<p> We are a cost-effective and result-oriented SEO agency, which is why our SEO packages are not just to show off but to get real results. Our monthly SEO packages are created by experts who ensure that you get the best value for your money.</p>
					</div>
				</section>
				<section class="getintuchformsec">
					<h2> 
		
						Fill Us In About 
						Your Requirement
					</h2>
					<form role="form" method="post" action="/seo_sending_form">
					{{ csrf_field() }}
					<div class="getintuchforminnersec">
						
							<div class="getintuchforminnerleftsec">
								<label for="r-form-1-first-name">Hey, I’m is</label>
								<input type="text" name="first-name" id="r-form-1-first-name" placeholder="name" class="textbox-cls">
							</div>
							<div class="getintuchforminnerrightsec">
									<label for="r-form-1-email">my website is</label>
									<input type="text" name="website" id="r-form-1-email" name="" placeholder="www.example.com">
							</div>
							<div class="getintuchforminnerleftsec">
									<label for="selfie">and, I’m looking for </label>
									<select class="selectarrow">
										<span>&#xf107;</span>
											<option selected>&nbsp; Select </option>
											<option value="1">Project Based SEO</option>
											<option value="2">Hourly SEO</option>
											<option value="3">SEO Retainer</option>
									</select>
										
							</div>
							<div class="getintuchforminnerrightsec">
									<label for="r-form-1-last-name">Get in touch with me at </label>
									<input type="text" name="email" id="r-form-1-first-name" placeholder="email">
							</div>
							<div class="getintuchforminnerleftsec">
										<label for="r-form-1-email">or call  </label>
										<input type="text" name="phone" id="r-form-1-email"  placeholder="phone no.">
							</div>
							<div class="getintuchforminnerrightsec">
									<label>Any additional info </label>
									<input type="text" id="r-form-1-email" name="" placeholder="brief about project">
							</div>
							<div class="getintuchforminnerbottomsec">
							<p style = "font-size:12px"> <input type="checkbox" id="r-form-1-email" name="" >  Subscribe For Important SEO Updates(We Will Never Spam Your Inbox) </p>
									
							</div>
							<div class="getintuchforminnerbottomsec">
                               {!! NoCaptcha::display(['data-size'=>"invisible"]) !!}
                            </div>
							<div class="getintuchforminnerbottomsec">
									<button type="submit"> Send Enquiry </button>
							</div>

						</div>
					</form>
				</section>
				<section class="ourbestcapabilitysec">
					<div class="row">
						<div class="col-lg-6 col-md-12 col-sm-12">
							 <div class="ourbestcapabilityleftsec i-can-has-a-colored-thing">
									<h2>Our <sapn class="highlight">Best Capability SEO Solutions</sapn> Set Us Apart</h2>
									<h4>Unparalleled Strategy </h4>
									<p> SEO packages from SeoEaze not just deliver you high-quality traffic for your website, but they also create brand awareness, consumer loyalty, 
											conversions and offer maximum return on your digital marketing budget investment.</p>
									<h4>Unique Approach </h4>
									<p>We have no one-size-fits-all, cookie-cutter 
											SEO solutions, rather customized SEO packages for every client. Just get in touch with our expert SEO consultants to discuss a SEO strategy that will change your digital marketing game.</p>
									<h4>Talented SEO Specialists </h4>
									<p>We have designed our SEO services packages to be a strategic combination of the latest SEO techniques and in line with your specific business goals so that we can achieve them together. We have included a number of services in our packages so that it is easier for you to pick up a customized plan. If you think there’s something more that your business needs, then our team can work out an SEO plan that covers your business requirements and vision.</p>
							 </div>
						</div>
						<div class="col-lg-6 col-md-12 col-sm-12">
								<div class="ourbestcapabilityrightsec">
										<img src="assets/img/seo_packages_img/ourbestcapabilityrightsecimg.webp" alt="seo dashboard" />
										<div class="thirdrighttsec">
												<p>
														Your Digital Strategy
														Is Awaiting
												</p>
												<div class="indibuttons">
												<a href="javascript:;" data-toggle="modal" data-target="#myModal">
													<button class="btn-hover color-1"> Ping Now 
														<span class="roundshapebutton roundshapearrow"> 
															<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
																<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
															</svg>
														</span>
													</button></a>
												</div>
											</div>
								</div>
						</div>
					</div>
				</section>

				<section class="weareatrustedgooglepartner">
						<div class="weareatrustedgooglepartnerleftsec i-can-has-a-colored-thing">
								<h2>WE ARE A TRUSTED <span class="highlight">GOOGLE PARTNER </span></h2>
								<p>We are proud to mention that we are a certified Google Partner. As our company is certified, we can manage Google Ads	accounts for your clients and their businesses. We have even earned the much-valued Google Partner badge.</p>
						</div>
						<div class="weareatrustedgooglepartnerrightsec">
							<div class="googlepartnersec">
								<img src="assets/img/seo_packages_img/googlepartnerimg.webp" alt="google partner" />
									<div class="googlepartner1"><img src="assets/img/seo_packages_img/googlepartnericon5.png" alt="" /></div>
									<div class="googlepartner2"><img src="assets/img/seo_packages_img/googlepartnericon4.png" alt="" /></div>
									<div class="googlepartner3"><img src="assets/img/seo_packages_img/googlepartnericon3.png" alt="" /></div>
									<div class="googlepartner4"><img src="assets/img/seo_packages_img/googlepartnericon2.png" alt="" /></div>
									<div class="googlepartner5"><img src="assets/img/seo_packages_img/googlepartnericon1.png" alt="" /></div>
							</div>

						</div>

				</section>
				<section class="seo_packagehsecondsec">
						<div class="container">
							<div class="row">
								<div class="col-lg-3 col-md-12 col-sm-12">
									<div class="seo_packagehsecondleftsec i-can-has-a-colored-thing">
										<p class="highlight">Let’s Get Down To Numbers</p>
										<h2>
											Our 
											SEO services 
											overcome 
											challenges 
											from 
											all industries  
										</h2>
									</div>
								</div>
								<div class="col-lg-9 col-md-12 col-sm-12">
									<div class="seo_packagehsecondrightsec">
										<div class="seo_packagehsecondrightinnersec">
											<div class="seo_packagehsecondrightinnerheadersec">
												<span><img src="assets/img/seo_packages_img/education_icon.png"/></span>
												<h4>Industry:</h4>
												<h2>Education</h2>
											</div>
											<div class="contenttablesec">
														  
														  <table class="table">
															<thead class="thead-light">
															  <tr>
																<th scope="col">Keyword</th>
																<th scope="col">Google India</th>
															  </tr>
															</thead>
															<tbody>
															  <tr>
																<td>Bachelor Degree in Nursing</td>
																<td class="text-center">1</td>
															  </tr>
															  <tr>
																<td>Bachelors Degree Programs</td>
																<td class="text-center">4</td>
															  </tr>
															  <tr>
																<td>Accredited IT Degree Programs</td>
																<td class="text-center">2</td>
															  </tr>
															  <tr>
																<td>Best Dual-Degree Programs</td>
																<td class="text-center">5</td>
															  </tr>
															  <tr>
																 <td>Bachelor of Nursing</td>
																 <td class="text-center">2</td>
															  </tr>
															</tbody>
														  </table>
											</div>
										</div>
										<div class="seo_packagehsecondrightinnersec">
												<div class="seo_packagehsecondrightinnerheadersec">
													<span><img src="assets/img/seo_packages_img/education_icon.png"/></span>
													<h4>Industry:</h4>
													<h2>Education</h2>
												</div>
												<div class="contenttablesec">
															  
															  <table class="table">
																<thead class="thead-light">
																  <tr>
																	<th scope="col">Keyword</th>
																	<th scope="col">Google India</th>
																  </tr>
																</thead>
																<tbody>
																  <tr>
																	<td>Bachelor Degree in Nursing</td>
																	<td class="text-center">1</td>
																  </tr>
																  <tr>
																	<td>Bachelors Degree Programs</td>
																	<td class="text-center">4</td>
																  </tr>
																  <tr>
																	<td>Accredited IT Degree Programs</td>
																	<td class="text-center">2</td>
																  </tr>
																  <tr>
																	<td>Best Dual-Degree Programs</td>
																	<td class="text-center">5</td>
																  </tr>
																  <tr>
																	 <td>Bachelor of Nursing</td>
																	 <td class="text-center">2</td>
																  </tr>
																</tbody>
															  </table>
												</div>
											</div>
											<div class="seo_packagehsecondrightinnersec">
													<div class="seo_packagehsecondrightinnerheadersec">
														<span><img src="assets/img/seo_packages_img/education_icon.png"/></span>
														<h4>Industry:</h4>
														<h2>Education</h2>
													</div>
													<div class="contenttablesec">
																  
																  <table class="table">
																	<thead class="thead-light">
																	  <tr>
																		<th scope="col">Keyword</th>
																		<th scope="col">Google India</th>
																	  </tr>
																	</thead>
																	<tbody>
																	  <tr>
																		<td>Bachelor Degree in Nursing</td>
																		<td class="text-center">1</td>
																	  </tr>
																	  <tr>
																		<td>Bachelors Degree Programs</td>
																		<td class="text-center">4</td>
																	  </tr>
																	  <tr>
																		<td>Accredited IT Degree Programs</td>
																		<td class="text-center">2</td>
																	  </tr>
																	  <tr>
																		<td>Best Dual-Degree Programs</td>
																		<td class="text-center">5</td>
																	  </tr>
																	  <tr>
																		 <td>Bachelor of Nursing</td>
																		 <td class="text-center">2</td>
																	  </tr>
																	</tbody>
																  </table>
													</div>
												</div>
												<div class="seo_packagehsecondrightinnersec">
														<div class="seo_packagehsecondrightinnerheadersec">
															<span><img src="assets/img/seo_packages_img/education_icon.png"/></span>
															<h4>Industry:</h4>
															<h2>Education</h2>
														</div>
														<div class="contenttablesec">
																	  
																	  <table class="table">
																		<thead class="thead-light">
																		  <tr>
																			<th scope="col">Keyword</th>
																			<th scope="col">Google India</th>
																		  </tr>
																		</thead>
																		<tbody>
																		  <tr>
																			<td>Bachelor Degree in Nursing</td>
																			<td class="text-center">1</td>
																		  </tr>
																		  <tr>
																			<td>Bachelors Degree Programs</td>
																			<td class="text-center">4</td>
																		  </tr>
																		  <tr>
																			<td>Accredited IT Degree Programs</td>
																			<td class="text-center">2</td>
																		  </tr>
																		  <tr>
																			<td>Best Dual-Degree Programs</td>
																			<td class="text-center">5</td>
																		  </tr>
																		  <tr>
																			 <td>Bachelor of Nursing</td>
																			 <td class="text-center">2</td>
																		  </tr>
																		</tbody>
																	  </table>
														</div>
													</div>
									</div>
								</div>
							</div>
						</div>
					</section>
				<section class="werulethecompetitionsec">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 col-md-12 col-sm-12">
									<div class="werulethecompetitionleftsec i-can-has-a-colored-thing">
										<h2> We Rule The<br><span class="highlight">  Competition</span></h2>
										<p>At SeoEaze, we’ve built a series of SEO service packages that are not based on keywords like other digital marketing agencies. Rather, we have focused on 
												in-depth research, customized strategies and transparent reporting to deliver measurable results to our 
												clients.
											</p>
												<p>
														Our SEO team focuses on delivering real results, which is why we ensure our SEO packages have the right deliverables fit for your business size- whether you are a startup or a large enterprise. In the last decade of our existence, we have earned our hundreds of clients millions in 
														revenue with local and global SEO 
														strategies that get more leads, calls and customers.
												</p>
										</div>
								</div>
								<div class="col-lg-6 col-md-12 col-sm-12">
											<div class="werulethecompetitionrightsec i-can-has-a-colored-thing">
												<h3>We stand out with pride 
														because we offer:</h3>
													<div class="werulethecompetitionrightinnerleftsec">
														Transparent andin-depth reporting
													</div>
													<div class="werulethecompetitionrightinnerrightsec">
															<div class="werulethecompetitionrightinnerrightfirstsec"> High Response Rate </div>
															<div class="werulethecompetitionrightinnerrightsecondsec"> Skilled and experienced team of SEO experts</div>
															<div class="werulethecompetitionrightinnerrightthirdsec"> Affordable SEO packages that effectively deliver goals</div>
															<div class="werulethecompetitionrightinnerrightfourthsec"> No obligatory contracts or hidden fees</div>
															<div class="werulethecompetitionrightinnerrightfifthsec"> Real results and more conversions </div>
													</div>
											</div>
									</div>
							</div>
						</div>
				</section>



				<section class="tablesec">
					<ul>
						<li>
							<div class="tableinnersec">
								<div class="tableinnerheadersec">
									<h2> Starter </h2>
									<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a>
								</div>
								<div class="tableinnercontentsec">
									<ul>
										<li><span> 2-5 </span> Keywords Suggested </li>
										<li><span class="plusicocls"></span> Full Website Analysis </li>
										<li><span class="plusicocls"></span> Site Speed Audit </li>
										<li><span class="plusicocls"></span> Backlinks Audit </li>
										<li><span class="plusicocls"></span> Competition Analysis </li>
										<li><span class="plusicocls"></span> Duplicate Content Check </li>
										<li><span class="plusicocls"></span> Keyword Research	 </li>
										<li><span class="plusicocls"></span> Mobile Usability Audit	 </li>
										<li><span class="plusicocls"></span> Meta Tags Optimzation	 </li>
										<li><span class="plusicocls"></span> Content Optimization </li>
										<li><span class="plusicocls"></span> Sitemap Creation/Submission </li>
										<li><span class="plusicocls"></span> Robots.txt Creation	 </li>
										<li><span class="plusicocls"></span> Images Optimization </li>
										<li><span class="plusicocls"></span> Interlinking Setup </li>
										<li><span class="plusicocls"></span> 301/302 Rediect Setup </li>
										<li><span class="plusicocls"></span> htaccess Setup </li>
										<li><span class="plusicocls"></span> Search Console Setup </li>
										<li><span class="plusicocls"></span> Google Analytics Setup	</li>
										<li class="linethroughcls"> Schema Markup Implementation</li>
										<li><span> 1 </span> Mini Blog Creation </li>
										<li><span> 25 </span> PR Distribution </li>
										<li><span> 50 </span>Search Engine Listings </li>
										<li><span> 25 </span> Forum Link Building </li>
										<li><span> 20 </span> Social Sharing </li>
										<li class="linethroughcls"></span> Niche Blog Posts </li>
										<li><span> 10 </span> Article Distributions</li>
										<li><span> 1 </span> Guest Posts </li>
										<li class="linethroughcls"> Link Wheel </li>
										<li><span class="plusicocls"></span> Google/Bing Maps Listing</li>
										<li class="linethroughcls"> Citation Building </li>
										<li class="linethroughcls"> Facebook Ads Management </li>
										<li class="linethroughcls"> Google Ads Management </li>
										<li class="linethroughcls"> FREE Google Ads Credit* </li>
										<li class="linethroughcls"> Facebook Content Management </li>
										<li class="linethroughcls"> Promotional Tweets </li>
										<li><span class="plusicocls"></span>Dedicated Ranklogs** Campaign Dashboard</li>
										<li><span class="plusicocls"></span>SERP Report</li>
										<li><span class="plusicocls"></span>Traffic Report (Analytics)</li>
										<li><span class="plusicocls"></span>Monthly Link Building Report</li>
										<li><span>6-12M</span> Ideal Contract Length</li>
									</ul>
									<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a> 
								</div>
							</div>
						</li>
						<li>
							<div class="tableinnersec">
								<div class="tableinnerheadersec">
									<h2> Silver </h2>
									<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a>
								</div>
								<div class="tableinnercontentsec">
									<ul>
										<li><span> 5-10 </span> Keywords Suggested </li>
										<li><span class="plusicocls"></span> Full Website Analysis </li>
										<li><span class="plusicocls"></span> Site Speed Audit </li>
										<li><span class="plusicocls"></span> Backlinks Audit </li>
										<li><span class="plusicocls"></span> Competition Analysis </li>
										<li><span class="plusicocls"></span> Duplicate Content Check </li>
										<li><span class="plusicocls"></span> Keyword Research	 </li>
										<li><span class="plusicocls"></span> Mobile Usability Audit	 </li>
										<li><span class="plusicocls"></span> Meta Tags Optimzation	 </li>
										<li><span class="plusicocls"></span> Content Optimization </li>
										<li><span class="plusicocls"></span> Sitemap Creation/Submission </li>
										<li><span class="plusicocls"></span> Robots.txt Creation	 </li>
										<li><span class="plusicocls"></span> Images Optimization </li>
										<li><span class="plusicocls"></span> Interlinking Setup </li>
										<li><span class="plusicocls"></span> 301/302 Rediect Setup </li>
										<li><span class="plusicocls"></span> htaccess Setup </li>
										<li><span class="plusicocls"></span> Search Console Setup </li>
										<li><span class="plusicocls"></span> Google Analytics Setup	</li>
										<li class="linethroughcls"> Schema Markup Implementation</li>
										<li><span> 2 </span> Mini Blogs Creation </li>
										<li><span> 50 </span> PR Distribution </li>
										<li><span> 50 </span> Search Engine Listings </li>
										<li><span> 50 </span> Forum Link Building </li>
										<li><span> 30 </span> Social Sharing </li>
										<li><span> 1 </span> Niche Blog Posts </li>
										<li><span> 20 </span> Article Distributions</li>
										<li><span> 2 </span> Guest Post</li>
										<li class="linethroughcls"> Link Wheel </li>
										<li><span class="plusicocls"></span> Google/Bing Maps Listing</li>
										<li><span class="plusicocls"></span> Citation Building </li>
										<li class="linethroughcls"> Facebook Ads Management </li>
										<li class="linethroughcls"> Google Ads Management </li>
										<li class="linethroughcls"> FREE Google Ads Credit* </li>
										<li class="linethroughcls"> Facebook Content Management </li>
										<li class="linethroughcls"> Promotional Tweets </li>
										<li><span class="plusicocls"></span>Dedicated Ranklogs** Campaign Dashboard</li>
										<li><span class="plusicocls"></span>SERP Report</li>
										<li><span class="plusicocls"></span>Traffic Report (Analytics)</li>
										<li><span class="plusicocls"></span>Monthly Link Building Report</li>
										<li><span>6-12M</span> Ideal Contract Length</li>
									</ul>
									<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a> 
								</div>
							</div>
						</li>
						<li>
    						<div class="tableinnersec">
								<div class="tableinnerheadersec">
									<h2> Gold </h2>
									<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a>
								</div>
								<div class="tableinnercontentsec">
									<ul>
										<li><span> Upto 20 </span> Keywords Suggested </li>
										<li><span class="plusicocls"></span> Full Website Analysis </li>
										<li><span class="plusicocls"></span> Site Speed Audit </li>
										<li><span class="plusicocls"></span> Backlinks Audit </li>
										<li><span class="plusicocls"></span> Competition Analysis </li>
										<li><span class="plusicocls"></span> Duplicate Content Check </li>
										<li><span class="plusicocls"></span> Keyword Research	 </li>
										<li><span class="plusicocls"></span> Mobile Usability Audit	 </li>
										<li><span class="plusicocls"></span> Meta Tags Optimzation	 </li>
										<li><span class="plusicocls"></span> Content Optimization </li>
										<li><span class="plusicocls"></span> Sitemap Creation/Submission </li>
										<li><span class="plusicocls"></span> Robots.txt Creation	 </li>
										<li><span class="plusicocls"></span> Images Optimization </li>
										<li><span class="plusicocls"></span> Interlinking Setup </li>
										<li><span class="plusicocls"></span> 301/302 Rediect Setup </li>
										<li><span class="plusicocls"></span> htaccess Setup </li>
										<li><span class="plusicocls"></span> Search Console Setup </li>
										<li><span class="plusicocls"></span> Google Analytics Setup	</li>
										<li class="plusicocls"> Schema Markup Implementation</li>
										<li><span> 5 </span> Mini Blogs Creation </li>
										<li><span> 100 </span> PR Distribution </li>
										<li><span> 100 </span> Search Engine Listings </li>
										<li><span> 200 </span> Forum Link Building </li>
										<li><span> 50 </span> Social Sharing </li>
										<li><span> 5 </span> Niche Blog Posts </li>
										<li><span> 50 </span> Article Distributions</li>
										<li><span> 5 </span></span> Guest Posts </li>
										<li> <span>1 </span> Link Wheel </li>
										<li><span class="plusicocls"></span> Google/Bing Maps Listing</li>
										<li><span class="plusicocls"></span> Citation Building </li>
										<li class="plusicocls"> Facebook Ads Management </li>
										<li class="plusicocls"> Google Ads Management </li>
										<li class="plusicocls"> FREE Google Ads Credit* </li>
										<li class="plusicocls"> Facebook Content Management </li>
										<li class="linethroughcls"> Promotional Tweets </li>
										<li><span class="plusicocls"></span>Dedicated Ranklogs** Campaign Dashboard</li>
										<li><span class="plusicocls"></span>SERP Report</li>
										<li><span class="plusicocls"></span>Traffic Report (Analytics)</li>
										<li><span class="plusicocls"></span>Monthly Link Building Report</li>
										<li><span>6-12M</span> Ideal Contract Length</li>
									</ul>
									<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a> 
								</div>
							</div>
						</li>
						<li>
							<div class="tableinnersec">
								<div class="tableinnerheadersec">
											<h2> Platinum </h2>
											<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a>
										</div>
								<div class="tableinnercontentsec">
											<ul>
												<li><span> Upto 30 </span> Keywords Suggested </li>
												<li><span class="plusicocls"></span> Full Website Analysis </li>
												<li><span class="plusicocls"></span> Site Speed Audit </li>
												<li><span class="plusicocls"></span> Backlinks Audit </li>
												<li><span class="plusicocls"></span> Competition Analysis </li>
												<li><span class="plusicocls"></span> Duplicate Content Check </li>
												<li><span class="plusicocls"></span> Keyword Research	 </li>
												<li><span class="plusicocls"></span> Mobile Usability Audit	 </li>
												<li><span class="plusicocls"></span> Meta Tags Optimzation	 </li>
												<li><span class="plusicocls"></span> Content Optimization </li>
												<li><span class="plusicocls"></span> Sitemap Creation/Submission </li>
												<li><span class="plusicocls"></span> Robots.txt Creation	 </li>
												<li><span class="plusicocls"></span> Images Optimization </li>
												<li><span class="plusicocls"></span> Interlinking Setup </li>
												<li><span class="plusicocls"></span> 301/302 Rediect Setup </li>
												<li><span class="plusicocls"></span> htaccess Setup </li>
												<li><span class="plusicocls"></span> Search Console Setup </li>
												<li><span class="plusicocls"></span> Google Analytics Setup	</li>
												<li class="plusicocls"> Schema Markup Implementation</li>
												<li><span> 8 </span> Mini Blogs Creation </li>
												<li><span> 150 </span> PR Distribution </li>
												<li><span> 100 </span> Search Engine Listings </li>
												<li><span> 300 </span> Forum Link Building </li>
												<li><span> 100 </span> Social Sharing </li>
												<li><span> 8 </span> Niche Blog Posts </li>
												<li><span> 70 </span> Article Distributions</li>
												<li><span> 7 </span> Guest Post</li>
												<li> <span>2 </span> Link Wheels </li>
												<li><span class="plusicocls"></span> Google/Bing Maps Listing</li>
												<li><span class="plusicocls"></span> Citation Building </li>
												<li class="plusicocls"> Facebook Ads Management </li>
										        <li class="plusicocls"> Google Ads Management </li>
												<li class="plusicocls"> FREE Google Ads Credit* </li>
												<li class="plusicocls">Facebook Content Management  </li>
												<li class="linethroughcls"> Promotional Tweets </li>
												<li><span class="plusicocls"></span>Dedicated Ranklogs** Campaign Dashboard</li>
												<li><span class="plusicocls"></span>SERP Report</li>
												<li><span class="plusicocls"></span>Traffic Report (Analytics)</li>
												<li><span class="plusicocls"></span>Monthly Link Building Report</li>
										        <li><span>6-12M</span> Ideal Contract Length</li>
											</ul>
											<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a> 
										</div>
							</div>
						</li>
						<li>
							<div class="tableinnersec">
								<div class="tableinnerheadersec">
											<h2> Diamond </h2>
											<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a>
										</div>
								<div class="tableinnercontentsec">
											<ul>
												<li><span> Upto 50 </span> Keywords Suggested </li>
												<li><span class="plusicocls"></span> Full Website Analysis </li>
												<li><span class="plusicocls"></span> Site Speed Audit </li>
												<li><span class="plusicocls"></span> Backlinks Audit </li>
												<li><span class="plusicocls"></span> Competition Analysis </li>
												<li><span class="plusicocls"></span> Duplicate Content Check </li>
												<li><span class="plusicocls"></span> Keyword Research	 </li>
												<li><span class="plusicocls"></span> Mobile Usability Audit	 </li>
												<li><span class="plusicocls"></span> Meta Tags Optimzation	 </li>
												<li><span class="plusicocls"></span> Content Optimization </li>
												<li><span class="plusicocls"></span> Sitemap Creation/Submission </li>
												<li><span class="plusicocls"></span> Robots.txt Creation	 </li>
												<li><span class="plusicocls"></span> Images Optimization </li>
												<li><span class="plusicocls"></span> Interlinking Setup </li>
												<li><span class="plusicocls"></span> 301/302 Rediect Setup </li>
												<li><span class="plusicocls"></span> htaccess Setup </li>
												<li><span class="plusicocls"></span> Search Console Setup </li>
												<li><span class="plusicocls"></span> Google Analytics Setup	</li>
												<li class="plusicocls"> Schema Markup Implementation</li>
												<li><span> 10 </span> Mini Blogs Creation </li>
												<li><span> 200 </span> PR Distribution </li>
												<li><span> 150 </span> Search Engine Listings </li>
												<li><span> 500 </span> Forum Link Building </li>
												<li><span> 150 </span> Social Sharing </li>
												<li><span> 10 </span> Niche Blog Posts </li>
												<li><span> 100 </span> Article Distributions</li>
												<li><span> 10 </span> Guest Post</li>
												<li> <span>3 </span> Link Wheels </li>
												<li><span class="plusicocls"></span> Google/Bing Maps Listing</li>
												<li><span class="plusicocls"></span> Citation Building </li>
												<li class="plusicocls"> Facebook Ads Management </li>
										        <li class="plusicocls"> Google Ads Management </li>
												<li class="plusicocls"> FREE Google Ads Credit* </li>
												<li class="plusicocls"> Facebook Content Management </li>
												<li class="linethroughcls"> Promotional Tweets </li>
												<li><span class="plusicocls"></span>Dedicated Ranklogs** Campaign Dashboard</li>
												<li><span class="plusicocls"></span>SERP Report</li>
												<li><span class="plusicocls"></span>Traffic Report (Analytics)</li>
												<li><span class="plusicocls"></span>Monthly Link Building Report</li>
										        <li><span>6-12M</span> Ideal Contract Length</li>
											</ul>
											<a href="javascript:;" data-toggle="modal" data-target="#myModal"> <button> Enquire Now </button> </a> 
										</div>
							</div>
						</li>
					</ul>
				</div>
				</section>



				<section class="moneybackguranteesec">
						<div class="container">
							<div class="row">
								<div class="col-lg-8 col-md-12 col-sm-12">
									<div class="moneybackguranteeleftsec i-can-has-a-colored-thing">
										<h2> 30-Day <br> <span class="highlight"> Money-Back Offer </span></h2>
										<p>We know we can deliver no matter how big a challenge is. 
												This is why SeoEaze offers risk-free 30 days money-back guarantee. 
												Either we get you results or you get your money back, simple.
											</p>
												
									</div>
							</div>
							<div class="col-lg-4 col-md-12 col-sm-12">
									<div class="moneybackguranteerightsec">
										<img src="assets/img/seo_packages_img/moneybackguaranteeicon.webp" alt="money back guarantee by seoeaze" />
										<div class="indibuttons">
										<a href="javascript:;" data-toggle="modal" data-target="#myModal">
												<button class="btn-hover color-1"> Let's Get Started
													<span class="roundshapebutton roundshapearrow"> 
														<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
															<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
														</svg>
													</span>
												</button></a>
											</div>
									</div>
							</div>
						</div>
				</section>

				<section class="whatmakesusdifferentsec">
						<div class="container i-can-has-a-colored-thing">
								<h2> What <span class="highlight"> Makes Us Different? </span></h2>
								<p>Features & Benefits You Enjoy At SEOEAZE</p>
							<div class="row">

								<div class="col-lg-4 col-md-6 col-sm-12">
									<div class="whatmakesusdifferentinnersec">
										<figure><img src="assets/img/seo_packages_img/whatmakesusdifferenticon1.png" alt="" /></figure>
										<h2> Keyword Research </h2>
										<p>
											  Not the traditional keyword research but evolving 
												analysis of keywords based on latent semantics, searcher’s 
												intent and voice search-oriented.
											</p>
									</div>
								</div>
								<div class="col-lg-4 col-md-6 col-sm-12">
									<div class="whatmakesusdifferentinnersec">
										<figure><img src="assets/img/seo_packages_img/whatmakesusdifferenticon2.png" alt="" /></figure>
										<h2> Years Of Experience </h2>
										<p>
												Believe it or not, SeoEaze has been able to keep up with the game of changing SEO and search ranking 
												algorithms for over a decade. We don’t think anything can slow us down.
												
										</p>
									</div>
								</div>
								<div class="col-lg-4 col-md-6 col-sm-12">
										<div class="whatmakesusdifferentinnersec">
											<figure><img src="assets/img/seo_packages_img/whatmakesusdifferenticon3.png" alt="" /></figure>
											<h2> Detailed SEO Reports </h2>
											<p>
													We ensure you are not left out which is why we are transparent with our SEO reporting. You are always aware of what’s going on.
											</p>
										</div>
									</div>
									<div class="col-lg-4 col-md-6 col-sm-12">
											<div class="whatmakesusdifferentinnersec">
												<figure><img src="assets/img/seo_packages_img/whatmakesusdifferenticon4.png" alt="" /></figure>
												<h2> Professional Content </h2>
												<p>
													Content remains the king, which is why we only work with expert native writers who understand your business. SEO oriented and valuable content is what boost our SEO results.
												</p>
											</div>
										</div>
										<div class="col-lg-4 col-md-6 col-sm-12">
												<div class="whatmakesusdifferentinnersec">
													<figure><img src="assets/img/seo_packages_img/whatmakesusdifferenticon5.png" alt="" /></figure>
													<h2> Affordable Packages </h2>
													<p>
														SEO packages for every business, small or big. Keeping our prices 
														competitive is also 
														important to be ahead in the race without compromising on service quality.
													</p>
												</div>
											</div>
											<div class="col-lg-4 col-md-6 col-sm-12">
													<div class="whatmakesusdifferentinnersec">
														<figure><img src="assets/img/seo_packages_img/whatmakesusdifferenticon6.png" alt="" /></figure>
														<h2> Customized Solutions </h2>
														<p>
															You do not have to become a part of the run-of-the-mill solution, just reach out to our experts and they will tailor a customized SEO plan encompassing your requirements and needs.
														</p>
													</div>
												</div>

							</div>
						</div>
				</section>

				<section class="frequentlyaskedquestionsec">
						<div class="container i-can-has-a-colored-thing">
								<h2> Frequently <br> <span class="highlight"> Asked Questions</span> </h2>
							<div class="row">

								<div class="col-lg-5 col-md-12 col-sm-12" style="margin-top: -50px;">
									<img src="assets/img/seo_packages_img/faqsleftsec.gif" class="img-fluid" alt=""/>
								</div>
								<div class="col-lg-7 col-md-12 col-sm-12">
									  <!-- start Frequently Asked Questions-->
									  			<button class="accordion">What are your SEO Strategy & SEO Packages?</button>
												<div class="panel">
													<p>Our SEO strategy & packages are a complete SEO bundle which include the details of SEO tasks we provide as an SEO agency and the price we charge. The cost of our SEO plans ranges from $250 to $1000. The prices of our packages are completely dependent on the niche of the website and the competition against the business of the client.</p>
												</div>

												<button class="accordion">What all is included in SEO Services?</button>
												<div class="panel">
													<p>Our Monthly SEO Plans take care of your technical SEO related issues including On-page SEO, Off-Page SEO and content marketing.</p>
												</div>
												
												<button class="accordion">Are custom monthly SEO packages available?</button>
												<div class="panel">
													<p>Yes, we can build custom SEO plans for you. Please get in touch with us so that we can understand your requirements.</p>
												</div>
												
												<button class="accordion">What is the minimum contract period for these SEO Plans?</button>
												<div class="panel">
													<p>6 months. Based on our experience, in most cases, it takes a good 5-6 months to achieve rankings on competitive keywords and to start driving a significant volume of targeted traffic. If you are serious about SEO, you should be prepared to continue for at least 6 months. If you need quick results, you can go with 1 month plans or check out our PPC plans.</p>
												</div>
												
												<button class="accordion">Do you use White Hat or Black Hat SEO techniques?</button>
												<div class="panel">
													<p>We use only white hat SEO techniques to offer the best SEO services. We are not into any type of illegal or black hat working.</p>
												</div>

												<button class="accordion">Who will be working on my SEO campaign?</button>
												<div class="panel">
													<p>Our trained and experienced team of SEO professionals will work on your campaign, providing the best SEO solutions. There will even be a dedicated manager for your project who will be assisting you with everything you need to know.</p>
												</div>

												<button class="accordion">How long does it take to show SEO results for Google ranking?</button>
												<div class="panel">
													<p>If you already have an established website, it will not take long to rank high. But if you have a relatively new site, it will take about 5-6 months to see your business in top 100 rankings.</p>
												</div>
  										<!-- end Frequently Asked Questions-->

								</div>
							</div>

						</div>
				</section>

				<section class="clientsec">
						<h2> Some of Our Esteemed Clients </h2>
							<div class="clientinnersec">
								<div class="clientinnerleftsec">
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg1.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg2.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg3.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg4.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg5.webp" alt="client icon"/></a></li>
									</ul>
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg6.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg7.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg8.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg9.webp" alt="client icon"/></a></li>
									</ul>
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg10.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg11.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg12.webp" alt="client icon"/></a></li>
									</ul>
								</div>	
							</div>		
				</section>

				<section class="testimonial">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 d-none d-lg-block">
									<ol class="carousel-indicators tabs">
										<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-01-179x179.webp" class="img-fluid" alt="seoeaze testimonial 1">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="1">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-02-306x306.webp" class="img-fluid" alt="seoeaze testimonial 2">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="2">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-03-179x179.webp" class="img-fluid" alt="seoeaze testimonial 3">
											</figure>
										</li>
									</ol>
								</div>
								<div class="col-lg-6 d-flex justify-content-center align-items-center i-can-has-a-colored-thing">
									<div id="carouselExampleIndicators" data-interval="false" class="carousel slide" data-ride="carousel">
										<h3>Words From</h3>
										<h1><span class="highlight">Our Clients</span></h1>
										<h4>Our Valued Customers Believe In Us & 
												This Is What Keeps Us Going</h4>
										<div class="carousel-inner">
											<div class="carousel-item active">
												<div class="quote-wrapper">
													<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
															It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																												</p>
													<h3> Evrim Oralkan </h3>
													<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
										</div>
										<ol class="carousel-indicators indicators">
											<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
										</ol>
									</div>
								</div>
							</div>
						</div>
				</section>

				<section class="seventhsec">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 col-md-12 col-sm-12">
									<h3>We <i class="fas fa-heart hearticonsty"></i> <br> what we do </h3>
								</div>
								<div class="col-lg-6 col-md-12 col-sm-12">
									<h4>In a world of infinite possibilities, do not limit yourself.</h4>
									<div class="indibuttons">
									<a href="javascript:;" data-toggle="modal" data-target="#myModal">
											<button class="btn-hover color-1"> Let’s Talk  
												<span class="roundshapebutton roundshapearrow"> 
													<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
														<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
													</svg>
												</span>
											</button></a>
										</div>
								</div>
							</div>
						</div>
				</section>
         
<script>
function init() {
var vidDefer = document.getElementsByTagName('iframe');
for (var i=0; i<vidDefer.length; i++) {
if(vidDefer[i].getAttribute('data-src')) {
vidDefer[i].setAttribute('src',vidDefer[i].getAttribute('data-src'));
} } }
window.onload = init;
</script>





 @endsection