@extends('layouts.master')

@section('title', 'Social Media Marketing services by top agency-SMO plans for companies')
@section('meta' , "SeoEaze is best Social Media Marketing Agency Providing Services Since 2009, our unique Social Media Marketing Strategy helps companies to get best results.")

@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.com/social_media_marketing" hreflang="en-us" />
    <link rel="alternate" href="https://www.seoeaze.in/social_media_marketing" hreflang="en-in" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/social_media_marketing" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/social_media_marketing" hreflang="x-default" />
@endsection

<!-- Start Breadcrumbs Schema -->
<script type="application/ld+json">
{
  "@context": "https://schema.org/", 
  "@type": "BreadcrumbList", 
  "itemListElement": [{
    "@type": "ListItem", 
    "position": 1, 
    "name": "Home",
    "item": "https://www.seoeaze.com"  
  },{
    "@type": "ListItem", 
    "position": 2, 
    "name": "Social Media Marketing Service",
    "item": "https://www.seoeaze.com/social_media_marketing"  
  }]
}
</script>
<!-- End Breadcrumbs Schema -->

<!-- FAQ Schema start -->
    <script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Why social media marketing is important?","acceptedAnswer":[{"@type":"Answer","text":"Social media is a lot more cost-effective as compared to TV, print media or radio when it comes to reaching the large customer base. Companies and brands can incorporate social media marketing into their digital marketing strategy to get far more measurable results than traditional media."}]},{"@type":"Question","name":"Which social media platform should I use?","acceptedAnswer":[{"@type":"Answer","text":"In today’s scenario, it is best to use multiple platforms. Still, you need to decide based on these factors such as: Who is your target audience? Which platform do they spend their time on? Such questions will help you decide which platform is best to reach your audience with the right content at the right time."}]},{"@type":"Question","name":"How many people can I reach with social media marketing?","acceptedAnswer":[{"@type":"Answer","text":"With 8 out of 10 U.S. internet users accessing social media content, theoretically get access to 80% of the internet users in the United State with SMM. However, it all depends on how creative and captivating your content is."}]},{"@type":"Question","name":"How much social media marketing costs?","acceptedAnswer":[{"@type":"Answer","text":"The cost of SMM campaigns varies depending on your objectives and goals. It is best to talk to our social media strategists who can better explain the cost involved."}]}]}</script><!-- Generated by https://www.seoeaze.com/ -->
<!-- FAQ Schema end -->
@section('header')
@show
@section('content')
<section class="social_media_marketing_solution_sec">
					<div class="container">
							<div class="social_media_marketing_solution_left_sec i-can-has-a-colored-thing">
									<h2><span class="highlight">Social Media Marketing</span> </h2>
									<h4>Enhance Your Social Presence;
										Connect With More People</h4>
									<ul>
										<li>Have your presence on various social media networks</li>
										<li>Increase your followers</li>
										<li>Create brand awareness</li>
										<li>Increase customer engagement</li>
										<li>Manage brand visibility</li>
									</ul>
									<div class="indibuttons">
										<button class="btn-hover color-1"> Consult Now
											<span class="roundshapebutton roundshapearrow"> 
												<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
													<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
												</svg>
											</span>
										</button>
									</div>
							</div>
							<div class="social_media_marketing_solution_right_sec">
									<img src="assets/img/social_media_marketing/social_media_marketing_head.png" alt="" />
							</div>
					</div>

				</section>
				<section class="social_media_marketing_solution_dedicatedyourbrandsec">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-12">
								<h2>Modern Social Media 
									Marketing Solutions 
									Dedicated For Your Brand</h2>
									<figure><img src="assets/img/social_media_marketing/dedicatedyourbrandimg.png" alt=""/></figure>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-12">
									<p>
										As one of the best social media marketing companies in India, we at SEOEaze acknowledge that social media marketing gives 100% positive leads towards real sales. So irrespective of your business, we help you to gain active presence on different social media platforms.
										Creating brand awareness on different social platforms becomes interesting with us. Our social media specialists understand your business and target your audience accordingly.
										As a social media marketing expert, we manage social networks like Facebook, Twitter, Instagram and more. We use effective SMO techniques to let your business get better visibility on major social platforms.
									</p>
							</div>
						</div>
						<div class="row pt-5">
							<div class="col-lg-3 col-md-3 col-sm-12">
								<div class="socialmediasec">
								<figure><img src="assets/img/social_media_marketing/social_media_marketing_face.png" alt=""/></figure>
								<div class="socialmediainnersec bgimg1">
								<div class="socialmediainnerboxsec"><i class="fab fa-facebook-f"></i></div>
								<p>With our FB marketing service, 
									you can have more customers 
									coming your way. We help to 
									manage your Facebook account 
									and help promoting your 
									products and services through it. 
									Links to your recent blog posts 
									or quiz or contests can engage 
									the customers and bring in 
									more sales.</p>
									</div>
								</div>
							</div>
							<div class="col-lg-3 col-md-3 col-sm-12">
								<div class="socialmediasec">
								<figure><img src="assets/img/social_media_marketing/social_media_marketing_inst.png" alt=""/></figure>
								<div class="socialmediainnersec bgimg2">
								<div class="socialmediainnerboxsec"><i class="fab fa-instagram"></i></div>
								<p>We can help you promote your 
									brand through appealing images 
									on Instagram. You can have 
									pictures of your team, services, 
									products and we can help you to 
									write the perfect hashtags and 
									status for your posts. take your 
									Intagram marketing to another 
									level with our expert services.</p>
								</div>
							</div>
							</div>
							<div class="col-lg-3 col-md-3 col-sm-12">
								<div class="socialmediasec">
								<figure><img src="assets/img/social_media_marketing/social_media_marketing_twit.png" alt=""/></figure>
								<div class="socialmediainnersec bgimg3">
								<div class="socialmediainnerboxsec"><i class="fab fa-twitter"></i></div>
								<p>We use the best Twitter 
									marketing strategy to offer the 
									informationyou want and we can 
									help you with this in the best 
									possible way. Our social media 
									marketing experts will handle 
									your Twitter account, add images, 
									follow similar businesses, update 
									tweets, manage ads and more.</p>
								</div>
							</div>
							</div>
							<div class="col-lg-3 col-md-3 col-sm-12">
								<div class="socialmediasec">
								<figure><img src="assets/img/social_media_marketing/social_media_marketing_comp.png" alt=""/></figure>
								<div class="socialmediainnersec bgimg4">
								<div class="socialmediainnerboxsec"><i class="fa fa-gift" aria-hidden="true"></i></div>
								<p>We also offer all-in-one packages 
									to help you with all types of social 
									media marketing services like 
									Facebook, Google+, Twitter, 
									Pinterest, Instagram and more. 
									By this, we help to keep all SMO 
									solutions under one big roof so 
									that you don’t have to skip one or 
									the other service.</p>
								</div>
								</div>
							</div>
						</div>
				</section>
				<section class="social_media_marketing_solution_featuresandbenifitsec">
					<h2> Our SMO Features & Benefits </h2>
					<div class="row m-0">
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecwhitebgimg">
								<h4>Brand Awareness</h4>
								<p>Increase your brand awareness through popular social networks. this not only enhances your social presence but even your business credibility.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecgreenbgimg">
								<h4>Get More Visitors</h4>
								<p>Increase your brand awareness through popular social networks. this not only enhances your social presence but even your business credibility.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecwhitebgimg">
								<h4>Offline Marketing</h4>
								<p>Good Social media marketing can contribute in offline marketing as well. It is through social media that people will get to know about your business and may visit your store/company for offline solutions.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecgreenbgimg">
								<h4> Performance Tracking & Reporting </h4>
								<p> We provide weekly and monthly updates of your projects so to help you track your site’s progress. We also provide what has been planned for the coming months.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecwhitebgimg">
								<h4>Social Media Presence</h4>
								<p>With our social media marketing services, you can have increased social presence. Enjoy more fans, followers, likes and more when you hire our expert SMO 
									solutions.</p>
							</div>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 m-0 p-0">
							<div class="social_media_marketing_solution_featuresandbenifitinnersec featuresandbenifitinnersecgreenbgimg">
								<h4>Go Viral</h4>
								<p>With our social media marketing services, you can have increased social presence. Enjoy more fans, followers, likes and more when you hire our expert SMO solutions.</p>
							</div>
						</div>
					</div>

				</section>

				<section class="getintuchformsec">
					<h2> 
						Let’s get Started
						Fill Us In About 
						Your Requirement
					</h2>
					<form role="form" method="post" action="/seo_sending_form">
					{{ csrf_field() }}
					<div class="getintuchforminnersec">
						
							<div class="getintuchforminnerleftsec">
								<label for="r-form-1-first-name">Hey, I’m is</label>
								<input type="text" name="first-name" id="r-form-1-first-name" placeholder="name" class="textbox-cls">
							</div>
							<div class="getintuchforminnerrightsec">
									<label for="r-form-1-email">my website is</label>
									<input type="text" name="website" id="r-form-1-email" name="" placeholder="www.example.com">
							</div>
							<div class="getintuchforminnerleftsec">
									<label for="selfie">and, I’m looking for </label>
									<select class="selectarrow">
										<span>&#xf107;</span>
											<option selected>&nbsp; Select </option>
											<option value="1">One</option>
											<option value="2">Two</option>
											<option value="3">Three</option>
									</select>
										
							</div>
							<div class="getintuchforminnerrightsec">
									<label for="r-form-1-last-name">Get in touch with me at </label>
									<input type="text" name="email" id="r-form-1-first-name" placeholder="email">
							</div>
							<div class="getintuchforminnerleftsec">
										<label for="r-form-1-email">or call  </label>
										<input type="text" name="phone" id="r-form-1-email"  placeholder="phone no.">
							</div>
							<div class="getintuchforminnerrightsec">
									<label>Any additional info </label>
									<input type="text" id="r-form-1-email" name="" placeholder="brief about project">
							</div>
							<div class="getintuchforminnerbottomsec">
									<p> <input type="checkbox" id="r-form-1-email" name="" >We Will Never Spam Your Inbox </p>
									
							</div>
							<div class="getintuchforminnerbottomsec">
                                {!! Recaptcha::render() !!}
                            </div>
							<div class="getintuchforminnerbottomsec">
									<button type="submit"> Send Enquiry </button>
							</div>

						</div>
					</form>
				</section>

				<section class="frequentlyaskedquestionsec">
						<div class="container i-can-has-a-colored-thing">
								<h2> Frequently <br> <span class="highlight"> Asked Questions</span> </h2>
							<div class="row">

								<div class="col-lg-5 col-md-12 col-sm-12" style="margin-top: -50px;">
									<img src="assets/img/seo_packages_img/faqsleftsec.gif" class="img-fluid" alt=""/>
								</div>
								<div class="col-lg-7 col-md-12 col-sm-12">
									 
									  			<button class="accordion">How local SEO is different from regular SEO?</button>
												<div class="panel">
													<p>SEO is about getting your website found in search engines like Google for relevant search phrases. With local SEO, there’s a slight twist. Instead of focusing exclusively on your website, the focus is also on optimizing your local business profiles such as Google My Business listing.</p>
												</div>

												<button class="accordion">What Types of Businesses Can Use Local SEO?</button>
												<div class="panel">
													<p>Unless you are a 100% e-commerce business with no physical location for customers to visit, you use to reap the benefits of local SEO. Local SEO service is a good opportunity for your business no matter what industry it is in to get targeted traffic.</p>
												</div>
												
												<button class="accordion">Can I compete in cities and towns outside my physical location?</button>
												<div class="panel">
													<p>Local SEO is greatly affected by the location of your store or office. This is important to keep the relevancy of local business results for searchers. If you are trying to rank in a location other than your local address, you need to focus on traditional SEO.</p>
												</div>
												
												
  										

								</div>
							</div>

						</div>
				</section>

				<section class="clientsec">
						<h2> Some of Our Esteemed Clients </h2>
							<div class="clientinnersec">
								<div class="clientinnerleftsec">
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg1.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg2.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg3.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg4.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg5.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg6.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg7.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg8.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg9.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg10.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg11.jpg" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg12.jpg" alt="client icon"/></a></li>
									</ul>
								</div>	
							</div>		
				</section>

				<section class="testimonial">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 d-none d-lg-block">
									<ol class="carousel-indicators tabs">
										<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">
											<figure>
												<img src="https://livedemo00.template-help.com/wt_62267_v8/prod-20823-one-service/images/testimonials-01-179x179.png" class="img-fluid" alt="">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="1">
											<figure>
												<img src="https://livedemo00.template-help.com/wt_62267_v8/prod-20823-one-service/images/testimonials-02-306x306.png" class="img-fluid" alt="">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="2">
											<figure>
												<img src="https://livedemo00.template-help.com/wt_62267_v8/prod-20823-one-service/images/testimonials-03-179x179.png" class="img-fluid" alt="">
											</figure>
										</li>
									</ol>
								</div>
								<div class="col-lg-6 d-flex justify-content-center align-items-center i-can-has-a-colored-thing">
									<div id="carouselExampleIndicators" data-interval="false" class="carousel slide" data-ride="carousel">
										<h3>Words From</h3>
										<h1><span class="highlight">Our Clients</span></h1>
										<h4>Our Valued Customers Believe In Us & 
												This Is What Keeps Us Going</h4>
										<div class="carousel-inner">
											<div class="carousel-item active">
												<div class="quote-wrapper">
													<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
															It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																												</p>
													<h3> Evrim Oralkan </h3>
													<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
										</div>
										<ol class="carousel-indicators indicators">
											<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
										</ol>
									</div>
								</div>
							</div>
						</div>
				</section>

				<section class="seventhsec">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 col-md-12 col-sm-12">
									<h3>We <i class="fas fa-heart hearticonsty"></i> <br> what we do </h3>
								</div>
								<div class="col-lg-6 col-md-12 col-sm-12">
									<h4>In a world of infinite possibilities, do not limit yourself.</h4>
									<div class="indibuttons">
											<button class="btn-hover color-1"> Let’s Talk  
												<span class="roundshapebutton roundshapearrow"> 
													<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
														<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
													</svg>
												</span>
											</button>
										</div>
								</div>
							</div>
						</div>
				</section>      

@endsection