@extends('layouts.master')




@section('header')
@section('title', 'Web Development Services -Web Application Development & Designing')
@section('meta' , "SeoEaze's is providing Web Development Services includes Web application development with wordpress, joomla, php, magento based Web designing service & more")

@section('hreflangs')
    <link rel="canonical" href="https://www.seoeaze.com/web_development_service" />
@endsection

<!-- Start Breadcrumbs Schema -->
<script type="application/ld+json">
{
  "@context": "https://schema.org/", 
  "@type": "BreadcrumbList", 
  "itemListElement": [{
    "@type": "ListItem", 
    "position": 1, 
    "name": "Home",
    "item": "https://www.seoeaze.com"  
  },{
    "@type": "ListItem", 
    "position": 2, 
    "name": "Web Development Service",
    "item": "https://www.seoeaze.com/web_development_service"  
  }]
}
</script>
<!-- End Breadcrumbs Schema -->
<!-- FAQ Schema Start -->
<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What type of result can I expect from PPC Ads campaigns?","acceptedAnswer":[{"@type":"Answer","text":"Website traffic and conversions are the key performance indicators we look at. The answer depends on what your business goals are and how much traffic or conversion is expected."}]},{"@type":"Question","name":"How much traffic can I expect from PPC?","acceptedAnswer":[{"@type":"Answer","text":"The amount through PPC received every month will vary depending on:\n1. How effective your PPC campaigns are\n2. You PPC advertising budget"}]},{"@type":"Question","name":"Is advertising with Google expensive?","acceptedAnswer":[{"@type":"Answer","text":"Pay per click ad model is expensive than other methods of advertising and due to stiff competition to rank in Google search results, it can be expensive to advertise with the search giant. However, the traffic you receive will be high quality leading to more sales and conversion."}]}]}</script><!-- Generated by https://www.seoeaze.com/ -->
	<!-- FAQ Schema End -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css" integrity="sha512-UTNP5BXLIptsaj5WdKFrkFov94lDx+eBvbKyoe1YAfjeRPC+gT5kyZ10kOHCfNZqEui1sxmqvodNUx3KbuYI/A==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" integrity="sha512-OTcub78R3msOCtY3Tc6FzeDJ8N9qvQn1Ph49ou13xgA9VsH9+LRxoFU6EqLhW4+PKRfU+/HReXmSZXHEkpYoOA==" crossorigin="anonymous" />


@show

@section('content')
@php
use  PulkitJalan\GeoIP\GeoIP;
$geoip = new GeoIP();
$geoip->setIp(\Request::ip());
$country_code = $geoip->getCountryCode();
@endphp
<section class="webdesignanddevelopmentsec">
					<div class="container">
						<div class="webdesignanddevelopmentsec_innersec">
								
								<div class="webdesignanddevelopmentsec_innerleftsec i-can-has-a-colored-thing">
								<h2><span class="highlight"> Website Design and <br> Development Solutions </span> </h2>
								<p> Creating client-focused, customer-centric website solutions for over a decade. Let’s start your digital landscape adoption.</p>
								<div class="indibuttons pb-5">
								<a href="javascript:;" data-toggle="modal" data-target="#myModal">
									<button class="btn-hover color-1">  GET Started Now!
										<span class="roundshapebutton roundshapearrow"> 
											<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
												<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
											</svg>
										</span>
									</button></a>
								</div>
							</div>
							<div class="webdesignanddevelopmentsec_innerrightsec">
									
									<div class="blockchain-earth" data-second-sphere="true" data-sphere-color="#5ebafa" data-sphere-width="750">
										<canvas width="750" height="750" style="width: 450px; height: 450px;"></canvas>
									</div>
							</div>
						</div>
					</div>
</section>


<!-- Start OF Service Section -->

<section class="webdesignanddevelopmentsecndsec">
<h2> What Do We Do For Web Development? </h2>
<P>Redefining the standards of web development with our bespoke services. SeoEaze offers complete web development solutions across industries. </P>
				<section classs="testimonials">
					<div class="container">
					<div class="row">
						<div class="col-sm-12">
						<div id="customers-testimonials" class="owl-carousel">

							<!-- Service 1 -->
							<div class="item">
							<div class="testimonial-name"> Designing </div>
							<div class="shadow-effect">
								<img class="img-circle" src="assets/img/services/services-img1.webp" alt="">
								<p>Our designers create user friendly and intuitive designs for you. Our work speaks of innovation and our professionals meet industry standards to offer the best solutions. </p>
							</div>
							</div>

							<!-- Service 2 -->
							<div class="item">
							<div class="testimonial-name"> Development </div>
							<div class="shadow-effect">
								<img class="img-circle" src="assets/img/services/services-img2.webp" alt="">
								<p>With our easy to use CMS, you will get only the best for your website. From engaging content to app development and more, our professionals provide the most comprehensive web development solutions. </p>
							</div>
							
							</div>

							<!-- Service 3 -->
							<div class="item">
							<div class="testimonial-name"> Maintenance </div>
							<div class="shadow-effect">
								<img class="img-circle" src="assets/img/services/services-img3.webp" alt="">
								<p>We further maintain and manage your sites, keeping them updated and optimized. From adding pages to text updates and more, we help you to manage your site in the best way.</p>
							</div>
							
							</div>

							<!-- Service 4 -->
							<div class="item">
							<div class="testimonial-name"> Versatility </div>
							<div class="shadow-effect">
								<img class="img-circle" src="assets/img/services/services-img4.webp" alt="">
								<p>At SEOEaze, our experts provide you with multiple options for a site, be it the most advanced Laravel or Redient.js or the traditional WordPress and PHP, our team has experience for all development frameworks.</p>
							</div>
							
							</div>

							<!-- Service 5 -->
							<div class="item">
							<div class="testimonial-name"> Affordable pricing </div>
							<div class="shadow-effect">
								<img class="img-circle" src="assets/img/services/services-img1.jpg" alt="">
								<p>At SEOEaze, our experts provide you with multiple options for a site,You can be sure of getting the best price for your website design and development requirements. We provide different affordable plans and packages to suit your needs. be it the most advanced Laravel or Redient.js or the traditional WordPress and PHP, our team has experience for all development frameworks. </p>
							</div>
							
							</div>


						</div>
						</div>
					</div>
					</div>
				</section>


<!-- END OF Service Section -->
</section>



<section class="webdesignanddevelopmentthirdsec">
<div class="container">
	<div class="webdesignanddevelopmentthirdinnersec">
		<ul class="infoGraphic"> 
			<li>
			<div class="numberWrap">
				<div class="number fontColor1">1</div>
				<div class="coverWrap">
				<div class="numberCover"></div>
				</div>
			</div>
			<div class="content">
				<div class="icon">
					<img class="img-circle" src="assets/img/webdesignanddevelopment/qualityservicesicon.png" alt="">
				</div>
				<h2>QUALITY SERVICES</h2>
				<p>SEOEaze provides quality and up-to-date web design and development solutions. You can be sure of getting top class services for your website.</p>
			</div>
			</li>
			<li>
			<div class="numberWrap">
				<div class="number fontColor2">2</div>
				<div class="coverWrap">
				<div class="numberCover"></div>
				</div>
			</div>
			<div class="content">
				<div class="icon">
					<img class="img-circle" src="assets/img/webdesignanddevelopment/competitivepricingicon.png" alt="">
				</div>
				<h2>COMPETITIVE PRICING</h2>
				<p>We bet you won’t get better prices anywhere else. Our plans and packages are affordable and will leave you satisfied with the results.</p>
			</div>
			</li>
			<li>
			<div class="numberWrap">
				<div class="number  fontColor3">3</div>
				<div class="coverWrap">
				<div class="numberCover"></div>
				</div>
			</div>
			<div class="content">
				<div class="icon">
					<img class="img-circle" src="assets/img/webdesignanddevelopment/experinceprofessionalsicon.png" alt="">
				</div>
				<h2>EXPERIENCED PROFESSIONALS</h2>
				<p>Our team of professionals work closely to make your business a hit in this competitive world. Our years of expertise speak for itself through the results we deliver.</p>
			</div>
			</li>
		</ul>
</div>
</div>
</section>


<section class="container-fluid dev-sev-sec">
			<div class="row">
				<div class="col-xl-12 col-md-12 col-sm-12 text-center">
					<div class="col-left1">
						<h3>BEST <span> WEBSITE DEVELOPMENT </span>FOR YOU</h3>
						<p>
							As a top web development company, we have a dedicated team of experts who create powerful websites using clean and bold designs. 
							We believe that a good online presence starts with a great looking, professional website. Your site is the place that mirrors your
							business goals and objectives and thus we develop informative, attractive and appealing website for you! 

						</p>
						<a href="javascript:;" data-toggle="modal" data-target="#myModal">
                <div class="indibuttons">
                   <button type="submit" class="btn-hover color-1" onclick="openGetQuoteWebDev()"> Get a quote now
                        <span class="roundshapebutton roundshapearrow"> 
                            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
                            </svg>
                        </span>
                    </button></a>
                </div>
            
					</div>
				</div>
				
			</div>

</section>

<section class="webdesignouresentprosec">
			<div class="container i-can-has-a-colored-thing">
							<h4> OUR RECENT CREATIVE PROJECT </h4>
							<h2> Let our work help you decide better !<br></h2>
							<div class="row mb-4 mt-5">
									<div class="col-lg-4 col-md-12 col-sm-12"> 
                    <div class="card p-2">
											<img src="assets/img/webdesignanddevelopment/website-img1.webp" alt="">
                    </div>
									</div>

								<div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="card p-2">
											<img src="assets/img/webdesignanddevelopment/website-img2.webp" alt="">
                    </div>
								</div>

								<div class="col-lg-4 col-md-12 col-sm-12">
										<div class="card p-2">
											<img src="assets/img/webdesignanddevelopment/website-img3.webp" alt="">
                    </div>
								</div>
							</div>
				</div>
	</section>
  <section class="container-fluid aboutuswebdevelopmentsec text-center">

<div class="row">
    <div class="col-xl-4 col-md-4 col-sm-12 text-center">
      <img src="assets/img/webdesignanddevelopment/left-img.png" alt="">
    </div>
    <div class="col-xl-8 col-md-8 col-sm-12 text-center">
            
      <h2> About SEOEAZE </h2>
      <p>
        We are an established ISO certified company with 14 years of endeavouring experience into Enterprise Level Software Development, Web, Ecommerce and Mobility solutions. 
        We weave inventive and innovative ideas into reality.

      </p>
      <div class="row">
        <div class="col-xl-3 col-md-3 col-sm-6 text-center p-0 m-0">
          <h2>50 <span class="about-spanClass"> + </span></h2>
          <p>Team members</p>
        </div>
        <div class="col-xl-4 col-md-4 col-sm-6 text-center p-0 m-0">
          <h2>14 <span class="about-spanClass"> Years </span></h2>
          <p>of Industry Experience</p>
        </div>
        <div class="col-xl-3 col-md-3 col-sm-6 text-center p-0 m-0">
          <h2>850 <span class="about-spanClass">+ </span></h2>
          <p>Prestigious clients</p>
        </div>
        <div class="col-xl-2 col-md-2 col-sm-6 text-center p-0 m-0">
          <h2>20<span class="about-spanClass">+</span></h2>
          <p>Awards</p>
        </div>
      </div>		
    </div>
  </div>
</section>


<section class="frequentlyaskedquestionsec">
						<div class="container i-can-has-a-colored-thing">
								<h2> Frequently <br> <span class="highlight"> Asked Questions</span> </h2>
							<div class="row">

								<div class="col-lg-5 col-md-12 col-sm-12" style="margin-top: -50px;">
									<img src="assets/img/seo_packages_img/faqsleftsec.gif" class="img-fluid" alt=""/>
								</div>
								<div class="col-lg-7 col-md-12 col-sm-12">
									  <!-- start Frequently Asked Questions-->
									  			<button class="accordion">How much does a new website cost?</button>
												<div class="panel">
													<p>There is no fixed price for website development, as our services are fully customizable and tailored to our client’s requirements. The overall cost of your website will depend on requirements, technology, and scale of the website.<br>
													At SeoEaze, we ensure to keep the pricing lowest for you while offering an optimum solution for achieving the desired results.</p>
												</div>

												<button class="accordion">How long does it take to build a website?</button>
												<div class="panel">
													<p>Just as pricing varies, the development time for a website can be anywhere between 1 to 4 months, depending on the requirements. As a professional website development company, SeoEaze follows industry standard practices from planning to writing code and testing. Websites with basic functionalities have quicker turnaround as compared to sophisticated websites. </p>
												</div>
												
												<button class="accordion">Will you maintain my site for me?</button>
												<div class="panel">
													<p>As maintenance is essential to ensure your website is operational 24/7 and protected against cyber attacks, we offer professional website maintenance as well. Our engineers use best-in-class management and security tools to ensure the website’s security, support traffic boost, and facilitate stabilized growth.</p>
												</div>

												<button class="accordion">For How Long You Will Provide Support After Completion Of Website?</button>
												<div class="panel">
													<p>We provide 6 months free technical support with every web developmet project, apart from that you can pick for for website maintenance for regular support. </p>
												</div>

												
												
												
  										<!-- end Frequently Asked Questions-->

								</div>
							</div>

						</div>
				</section>

				<section class="localseoseventhsec">
					<div class="row">
						<div class="col-lg-5 col-md-12 col-sm-12">
							<div class="localseoseventhleftsec">
									<canvas id="starfield" width="2000" height="auto"></canvas>
									<div class="stage">
									  <div class="localseoseventhsecbody">
										<div class="top">
										  <div class="light"></div>
										  <div class="antenna"></div>
										  <div class="base2"></div>
										  <div class="base1"></div>
										</div>
										<div class="glass">
										  <div class="reflection"></div>
										</div>

										<div class="boster bosterL"></div>
										<div class="boster bosterR"></div>
										<div class="ring">
										  <div class="s1"></div>
										  <div class="s1"></div>
										  <div class="s1"></div>
										  <div class="s1"></div>
										  <div class="s1"></div>
										  <div class="s1"></div>
										  <div class="s1"></div>
										</div>
										<div class="fire">
										  <div class="flame h1"></div>
										  <div class="flame h2"></div>
										  <div class="flame h3"></div>
										  <div class="flame h4"></div>
										  <div class="flame h5"></div>
										</div>
									  </div>
									</div>
								</div>
							</div>
							<div class="col-lg-7 col-md-12 col-sm-12">
									<div class="localseoseventhrightsec">
										<h2>Need Help In Web Development?</h2>
										<h4>Call us Now To Discuss Your Project on </h4>
										@if ($country_code == "IN")
                                        <a href="tel:8375011200"><h2>83750-11200</h2></a>
                                        @else
                                        <a href="tel:+18447363293"><h2>844-SEO-EAZE</h2></a>
                                        @endif
										
									</div>
							</div>


					</div>
				</section>

				<section class="clientsec">
						<h2> Some of Our Esteemed Clients </h2>
							<div class="clientinnersec">
								<div class="clientinnerleftsec">
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg1.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg2.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg3.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg4.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg5.webp" alt="client icon"/></a></li>
									</ul>
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg6.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg7.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg8.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg9.webp" alt="client icon"/></a></li>
									</ul>
									<ul>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg10.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg11.webp" alt="client icon"/></a></li>
										<li><a href=""><img src="assets/img/seo_packages_img/clientsimg12.webp" alt="client icon"/></a></li>
									</ul>
								</div>	
							</div>		
				</section>

				<section class="testimonial">
						<div class="container">
							<div class="row">
								<div class="col-lg-6 d-none d-lg-block">
									<ol class="carousel-indicators tabs">
										<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-01-179x179.webp" class="img-fluid" alt="seoeaze testimonial 1">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="1">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-02-306x306.webp" class="img-fluid" alt="seoeaze testimonial 2">
											</figure>
										</li>
										<li data-target="#carouselExampleIndicators" data-slide-to="2">
											<figure>
												<img src="assets/img/seo_packages_img/testimonials-03-179x179.webp" class="img-fluid" alt="seoeaze testimonial 3">
											</figure>
										</li>
									</ol>
								</div>
								<div class="col-lg-6 d-flex justify-content-center align-items-center i-can-has-a-colored-thing">
									<div id="carouselExampleIndicators" data-interval="false" class="carousel slide" data-ride="carousel">
										<h3>Words From</h3>
										<h1><span class="highlight">Our Clients</span></h1>
										<h4>Our Valued Customers Believe In Us & 
												This Is What Keeps Us Going</h4>
										<div class="carousel-inner">
											<div class="carousel-item active">
												<div class="quote-wrapper">
													<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
															It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																												</p>
													<h3> Evrim Oralkan </h3>
													<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
											<div class="carousel-item">
												<div class="quote-wrapper">
														<p>My site travertinemart.com has gained high rankings on Google within 8 months of trying their dedicated SEO plan. Anki was very helpful in creating a customized SEO package for me. 
																It was a great experience working with his team. Now my site is user friendly and ranks on first page of major search engines.
																													</p>
														<h3> Evrim Oralkan </h3>
														<p> Travertine Mart </p>
												</div>
											</div>
										</div>
										<ol class="carousel-indicators indicators">
											<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
											<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
										</ol>
									</div>
								</div>
							</div>
						</div>
				</section>


<!-- Start Form sec -->
<section class="container-fluid ourform-sec text-center" id="conform" id="audit">

		<div class="row">
		
			<div class="col-xl-6 col-md-6 col-sm-12 text-left">
				<div class="col-con-left">
												<h4>Contact us</h4>
												<h3>Talk to us about your project</h3>
												
												<h5>Phone Numbers</h5>
												@if ($country_code == "IN")
												<p>India: +91-837-501-1200<br>US: +1-844-736-3295</p>
												@else
												<p>844-736-3295</p>
												@endif
												
												<h5>Skype</h5>
												<p>seoeaze</p>
												
												<h5>Emails</h5>
												<p>info@seoeaze.com</p>
												
											</div>
			</div>
			<div class="col-xl-6 col-md-6 col-sm-12">
				<div class="col-con-right text-left">
                                <div class="form-col">
                                   <form action="/web_development_post" method="post" id="msform" role="form" >
                                       {{ csrf_field()}}
                                        <div class="form-row">
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group text-left">
                                                    <label for="inputAddress">Name<span style="color:#f03;">*</span></label>
                                                    <input type="text" name="name" class="form-control" placeholder="Type Your Name" required="">
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group text-left">
                                                    <label for="inputAddress">Email<span style="color:#f03;">*</span></label>
                                                    <input type="email" name="email" value="" class="form-control" placeholder="Type Your Email" required="">
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group text-left">
                                                    <label for="inputAddress">Company Name<span style="color:#f03;">*</span></label>
                                                    <input type="text" name="company_name" value="" class="form-control" placeholder="Type Your Company Name" required="">
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group text-left">
                                                    <label for="inputAddress">Select Your Design Type</label>
                                                    <select style="margin: 1%;width: 98%;float: left;" name="website_type" id="">
                                                        <option value="New Website" disabled selected>- Website Type -</option>
                                                        <option value="New Website">New Website</option>
                                                        <option value="Redesign">Redesign</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group text-left">
                                                    <label for="inputAddress">Select Your Budget </label>
													@if ($country_code == "IN")
													<select style="margin: 1%;width: 98%;float: left;" name="budget" id="">
													<option value="" disabled selected>- Budget -</option>
													<option value="500">Below ₹20000</option>
										            <option value="1000">₹20000 - ₹50000</option>
										            <option value="2500">₹50000 - ₹100000</option>
										            <option value="5000">₹100000 - ₹500000</option>
										            <option value="20000">₹500000+</option>
													</select>
													@else
                                                     <select style="margin: 1%;width: 98%;float: left;" name="budget" id="">
                                                        <option value="" disabled selected>- Budget -</option>
                                                        <option value="$5,000-10,000">$5,000-10,000</option>
                                                        <option value="$10,000-25,000">$10,000-25,000</option>
                                                        <option value="$25,000-50,000">$25,000-50,000</option>
                                                        <option value="$50,000-100,000">$50,000-100,000</option>
                                                        <option value="$100,000-250,000">$100,000-250,000</option>
                                                        <option value="$250,000-500,000">$250,000-500,000</option>
                                                        <option value="$500,000-1M">$500,000-1M</option>
                                                    </select>
													@endif
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group text-left">
                                                    <label for="inputAddress">Select Your Project Timeline </label>
                                                    <select style="margin: 1%;width: 98%;float: left;" name="project_timeline" id="">
                                                        <option value="" disabled selected>- Project Timeline -</option>
                                                        <option value="Immediate">Immediate</option>
                                                        <option value="1-3 Months">1-3 Months</option>
                                                        <option value="3-6 Months">3-6 Months</option>
                                                        <option value="6-12 Months">6-12 Months</option>
                                                        <option value="+1 Year">+1 Year</option>
                                                    </select>
                                                </div>
                                            </div>
                                           
                                            
                                            <div class="col-lg-12 col-md-12 col-sm-12">
                                                <div class="form-group text-left">
                                                    <label for="inputAddress">Share Your Project Details </label>
                                                     <textarea name="other_notes" style="height: 100px;margin: 1%;width: 98%;float: left;" placeholder="What is your core need? For example is this a website project? Do you need to get more visibility to your site? Want more traffic for your ecommerce? Etc." name="" id="" cols="30" rows="10"></textarea>
                                                </div>
                                            </div>

                                        </div>

                                        <div class="indibuttons">
                                          <button type="submit" class="btn-hover color-1"> Submit Request
                                            <span class="roundshapebutton roundshapearrow"> 
                                              <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"></path>
                                              </svg>
                                            </span>
                                          </button>
                                        </div>


                                        
                                    </form>
                                </div>
                            </div>
			</div>
			
		</div>

</section>
<!-- End Form sec -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.js" integrity="sha512-gY25nC63ddE0LcLPhxUJGFxa2GoIyA5FLym4UJqHDEMHjp8RET6Zn/SHo1sltt3WuVtqfyxECP38/daUc/WVEA==" crossorigin="anonymous"></script>

<script>
	jQuery(document).ready(function($) {
  "use strict";
  //  TESTIMONIALS CAROUSEL HOOK
  $('#customers-testimonials').owlCarousel({
      loop: true,
      center: true,
      items: 3,
      margin: 0,
      autoplay: false,
      dots:true,
      autoplayTimeout: 8500,
      smartSpeed: 450,
      responsive: {
        0: {
          items: 1
        },
        768: {
          items: 2
        },
        1170: {
          items: 3
        },
		1270: {
          items: 3
        }
      }
  });
});


</script>
 

<!-- Third sec start  -->
<script>
	///////////////////////////////////////////
// Resizing Slider

const inputs = document.querySelectorAll("input");
const div = document.querySelector("li");

function handleInputChange() {
  const units = this.dataset.units || "";

  document.documentElement.style.setProperty(
    `--${this.name}`,
    this.value + units
  );
}

inputs.forEach((input) => input.addEventListener("input", handleInputChange));
var range = $("input#range"),
  value = $(".range-value");
value.html(range.attr("value"));
range.on("input", function () {
  value.html(this.value);
});

</script>



@endsection