@extends('layouts.master')


@section('title', 'Web Content Writing Services -Buy Articles, eBook, Blog Posts, Reviews')
@section('meta' , "SeoEaze offering all Web Content Writing Services, You can buy article writing service, Blog posts writing, Press Releases, eBooks, Product Reviews & more..")





@section('header')

@section('hreflangs')
    <link rel="alternate" href="https://www.seoeaze.com/content_writing_service" hreflang="en-us" />
    <link rel="alternate" href="https://www.seoeaze.in/content_writing_service" hreflang="en-in" />
	<link rel="alternate" href="https://www.seoeaze.co.uk/content_writing_service" hreflang="en-gb" />
	<link rel="alternate" href="https://www.seoeaze.com/content_writing_service" hreflang="x-default" />
@endsection
<!-- Start Breadcrumbs Schema -->
<script type="application/ld+json">
{
  "@context": "https://schema.org/", 
  "@type": "BreadcrumbList", 
  "itemListElement": [{
    "@type": "ListItem", 
    "position": 1, 
    "name": "Home",
    "item": "https://www.seoeaze.com"  
  },{
    "@type": "ListItem", 
    "position": 2, 
    "name": "Content Writing Service",
    "item": "https://www.seoeaze.com/content_writing_service"  
  }]
}
</script>
<!-- End Breadcrumbs Schema -->

<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Will the content be original?","acceptedAnswer":[{"@type":"Answer","text":"100% Guaranteed. At SeoEaze, we have a stringent 'no plagiarism policy' which assures our clients that our content writing services are reliable. We make use of premium plagiarism tools like Copyscape, ensuring delivery of only original high-quality content written by native writers.\n"}]},{"@type":"Question","name":"How do I know that I will get top quality content?","acceptedAnswer":[{"@type":"Answer","text":"In over a decade of our existence, SeoEaze content writing services have served over 1500 global clients who speak of our quality services. Our content offers high value and so almost all the clients are our long-time partners.\n"}]},{"@type":"Question","name":"What industries does SeoEaze cater to?","acceptedAnswer":[{"@type":"Answer","text":"We have expert content writers who have experience and knowledge of various topics and subjects. Our native writers have in-depth knowledge of several industries spanning across IT, real estate, education, eCommerce, tourism, hospitality, healthcare and others. When you hire us, we match your project with the best-suited writers who are aware of terminologies and technicalities of your industry.\n"}]},{"@type":"Question","name":"Do you charge extra for revisions?","acceptedAnswer":[{"@type":"Answer","text":"At SeoEaze, we ensure that there are no hidden costs that surprise our clients. Every cost will be detailed upfront when you hire us. For minor revisions and editing, there are no additional costs. Our editors make sure that you receive error-free and accurate copy in the right format. But if you need any revision done, we get at it as soon as we get your feedback.\n"}]}]}</script><!-- Generated by https://www.seoeaze.com/ -->

@show

@section('content')

<!-- slider area bar start-->
	

	<main class="header-video-sec">
			
			<!-- Vedio Content Section Start  -->
			  <div class="container-flude">
			  
			  		<div class="container">
			  			<div class="row indexheader-video-sec-inner-sec">
				  			<div class="col-lg-7 col-md-7 col-sm-12 header-video-sec-inner-leftsec">

				  				<h1>Content Writing Service  </h1>
									<h2> Quality Content You Need </h2>
									<p>Get content that builds your name and sells, delivered by the best writers <br>Best content writing services for search engine optimized content</p>
										<div class="header-bulletsec">
										<div class="header-bulletsec-colleft">
											<ul>
												<li> Subject matter-expert writers</li>
												<li> Experience writers from all industries </li>
												<li>100% original, plagiarism free content </li>
											</ul>
										</div>
										<div class="header-bulletsec-right">
											<ul>
												<li> Customized powerful content solutions </li>
												<li> Get your content on time </li>
												<li> Only pay for writing you love </li>
											</ul>
										</div>
									</div>
									<span>  
										<a href="#pricing">
											<button class="button1"> Get Started </button>
										</a> 
									    <a href="#samples">
											<button class="button2"> Writing Samples </button>
										</a>
										<a  href="#benefits">
											<button class="button1"> Key Benefits </button>
										</a> 
									</span><br><br><br>
				  			</div>

				  			<div class="col-lg-5 col-md-5 col-sm-12 header-video-sec-inner-rightsec">
								<div class="imgblockright">	  				
									<img src="assets/img/content-writing-services/content_writing_service_img1.png" alt="content writing service img" class="img-flude">
								</div>
				  			</div>
					</div>
			  	</div>
				
			
			</div>
        <!-- Vedio Content Section End -->
</main>
<!-- slider area bar end-->

<!-- Start Breadcrumbs Schema -->
<div class="container-fluid breadcrumb-sec">
	<div class="container">
		   <ol class="breadcrumb breadcrumb-arrow">
			<li><a href="/">Home</a></li>
			<li><a href="#">Services</a></li>
			<li class="active"><span> Content Writing Service </span></li>
		   </ol>
	</div>
</div>
<!-- End Breadcrumbs Schema -->

<!-- Start Key services sec -->

	<div class="container-fluid" style="border-bottom: 5px solid #eaeaea;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
				    
						    <div class="parent-box8 topSlider8 owl-carousel">

                                <div class="box8 mx-auto d-block">
									<div class="tophoriscrollsec-box text-center">
										<a href="#tab2" id="ui-id-#tab2">
										 <img src="./assets/img/content-writing-services/icons/blog-icon.png">
										 <h2>Blog Posts </h2>
										 </a>
									 </div>
                                </div>
								<div class="box8 mx-auto d-block">
                                     <div class="tophoriscrollsec-box text-center">
										<a href="#tab3" id="ui-id-3">
										 <img src="./assets/img/content-writing-services/icons/web-content.png">
										 <h2> Web Content </h2>
										</a>
									 </div>
                                </div>
                                <div class="box8 mx-auto d-block">
                                     <div class="tophoriscrollsec-box text-center">
                                         <a href="#tab4" id="ui-id-4">
										 <img src="./assets/img/content-writing-services/icons/product-review.png">
										 <h2>Product Reviews </h2>
										 </a>
									 </div>
                                </div>
								<div class="box8 mx-auto d-block">
                                     <div class="tophoriscrollsec-box text-center">
                                         <a href="#tab5" id="ui-id-5">
										 <img src="./assets/img/content-writing-services/icons/e-books-icon.png">
										 <h2>eBooks</h2>
										 </a>
									 </div>
                                </div>
								<div class="box8 mx-auto d-block  text-center">
                                     <div class="tophoriscrollsec-box">
                                         <a href="#tab6" id="ui-id-6">
										 <img src="./assets/img/content-writing-services/icons/press-release.png">
										 <h2> Press Releases </h2>
										 </a>
									 </div>
                                </div>
                                
							</div>
				</div>
			</div>
		</div>
	</div>


<!-- End Key services sec -->


<!-- Start Content Creation Simple sec -->

	<div class="container-fluid contentcreationsimple-sec">
		<div class="container">
			<h2>Quality Content That Grows Your Business</h2>
			<h3>Content marketing helps businesses of all sizes <br>Here are the important numbers you must know about content writing services</h3>
			<span class="bottomLineImgStyle"></span>
			<div class="row">
    			<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block"> 
        			<figure>
        				<img src="assets/img/content-writing-services/content-creation-sample.jpg">
        			</figure>
    			</div>
    			<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block"> 
                <p><strong>126% MORE LEADS</strong> are generated by small businesses from a blog compared to other mediums</p>
                <p><strong>2nd MOST SUCCESSFUL LEAD GENERATION tactic.Content marketing is only below email marketing in lead generation</p>
                <p><strong>3x MORE LEADS</strong> are generated with content marketing compared to any traditional outbound approach</p>
                <p><strong>62% LESS COST</strong> is incurred when you engage in content marketing</p><br>
                <p>You do not need more reasons than these to invest in high-quality content development. SeoEaze&rsquo;s web content writing services are made to suit your requirements without getting over budget.</p>
    			</div>
			</div
			<div class="row">
			    <div class="col-lg-12 col-md-12 col-sm-12">
			     <br><br>
                <p>Delegate your content requirements to our industry skilled writers who deliver your content on time. Whatever industry you are in, our writers can easily create content that engages your audience.</p>
                <br><br>
			    </div>
			</div>
			
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					
						<!------ Include the above in your HEAD tag ---------->

							<section id="tabs" class="project-tab">
										<div class="container" style="background: white;">
											<div class="row">
												<div class="col-md-12">
													<nav>
														<div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
															<a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">SEO Content Services </a>
															<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Enterprise Content Services</a>
															
														</div>
													</nav>
													<div class="tab-content" id="nav-tabContent">
														<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">

																<div class="row pt-5">
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-1.png"></figure>
																			<h3>High quality </h3>
																			<p>
																				We offer high quality, keyword-rich SEO content for your site/blog. Use our content to convert. 
																			</p>
																		</div>
																	</div>
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-2.png"></figure>
																			<h3>SEO Optimized </h3>
																			<p>
																				We ensure that the content we deliver is SEO optimized to get you on top. Our professionals take extra efforts to deliver the BEST. 
																			</p>
																		</div>
																	</div>
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-3.png"></figure>
																			<h3>Original and targeted </h3>
																			<p>
																				At SEOEaze, you can be sure of getting original content writing services at affordable rates. Our writers create fresh, targeted content for your needs. 
																			</p>
																		</div>
																	</div>
																</div>
																<div class="row mx-auto d-block mb-5 mt-2">
																	<a href="#pricing"><button type="button" class="btn btn-danger but-style"> Order Content </button></a>
																</div>

														</div>
														<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
															
																<div class="row pt-5">
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-4.png"></figure>
																			<h3>Complex projects  </h3>
																			<p>
																				Our professionals add their expertise to your complex projects, delivering high quality content writing. They can handle any sort of complicated content with ease. 
																			</p>
																		</div>
																	</div>
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-5.png"></figure>
																			<h3>Fully managed  </h3>
																			<p>Our writing team is well aware of how to tackle your content programs. When you choose our enterprise content services, you get industry veterans writing your content. </p>
																		</div>
																	</div>
																	<div class="col-lg-4 col-md-6 col-sm-12 mx-auto d-block">
																		<div class="box">
																			<figure><img src="assets/img/content-writing-services/icons/icon-6.png"></figure>
																			<h3>Fast turnaround</h3>
																			<p>
																				We deliver most orders within 24-48 hours. Our team takes turnaround time very seriously and deliver fast yet professional results. 
																			</p>
																		</div>
																	</div>
																</div>
																<div class="row mx-auto d-block mb-5 mt-2">
																	<a href="/custom_content_writing_quotation"><button type="button" class="btn btn-danger but-style"> Request For Pricing </button></a>
																</div>
															
														</div>

													</div>
												</div>
											</div>
										</div>
									</section>
				</div>
			</div>
		</div>
</div>
<!-- End Content Creation Simple sec -->

<!-- START  Hire the Perfect Content Writer SECTION -->

<div class="container-fluid hirethepercerctcontentwriter-sec">
		<div class="container">
			
			
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 mx-auto d-block">
					<div class="hirethepercerctcontentwriter-innersec">
						<h2>Hire the <span> Right Content Writer </span> for Your Website </h2>
								<section class="py-4">
									<div class="row">
										<div class="col-md-12">
											<div class="d-flex">
												<ul id="tabsJustified" class="nav nav-pills flex-column">
													<li class="nav-item"><a href="" data-target="#home1" data-toggle="tab" class="nav-link text-uppercase active mb-1">Hire The Best </a></li>
													<li class="nav-item"><a href="" data-target="#profile1" data-toggle="tab" class="nav-link text-uppercase mb-1">Skilled professionals  </a></li>
													<li class="nav-item"><a href="" data-target="#messages1" data-toggle="tab" class="nav-link text-uppercase mb-1">Writers for all </a></li>
												</ul>
												<div class="tab-content pt-1 pl-5 w-100 text-left">
													<div id="home1" class="tab-pane fade active show">
														Do not hold up the flow of your project waiting for content. Hire the best writers from SeoEaze content writing service and let the wheels churning in no time. <br>
														<i>“Intelligently managed and relentlessly timeline content writing project management is what makes me come back for their content writing service again and again.”</i>
-Deborah 

													</div>
													<div id="profile1" class="tab-pane fade">
														No budget writers here! Only skilled native writers who understand your industry and have established a rapport of being the best in the business. <br> <br>
														
														<i>“Not only these guys are skilled but they actually killed the competition with their expert writing. I am glad to have reached them with my project.”</i><br>
														-Shauna Brown
													</div>
													<div id="messages1" class="tab-pane fade">
														We are confident to provide content for every possible niche. It doesn’t matter whether you are an ecommerce company or a petrochemical conglomerate, we have writers for all. <br>
														
														<i>“In my 15 years of running a digital marketing company, I have never partnered with any digital marketing agency as versatile as SeoEaze. They can handle whatever business content requirement you throw at them.”</i><br>
-George Cooper 

													</div>
												</div>
											</div>
										</div>
									</div>
								</section>
					</div>
				</div>
			</div>
		</div>
</div>

<!-- End  Hire the Perfect Content Writer SECTION -->



<!-- Pricing Table Start -->
<div class="container-fluid datablesec">
    
    <section class=" b-benefits-container f-benefits-container" style="padding:0;">
        <div class="container">
            <div class="col-sm-12"><h1 id="pricing" class="se_title_serv f-primary-b text-center pr_pl_scroll pt-5">Plans & Pricing</h1>
                <center style="height: 50px;"><span class="bottomLineImgStyle"></span></center>
                <div class="b-shortcode-example">
                    <div class="b-tabs f-tabs j-tabs b-tabs-reset b-tabs--secondary f-tabs--secondary ui-tabs ui-widget ui-widget-content ui-corner-all">
                        <div class="row" style="overflow: hidden">
                            <div class="container-fluid"><br>
                                <div class="panel-body">
                                    <div>
                                        <ul class="seo_navi nav-tabs">
                                            <div style="display: none;">                                                {{ $count = 0 }}                                            </div> @if($plan_name['0'] != '')                                                @foreach($plan_name as $plan)
                                                <div style="display: none;">                                                        {{ $count ++ }}                                                    </div>
                                                <li id="plans" class="for_tabs_un_line_li seo_service_accord_menu">
                                                    <span style="background-color: #42af9a; " class="for_tabs_un_line"></span>
                                                    <a data-toggle="tab" style="font-size: 18px;" href="#tab{{$count}}">
                                                        {{ $plan['plan_name'] }}
                                                    </a>
                                                </li>                                                @endforeach                                            @endif
                                        </ul>
                                        <div class="tab-content" style="background: #eaeaea; overflow: hidden; padding: 50px;">                                            @if($plan_name['0'] != '')                                                @include('parts.pricing_table')                                            @endif                                        </div>
                                    </div>
                                </div>
                                <div class="A4KZv8 visible_hide_class" data-reactid="2">
                                    <div class="AFyd3c" data-reactid="3">
                                        <div class="_1EA4La" data-reactid="4">
                                            <div class="_1-baVo" data-reactid="5">
                                                <img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0nMjAnIGhlaWdodD0nMjAnIHZpZXdCb3g9JzAgMCAyMCAyMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz4KCTxnPgoJCTxwYXRoIGQ9J00tMi0yaDI0djI0SC0yeicgZmlsbD0nbm9uZScvPgoJCTxwYXRoIGQ9J00xMCAwQzQuNDggMCAwIDQuNDggMCAxMHM0LjQ4IDEwIDEwIDEwIDEwLTQuNDggMTAtMTBTMTUuNTIgMCAxMCAwek04IDE1bC01LTUgMS40MS0xLjQxTDggMTIuMTdsNy41OS03LjU5TDE3IDZsLTkgOXonIGZpbGw9JyMyNkJDNEUnLz4KCTwvZz4KPC9zdmc+Cg==" class="_2P4x_N" data-reactid="6">
                                            </div>
                                            <div class="JAUzCh" data-reactid="7">Product Added to Cart Successfully.
                                            </div>
                                            <a href="/cart" class="checkout_link">
                                                <button name="checkout" type="submit" class="cta-full-width pull-right" id="checkout-link" style="width: 100%;margin-right: 10px; font-size: 1.6rem;margin-top: 10px;">
                                                    Go to cart
                                                </button>
                                            </a></div>
                                    </div>
                                </div>
                                <br></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
  </div>  
    
    
    
    
    
<script type="text/javascript" language="javascript"
        src="https://maps.google.com/maps/api/js?sensor=false&key=AIzaSyCfVS1-Dv9bQNOIXsQhTSvj7jaDX7Oocvs"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.13/d3.min.js"></script>
<!-- end Progress -->

<!-- Cart Functionality services -->
<script type="text/javascript"
        src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}"></script>
<script src="/assets/js/main.min.js"></script>
<!-- Pricing Table End -->

<!-- Start OUR WRITING SAMPLES Section -->
	<div class="container-fluid ourwritingsamples-sec" id="samples">
		<div class="container">
			<h2>OUR WRITING SAMPLES </h2>
			<span class="bottomLineImgStyle"></span>
			
			
			<div class="row">
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon1.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Blogs  Writing Samples</p>
						  <a href="/assets/cws_files/blog_posts.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon2.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Web Content Samples</p>
						  <a href="/assets/cws_files/web_content.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon3.png" alt="Cinque Terre"> 
						  <h3>Download</h3>
						  <p>Review Samples</p>
						  <a href="/assets/cws_files/product_reviews.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon4.png" alt="Cinque Terre" > 
						  <h3>Download</h3>
						  <p>Ebooks Samples</p>
						  <a href="/assets/cws_files/e_book.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-12 mx-auto d-block">
					<div class="ourwritingsamples-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/icon5.png" alt="Cinque Terre" > 
						  <h3>Download</h3>
						  <p>Press Release Samples</p>
						  <a href="/assets/cws_files/press_eleases.zip"><img src="assets/img/ourwritingsamples-sec/icons/button-bgimg.png" alt="our writing samples image button"></a>
					</div>
				</div>
			</div>
			
			

		</div>
	</div>
			
<!-- End OUR WRITING SAMPLES Section -->


<!-- Start bannerFirst Section -->

	<div class="container-fluid bannerFirst-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 30+ </h2>
					<p> Professional Writers </p>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 2000+ </h2>
					<p> Businesses Served </p>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
					<h2> 20M+</h2>
					<p> Words Written  </p>
				</div>
			</div>
		</div>
	</div>
	
<!-- End bannerFirst Section -->

<!-- Start card Section -->
	<div class="container-fluid card-sec">
		<div class="container">
	
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">Be #1 on Google</h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/Be1onGoogle-img.jpg" alt="Card image cap">
								<p class="card-text">With our top content writing services, you can be sure of getting high positions on popular search engines like Google. Our content writers create high quality, keyword-rich, SEO friendly and optimized content that gets noticed. Use our content writing to create website that Google will love. </p>
								
						  </div>
						</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">GET MORE TRAFFIC </h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/igniteyourcommunity-img.jpg" alt="Card image cap">
								<p class="card-text">With high quality content that is targeted and optimized, you definitely get more traffic and visitors. This makes your site/blog more popular and you start earning. <br><br><br><br></p>
						  </div>
						</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 mx-auto d-block">
						<div class="card">
						  
						  <div class="card-body">
								<h3 class="card-title">Convert More </h3>
								<img class="card-img-top" src="assets/img/ourwritingsamples-sec/achieve-content-marketing-success-img.jpg" alt="Card image cap">
								<p class="card-text"> With our engaging content and high traffic, you will definitely convert more. Not just this, you can also achieve successful content marketing with our amazing writing. <br><br><br><br></p>
								
						  </div>
						</div>
				</div>
				
			</div>


		</div>
	</div>
<!-- End card Section -->



<!-- Start FEATURES AND BENEFITS Section -->


	<div class="container-fluid featuresandbenefits-sec" id="benefits">
		<div class="container">
			<h2> FEATURES AND BENEFITS </h2>
			<span class="bottomLineImgStyle"></span>
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/expert-writing-icon.png" alt="Cinque Terre"> 
						  <h3> EXPERT WRITING </h3>
						  <p> Professional writers with many years of experience handle all types of content as per your requirements. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/revisionandediting-icon.png" alt="Cinque Terre"> 
						  <h3> REVISIONS AND EDITING </h3>
						  <p> Unlimited revisions are provided and content is submitted after proofreading from trained editors. </p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/originalcontent-icon.png" alt="Cinque Terre"> 
						  <h3> ORIGINAL CONTENT </h3>
						  <p> 100% original and SEO friendly content is what we offer. You can be sure of originality and high quality.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 mx-auto d-block">
					<div class="featuresandbenefits-innersec">
						  <img src="assets/img/ourwritingsamples-sec/icons/keywordoptimazation-icon.png" alt="Cinque Terre"> 
						  <h3> KEYWORD OPTIMIZED </h3>
						  <p> Our content is keyword-optimized to make it SEO friendly. </p>
					</div>
				</div>
			</div>
			
				
		</div>
	</div>

<!-- END FEATURES AND BENEFITS Section -->



<!-- Start Get Custom Quote Section -->
<div class="container-fluid getcustomquote-sec">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
					<h3> NOT SURE HOW MUCH TO PAY? </h3>
					<p> CONFUSED ABOUT WHICH PLAN TO CHOOSE?  </p>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
					<a href="" data-toggle="modal" data-target="#myModal"><img src="assets/img/ourwritingsamples-sec/getcustomquote-bannerimg.png"></a>
				</div>
			</div>
		</div>
</div>

<!-- End Get Custom Quote Section -->


<!-- Start FAQS RELATED TO CONTENT WRITING SERVICE Section -->

<div class="container-fluid faqscontentwriting-sec">
		<div class="container">
			
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block">
					<div class="faqscontentwriting-innersec">
                        <h2>Frequently Asked Questions </h2>
            			<span class="bottomLineImgStyle"></span>
						 <div id="accordion" class="accordion">
								<div class="card mb-0">
									<div class="card-header collapsed" data-toggle="collapse" href="#collapseOne">
										<a class="card-title"> 1. Will the content be original?</a>
									</div>
									<div id="collapseOne" class="card-body collapse show" data-parent="#accordion">
										<div class="card-body">100% Guaranteed. At SeoEaze, we have a stringent 'no plagiarism policy' which assures our clients that our content writing services are reliable. We make use of premium plagiarism tools like Copyscape, ensuring delivery of only original high-quality content written by native writers.</div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
										<a class="card-title"> 2. How do I know that I will get top quality content?</a>
									</div>
									<div id="collapseTwo" class="card-body collapse" data-parent="#accordion">
										<div class="card-body">In over a decade of our existence, SeoEaze content writing services have served over 1500 global clients who speak of our quality services. Our content offers high value and so almost all the clients are our long-time partners.</div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
										<a class="card-title"> 3. What industries does SeoEaze cater to?</a>
									</div>
									<div id="collapseThree" class="collapse" data-parent="#accordion">
										<div class="card-body">We have expert content writers who have experience and knowledge of various topics and subjects. Our native writers have in-depth knowledge of several industries spanning across IT, real estate, education, eCommerce, tourism, hospitality, healthcare and others. When you hire us, we match your project with the best-suited writers who are aware of terminologies and technicalities of your industry.</div>
									</div>
									<div class="card-header collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFourth">
										<a class="card-title"> 4. Do you charge extra for revisions?</a>
									</div>
									<div id="collapseFourth" class="collapse" data-parent="#accordion">
										<div class="card-body">At SeoEaze, we ensure that there are no hidden costs that surprise our clients. Every cost will be detailed upfront when you hire us. For minor revisions and editing, there are no additional costs. Our editors make sure that you receive error-free and accurate copy in the right format. But if you need any revision done, we get at it as soon as we get your feedback.</div>
									</div>
                                    
								</div>
							</div>
					</div>
				</div>
            <div class="col-lg-6 col-md-6 col-sm-12 mx-auto d-block askaquoteVerticalsec">
             <!-- Start ask a quote Section -->
                    <div class="askaquoteVerticalinnersec" id="getintuchid">
                        <h2>Get In Touch</h2>
            			<span class="bottomLineImgStyle"></span>
            			<form action="/askaquote" method="post">
                        {{ csrf_field() }}
                        <div class="row">
                                <div class="col-sm-12">
                                    <div class="inner-cuote-sec">
                                        <div class="form-group">
                                            <input type="text" name="name" class="form-control" name="name"  placeholder="Type Your Name" required="">
                                        </div>
                                    </div>
                                </div>
                               <div class="col-sm-12">
                                    <div class="inner-cuote-sec">
                                        <div class="form-group">
                                            <input type="email" name="email" class="form-control" name="email" placeholder="Type your Email" required="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="inner-cuote-sec">
                                        <div class="form-group">
                                         <textarea class="form-control" id="message-text" rows="5" name="message" placeholder="Type your Message" required=""></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-12">
                                    <div class="inner-cuote-sec m-auto">
                                        <div class="form-group">
                                            <button type="submit" class="sub-buttonclass">Submit Request</button> <p>We Will Never Spam Your Inbox</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                   </div>
            <!-- End ask a quote Section -->
				</div>
			</div>
		</div>
</div>
<!-- End FAQS RELATED TO Section -->
<!-- New Start bannerFirst Section -->
    <section class="happyclientsec">
                      <div class="container text-center">
                    
                        <div class="row">
                           <div class="col-lg-12 col-md-12">
                            <ul>
                              <li><img src="assets/img/clientcomicon/icon1.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon2.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon3.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon4.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon5.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon6.jpg" alt=""></li>
                              <div class="hcheader"><h2> Our Clients | Our Strength </h2><h4> Some of our esteemed customers </h4></div>
                              <li><img src="assets/img/clientcomicon/icon7.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon8.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon9.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon10.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon11.jpg" alt=""></li>
                              <li><img src="assets/img/clientcomicon/icon12.jpg" alt=""></li>
                            </ul>
                          </div>
                        </div>
                        
                      </div>
    </section>
<!-- New End bannerFirst Section -->
<!-- Start customers think about us Section -->
	<div class="container-fluid customersthinkaboutus-sec">
		<div class="container">
			<h2>Words From Our Clients </h2>
			<h3>Our Valued Customers Believe In Us & This Is What Keeps Us Going </h3>
			<span class="bottomLineImgStyle"></span>
			
			
			
			<div class="customersthinkaboutus-innersec">
			
			
					<div class="customersthinkaboutus-innerleftsec">
						<div class="innerleftsec-box">
							
						</div>
					</div>
					<div class="customersthinkaboutus-innerrightsec">
					
						 <div class="parent-box6 topSlider6 owl-carousel">

										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Angus Walls</h3>
													<h4> Xlife Enterprices</h4>
													
												</div>
										</div>
										
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/cont-sec/web_dev_testimonials_icon-2.jpg" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														My site travertinemart.com has gained high rankings on Google 
														within 8 months of trying their dedicated SEO plan. Anki was very 
														helpful in creating a customized SEO package for me. It was a 
														great experience working with his team. Now my site is user 
														friendly and ranks on first page of major search engines.
													</p>
													<h3> Evrim Oralkan </h3>
													<h4> Travertine Mart </h4>
												</div>
										</div>
										<div class="box6">
												<div class="box-left-sec">
													<img src="assets/img/user_md_2.png" alt="">
												</div>
												<div class="box-right-sec">
													<div class="cote-st">
														<img src="assets/img/icons/cote-icon.png">
													</div>
													
													<p>
														I am associated with SeoEaze Since start & they have taken perfect care of our digital marketing campaign ever since. Our business growth was exponential after we chose SeoEaze. They Helped our Site rank on top for our industry's most searched keyword.<br><br>
														
													</p>
													<h3> Angus Walls</h3>
													<h4> Xlife Enterprices</h4>
												</div>
										</div>
								</div>
						</div>
					</div>

			</div>
		

	</div>

 <!-- End customers think about us Section  -->

<!-- Start SOME HAPPY CLIENTS  Section --> 
<div class="container-fluid featureandclient-sec">
	<div class="container">
		
			<div class="row">

				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="featureandclient-innersec">
							<h3 class="whitecolor"> OUR ACHIEVEMENTS: OUR PRIDE </h3>
						    <span class="bottomLineImgStyle"></span>
						    <p> 
								</p><ul>
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon1.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon2.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon3.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon4.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon5.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon6.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon7.png"></a></li>
									
									<li>
										<a href="" class="se_avards_cons fade-in-animate visible"><img src="assets/img/blog-management/featureandclient-icon/ourachivementsandpride-icon8.png"></a></li>
									
								</ul>	
							<p></p>
					</div>
				</div>
			</div>
	</div>
</div>
<!-- End SOME HAPPY CLIENTS  Section -->                        
                                            
                                            
                                            
                                            
                                    




@endsection